\legacy_if:nT
\coffin_gset_vertical_pole:Nnn
\regex_replace_once:nnNTF
\bool_lazy_or:nnT
\text_titlecase_first:n
\msg_redirect_module:nnn
\clist_if_exist:cF
\str_uppercase:f
\regex_set:Nn
\prop_gremove:cn
\tl_head:v
\prop_const_from_keyval:Nn
\prop_pop:NnN
\prop_if_exist:NF
\bool_set_true:c
\seq_gsort:cn
\seq_gset_from_clist:NN
\ior_open:cnT
\cs_if_free:cTF
\peek_charcode_remove:NF
\fparray_gzero:N
\str_log:N
\clist_gpush:co
\int_use:c
\l_tmpa_fp
\use_i_delimit_by_q_stop:nw
\keys_set_groups:nnn
\dim_if_exist_p:c
\tl_gset_rescan:Nno
\regex_split:NnNTF
\muskip_gset_eq:Nc
\str_if_eq_p:nV
\peek_regex_replace_once:NnT
\cs_set_protected:cn
\prop_gput_if_new:cnn
\box_gset_eq_drop:Nc
\char_to_utfviii_bytes:n
\tl_set_eq:NN
\skip_gsub:Nn
\quark_if_recursion_tail_stop_do:Nn
\cctab_gset:Nn
\tl_range_unbraced:nnn
\muskip_new:N
\str_put_left:Nn
\tl_sort:cn
\tl_replace_once:Nnn
\exp_args:NNo
\peek_N_type:T
\tl_if_novalue:nF
\intarray_new:Nn
\tl_show:n
\prop_put:con
\clist_rand_item:n
\seq_if_in:NvT
\cs_parameter_spec:N
\dim_gzero:c
\token_if_muskip_register:NF
\bool_if_exist:NF
\str_put_left:NV
\keys_set:nv
\skip_if_exist:cF
\box_if_horizontal:cF
\fp_show:N
\ior_map_break:
\if_mode_math:
\msg_none:nnn
\cctab_end:
\tl_set_rescan:cno
\tl_item:Nn
\cs_gset_protected_nopar:cpn
\bool_gset_false:N
\token_case_meaning:Nn
\box_ht_plus_dp:c
\str_gset_convert:NnnnT
\int_log:n
\vbox_gset_top:cn
\str_gset_eq:NN
\tl_to_str:N
\seq_pop:cNTF
\keys_set_known:nnN
\c_circumflex_str
\peek_catcode_remove:NF
\char_set_catcode_escape:N
\clist_set:No
\clist_gset_eq:Nc
\str_if_exist:cF
\str_count_spaces:c
\seq_const_from_clist:Nn
\seq_get_left:cN
\char_gset_active_eq:nN
\token_if_eq_catcode:NNTF
\lua_now:e
\sys_if_platform_unix:T
\tl_range:Nnn
\int_step_inline:nnnn
\sort_return_same:
\l_tmpb_coffin
\bool_const:Nn
\regex_split:nnNTF
\peek_catcode:NTF
\peek_regex_remove_once:nF
\cs_gset_protected:Nn
\ior_close:c
\g_tmpa_str
\file_compare_timestamp_p:nNn
\char_value_sfcode:n
\str_if_eq_p:nn
\prop_set_from_keyval:Nn
\int_case:nn
\seq_pop_item:cnNTF
\l_char_special_seq
\hbox_set_end:
\bool_case_true:n
\prop_get:coNTF
\g_tmpa_coffin
\bool_if_p:n
\str_gput_left:NV
\int_gadd:cn
\quark_if_nil_p:V
\seq_gpop:NNT
\char_set_catcode_alignment:N
\token_if_dim_register:NTF
\char_gset_active_eq:nc
\fp_show:c
\cs_set_protected:cx
\bool_lazy_and:nnTF
\msg_redirect_name:nnn
\tl_gset_rescan:cnn
\muskip_zero_new:c
\skip_sub:Nn
\seq_gpush:cv
\coffin_gresize:cnn
\dim_ratio:nn
\msg_show:nnxx
\token_if_parameter:NT
\cs_if_exist_use:cT
\tl_range_braced:cnn
\prg_break_point:Nn
\ior_if_eof_p:N
\tl_analysis_log:N
\seq_gput_right:Nx
\c_max_skip
\tl_gput_left:Nn
\ior_show:c
\quark_if_recursion_tail_stop:o
\tl_if_empty:NT
\tl_if_head_eq_charcode:fNTF
\clist_push:Nx
\box_if_empty:cTF
\bool_set_false:c
\fp_if_nan:nT
\fp_log:N
\int_show:n
\cs_if_exist_use:cF
\prop_put:cxx
\token_if_font_selection:NT
\clist_gclear:N
\iow_wrap:nnnN
\l_text_math_arg_tl
\char_set_catcode_group_begin:N
\box_log:c
\clist_set_eq:cc
\skip_new:N
\seq_get:cNTF
\token_if_group_begin:NTF
\clist_if_empty:NF
\fp_gsub:cn
\l_tmpa_int
\tl_gput_right:No
\vbox_set:cn
\int_to_Roman:n
\clist_gput_left:Nn
\vbox_set:Nw
\intarray_gset:cnn
\prop_pop:cnNF
\cs_to_str:N
\exp_args:Nnnx
\l_color_math_active_tl
\cs_new_protected:Npn
\vbox_set:Nn
\c_one_degree_fp
\coffin_gset_eq:NN
\box_set_wd:Nn
\tl_gput_right:cn
\if_case:w
\coffin_if_exist_p:c
\tl_gset_rescan:cnx
\token_if_space:NTF
\regex_new:N
\dim_const:cn
\str_if_eq_p:ee
\tl_gclear_new:N
\msg_warning:nnnnn
\peek_meaning_collect_inline:Nn
\tl_put_left:Nx
\cs_set_nopar:Nn
\exp_last_unbraced:NNf
\tl_map_inline:cn
\box_resize_to_ht:cn
\msg_critical:nn
\int_gsub:cn
\sys_if_rand_exist_p:
\str_case:NnF
\box_set_wd:cn
\exp_last_unbraced:Nv
\seq_log:c
\ior_open:cnF
\msg_none:nnnn
\tl_reverse_items:n
\fp_compare:nTF
\group_end:
\int_gset_eq:cc
\prop_get:NnNT
\sys_if_engine_ptex_p:
\char_value_uccode:n
\str_if_eq:nnF
\seq_put_left:No
\dim_compare:nNnF
\l_tmpa_coffin
\tl_set:Nv
\int_if_even_p:n
\exp_args:Nc
\seq_gset_eq:NN
\c_str_cctab
\regex_replace_case_once:nN
\token_if_long_macro_p:N
\fp_trap:nn
\tl_gset_eq:Nc
\seq_gpop:NNTF
\tl_remove_once:Nn
\cs_if_exist:NTF
\tl_set:Nf
\token_to_str:N
\seq_use:Nnnn
\tl_gput_right:Nx
\cs_gset_nopar:cx
\clist_if_exist:cTF
\cs_gset:Nx
\seq_gconcat:ccc
\iow_log:c
\tl_if_empty:VTF
\c_math_toggle_token
\box_clip:c
\group_show_list:
\bool_if:cTF
\clist_if_in:coT
\color_math:nnn
\tl_gtrim_spaces:c
\tl_put_left:cn
\cs_new_nopar:cn
\dim_if_exist_p:N
\ProvidesExplClass
\str_compare_p:eNe
\clist_set:Nn
\bool_do_while:Nn
\seq_pop_right:cNF
\clist_if_in:coF
\cs_gset:cpx
\fp_gset:Nn
\prg_map_break:Nn
\text_lowercase:n
\tl_log:c
\fp_sub:Nn
\cs_split_function:N
\skip_zero:N
\str_new:N
\seq_gpop_left:cN
\regex_replace_once:nnNF
\regex_replace_all:nnNTF
\prop_get:NnNTF
\clist_const:Nx
\str_gput_right:NV
\cs_if_free:NTF
\cs_undefine:N
\c_zero_fp
\seq_pop_left:NN
\cs_new:Npn
\peek_catcode_remove:NT
\regex_extract_all:NnNT
\iow_now:Nn
\c_max_muskip
\c_zero_skip
\vbox_gset:cn
\tl_if_empty_p:n
\token_if_int_register_p:N
\seq_gpush:NV
\c_math_superscript_token
\box_gset_eq_drop:cN
\quark_if_recursion_tail_stop:N
\coffin_gset_eq:Nc
\coffin_set_eq:cN
\exp_args:NNox
\muskip_log:n
\quark_if_no_value:cTF
\tl_if_empty:cTF
\str_if_exist_p:c
\sys_if_engine_uptex_p:
\q_recursion_tail
\exp_last_two_unbraced:Noo
\seq_gput_right:NV
\seq_gput_right:cx
\clist_gclear_new:c
\seq_if_empty:NTF
\int_if_exist:NTF
\int_to_Base:nn
\token_if_eq_charcode:NNTF
\l_text_accents_tl
\tl_count_tokens:n
\reverse_if:N
\cs_new_eq:NN
\clist_if_in:cnT
\cctab_item:cn
\seq_concat:ccc
\prop_gput:Nnx
\g_tmpa_skip
\fp_if_nan:nF
\skip_show:c
\seq_gpush:No
\tl_gconcat:NNN
\seq_set_from_clist:NN
\seq_remove_duplicates:c
\c_log_iow
\prop_get:cVNF
\char_set_catcode_math_subscript:N
\fp_const:Nn
\vcoffin_set:cnw
\exp_end_continue_f:w
\token_if_eq_catcode_p:NN
\prop_new:c
\msg_info:nnx
\seq_pop_right:cNT
\str_if_eq:ccF
\bool_if:nF
\dim_set_eq:cc
\pdf_destination:nnnn
\char_set_catcode_alignment:n
\file_get_full_name:VN
\int_zero:c
\int_do_while:nn
\msg_term:nnn
\str_compare:nNnT
\fp_if_exist:NT
\msg_fatal:nnxx
\seq_set_from_inline_x:Nnn
\prop_gput_if_new:Nnn
\cs_gset_protected:cx
\token_if_eq_charcode:NNT
\box_use:c
\hbox_set:Nw
\tl_range_unbraced:Nnn
\g_tmpb_seq
\pdf_object_if_exist:nT
\dim_case:nnT
\skip_new:c
\cs_gset_protected_nopar:Npn
\box_if_exist:cF
\cctab_const:Nn
\tl_greverse:c
\tl_if_eq:ccT
\sys_get_shell:nnNTF
\hbox:n
\dim_gset_eq:cc
\int_do_until:nn
\bool_to_str:c
\tl_build_gend:N
\str_use:N
\exp_args:NNNv
\seq_gput_left:cn
\box_gset_wd:Nn
\cs_set_protected:Npn
\tl_if_blank:nF
\regex_match:NnF
\prop_put:Nnn
\token_case_catcode:NnTF
\msg_critical:nnnnnn
\msg_error:nnnnnn
\seq_gpop_right:NN
\coffin_gset_horizontal_pole:Nnn
\token_if_mathchardef_p:N
\dim_while_do:nNnn
\int_if_exist:cF
\clist_gput_right:Nn
\str_replace_all:cnn
\pdf_uncompress:
\file_full_name:V
\seq_get:NNT
\iow_new:N
\str_compare:nNnF
\token_if_math_superscript_p:N
\tl_map_break:
\dim_case:nn
\fp_abs:n
\cs_new_nopar:cx
\bool_to_str:N
\peek_meaning:NTF
\msg_log:nnx
\clist_gpush:Nx
\token_if_letter:NTF
\fp_to_int:c
\exp_last_unbraced:Ne
\seq_map_tokens:Nn
\str_if_eq:NNT
\clist_push:No
\cs_gset_nopar:cpn
\hbox_gset_to_wd:Nnw
\tl_set:co
\tl_tail:N
\seq_gset_eq:cc
\hbox_overlap_left:n
\hbox_unpack_drop:c
\c_sys_engine_str
\int_decr:c
\quark_if_nil:NT
\msg_warning:nnnnnn
\keys_set_known:nV
\seq_set_item:cnnTF
\msg_log:nnn
\c_zero_muskip
\skip_vertical:c
\tl_case:cnT
\clist_gput_right:Nx
\prop_if_exist:cTF
\str_gput_right:Nx
\cs_if_exist_p:c
\tl_concat:ccc
\regex_extract_all:nnNT
\clist_put_left:No
\keys_if_exist:nnT
\keys_if_exist:neF
\prop_gput:Nvx
\cctab_begin:N
\exp_args:Nxx
\tl_if_eq:ccTF
\flag_raise_if_clear:n
\msg_show_item_unbraced:nn
\str_if_eq_p:NN
\clist_gremove_all:cV
\bool_until_do:cn
\tl_gput_right:co
\keys_if_exist:nnTF
\dim_zero:N
\sys_if_shell_unrestricted:F
\ior_open:cnTF
\coffin_set_horizontal_pole:Nnn
\clist_remove_all:NV
\str_map_function:cN
\seq_put_right:cx
\iow_shipout_x:Nn
\prop_set_eq:cN
\vbox_set_split_to_ht:cNn
\pdf_version_compare:NnT
\fp_set_eq:NN
\tl_if_eq:nnT
\int_step_inline:nnn
\clist_if_in:NnF
\token_if_long_macro:NT
\int_if_exist:NF
\seq_new:c
\quark_if_nil_p:o
\prop_set_eq:Nc
\str_case:VnF
\tl_if_head_is_space_p:n
\seq_gput_left:Nv
\iow_shipout:Nn
\tl_if_empty:oTF
\use_ii:nnn
\tl_if_exist:NT
\token_if_alignment:NTF
\token_if_active:NF
\seq_set_split:Nnn
\coffin_gjoin:Nnncnnnn
\c_tilde_str
\cs_set_protected_nopar:Nn
\token_if_active:NT
\cs_if_exist_use:NT
\bool_set_true:N
\box_clear_new:N
\use:nnn
\token_if_letter:NF
\ior_open:NnF
\prop_log:N
\muskip_gzero_new:c
\tl_head:n
\token_if_protected_long_macro:NF
\bool_set_inverse:N
\keys_set_known:nonN
\int_from_bin:n
\tl_greplace_all:cnn
\clist_sort:cn
\exp_args:Nox
\cs_gset_protected_nopar:Nx
\cs_if_eq:NNTF
\pdf_object_unnamed_write:nx
\c_math_subscript_token
\file_compare_timestamp:nNnF
\quark_if_nil:oT
\tl_if_head_is_group:nT
\fp_gsub:Nn
\regex_match_case:nnT
\fp_gadd:cn
\clist_if_empty:cT
\tl_set_rescan:Nnx
\vbox_set_top:Nn
\tl_case:cn
\seq_gpop_left:NNF
\dim_if_exist:NF
\exp_args:Ncv
\cctab_if_exist:cTF
\clist_gremove_duplicates:N
\exp_args:Nffo
\skip_horizontal:N
\int_set_eq:Nc
\prop_count:c
\clist_if_exist:NTF
\token_case_meaning:NnTF
\pdf_version_gset:n
\clist_log:n
\box_set_to_last:N
\bool_if_exist_p:N
\int_sign:n
\tl_if_empty:oT
\seq_pop_right:NN
\seq_get:NN
\cs_log:c
\int_from_roman:n
\seq_pop_item:NnNTF
\coffin_set_vertical_pole:cnn
\clist_get:NNTF
\str_concat:ccc
\clist_show:n
\token_if_other:NTF
\l_tmpa_skip
\str_set_eq:NN
\peek_catcode:NT
\prop_gset_from_keyval:Nn
\g_tmpb_tl
\g_tmpb_int
\file_get_hex_dump:nnnNT
\bool_case_false:n
\ior_new:N
\bool_if_exist_p:c
\intarray_rand_item:N
\int_compare_p:nNn
\dim_zero:c
\seq_pop:NNTF
\clist_map_function:NN
\str_if_empty:nF
\tl_if_head_eq_meaning:nNF
\keys_set:no
\c_left_brace_str
\sys_if_engine_uptex:TF
\cs_gset_protected:cpn
\seq_pop:NN
\use_none:nnnnnn
\fp_eval:n
\str_put_right:NV
\msg_info:nnxxx
\prg_set_conditional:Nnn
\use_i_delimit_by_q_nil:nw
\box_use:N
\token_to_str:c
\box_gresize_to_ht:Nn
\regex_replace_once:NnNTF
\skip_gzero:N
\iow_newline:
\prop_put:NVn
\sys_if_shell_restricted:F
\prop_gput:NVV
\msg_log:nnxxx
\regex_replace_all:nnNF
\seq_set_from_clist:Nn
\muskip_gset_eq:cc
\box_gclip:N
\str_show:c
\keys_set_known:no
\keys_set_filter:nnonN
\msg_line_number:
\vbox_gset:cw
\clist_greverse:c
\clist_set:cV
\sys_if_engine_pdftex:TF
\vcoffin_set:Nnw
\keys_set_known:nn
\prg_set_protected_conditional:Npnn
\prop_if_empty:NTF
\tl_if_head_eq_catcode_p:oN
\tl_rand_item:c
\l_tmpb_int
\seq_push:cx
\quark_if_recursion_tail_stop_do:nn
\seq_pop_left:NNF
\clist_count:N
\intarray_log:c
\seq_reverse:N
\g_tmpb_regex
\cs_show:c
\flag_new:n
\seq_gpush:co
\str_gset_convert:NnnnF
\bool_gset_inverse:c
\token_if_mathchardef:NTF
\clist_set_from_seq:Nc
\seq_gput_left:cV
\int_zero_new:c
\seq_push:Nn
\int_compare:nNnTF
\mode_if_vertical:T
\clist_push:cn
\cs_if_free:NF
\tl_build_get:NN
\seq_gset_from_inline_x:Nnn
\int_step_function:nnnN
\clist_pop:cN
\c_parameter_token
\use_none:nnnn
\prop_gput:NnV
\token_if_macro:NTF
\seq_use:cn
\box_wd:N
\str_case:nv
\c_space_tl
\file_get_size:nNF
\cs_replacement_spec:N
\prg_new_protected_conditional:Npnn
\seq_gset_map_x:NNn
\str_if_eq:NcT
\file_get_hex_dump:nNF
\tl_gset:cn
\coffin_gset_eq:cc
\peek_remove_filler:n
\token_if_letter:NT
\ior_map_inline:Nn
\seq_gremove_duplicates:c
\quark_if_nil_p:n
\str_if_eq:nVF
\file_get:nnNT
\seq_get_left:cNTF
\tl_if_eq:nnF
\dim_use:N
\box_autosize_to_wd_and_ht_plus_dp:cnn
\token_if_protected_long_macro_p:N
\prop_get:NvNF
\keys_if_exist_p:nn
\seq_set_split_keep_spaces:Nnn
\fp_if_exist:NF
\vbox_gset_split_to_ht:NNn
\coffin_gattach:cnncnnnn
\int_if_exist_p:c
\ior_str_get_term:nN
\text_uppercase:n
\clist_if_in:cVF
\msg_critical:nnxx
\seq_if_exist:NF
\token_if_eq_meaning_p:NN
\fp_set_eq:cN
\seq_gput_left:cx
\bool_do_while:cn
\prg_generate_conditional_variant:Nnn
\c_sys_backend_str
\prop_put:cVx
\peek_meaning_remove:NT
\seq_put_left:co
\dim_log:n
\clist_if_empty:nTF
\seq_put_left:cv
\seq_if_in:cxTF
\tl_set_rescan:Nnn
\keys_if_choice_exist:nnnF
\token_if_group_begin:NT
\ior_log:c
\tl_case:Nn
\int_rand:nn
\prop_put:cnV
\clist_if_in:NnT
\str_tail:N
\seq_gpop_left:NNT
\msg_expandable_error:nnfff
\muskip_set:cn
\color_set_eq:nn
\g_tmpa_int
\token_if_protected_long_macro:NT
\prop_gput:Nxx
\sys_gset_rand_seed:n
\regex_log:N
\skip_log:n
\str_case:nn
\vbox_set_top:cn
\seq_gpop:NN
\fp_to_int:N
\clist_get:NNF
\color_log:n
\skip_add:Nn
\str_if_eq:nVT
\char_set_catcode_ignore:n
\hbox_gset:Nw
\clist_if_in:nnT
\use_i:nnnn
\str_gput_right:cn
\c_sys_day_int
\quark_if_no_value:nTF
\cs_set_nopar:cx
\char_set_catcode_math_subscript:n
\char_set_uccode:nn
\regex_replace_all:nnNT
\cs_new_eq:cN
\seq_gset_item:NnnTF
\str_if_eq:nVTF
\exp_args:NNnV
\cs_gset_nopar:Nn
\str_compare:eNeF
\g_tmpb_dim
\ior_map_variable:NNn
\exp_args:Nccx
\c_empty_coffin
\clist_gremove_all:Nn
\cs_set_protected_nopar:cpn
\l_tmpb_muskip
\clist_rand_item:N
\exp_not:v
\clist_if_in:NoF
\seq_gpop_right:cNF
\bool_xor:nnF
\hbox_gset:cw
\clist_gremove_all:cn
\tl_count:V
\msg_show:nn
\regex_match:NnTF
\str_if_eq:nvF
\msg_info:nnn
\int_show:N
\box_set_eq:NN
\sort_return_swapped:
\cs_new_protected_nopar:Nn
\token_if_expandable:NTF
\str_case:onTF
\clist_pop:cNTF
\sys_if_engine_xetex:TF
\color_if_exist:nT
\seq_gpop_item:NnNT
\str_if_in:nnT
\exp_args:Nx
\int_to_bin:n
\clist_remove_all:cV
\exp_args:Nff
\seq_reverse:c
\cs_end:
\ior_str_map_variable:NNn
\g_file_curr_name_str
\int_eval:n
\c_zero_dim
\seq_clear:c
\cs_gset_nopar:cpx
\bool_lazy_all:nT
\seq_map_variable:cNn
\clist_if_in:cnF
\skip_show:n
\dim_gset_eq:NN
\tl_gset_rescan:Nnn
\prop_gconcat:ccc
\vbox_gset:Nw
\msg_fatal:nnnnn
\regex_match:nnF
\tl_to_str:n
\prop_gset_eq:cc
\prop_put:NVV
\str_if_eq_p:nv
\fp_if_exist:cT
\g_tmpb_iow
\sys_if_engine_luatex:TF
\tl_gput_left:cx
\box_set_eq_drop:cc
\char_set_catcode_math_superscript:N
\seq_get_right:cNF
\skip_sub:cn
\bool_if:cF
\sys_if_rand_exist:T
\token_case_catcode:Nn
\msg_show_item:n
\dim_compare_p:n
\hbox_set_to_wd:Nnn
\seq_pop_left:cNTF
\box_if_exist:NTF
\cs_new_protected_nopar:Npn
\char_value_catcode:n
\skip_if_exist_p:N
\bool_if_exist:cF
\str_set:cV
\str_gconcat:ccc
\msg_gset:nnn
\msg_note:nn
\seq_mapthread_function:cNN
\clist_gpop:cN
\legacy_if_gset:nn
\c_space_token
\seq_gset_item:cnnF
\c_max_char_int
\char_set_catcode_math_toggle:N
\coffin_if_exist:NTF
\cs_meaning:c
\muskip_log:N
\box_if_empty_p:N
\if_eof:w
\intarray_gset_rand:cn
\clist_use:cnnn
\clist_if_in:NVTF
\tl_if_head_eq_catcode_p:nN
\s_stop
\l_tmpb_str
\cs_set:Npx
\msg_error:nnx
\str_clear_new:c
\tl_gput_right:cV
\tl_if_head_eq_meaning:nNTF
\tl_greplace_all:Nnn
\prop_if_empty_p:N
\clist_push:Nn
\muskip_zero:N
\clist_if_exist_p:c
\tl_reverse:c
\vbox_set_to_ht:cnn
\clist_gpush:cx
\sys_if_engine_luatex:F
\str_case:nnF
\box_rotate:Nn
\box_clear:N
\prop_put:NVx
\str_case:VnT
\exp_args:Nxo
\tl_if_single:cT
\token_if_math_toggle:NF
\coffin_gset_eq:cN
\bool_new:N
\quark_if_nil:VF
\coffin_resize:cnn
\dim_gset:Nn
\cs_gset_protected_nopar:Npx
\use_none_delimit_by_q_stop:w
\tl_gset:NV
\seq_pop:cNF
\box_if_horizontal:NF
\box_gautosize_to_wd_and_ht_plus_dp:Nnn
\prop_if_exist_p:c
\intarray_new:cn
\clist_if_in:NoT
\clist_put_right:co
\tl_sort:nN
\msg_fatal:nnnnnn
\vbox_gset_split_to_ht:Ncn
\bool_lazy_or_p:nn
\keys_set_groups:nnv
\token_if_space:NT
\cs_set_eq:Nc
\clist_if_in:noT
\seq_get_right:NNF
\hbox_overlap_right:n
\tl_count:N
\bool_lazy_any:nTF
\tl_item:cn
\skip_use:N
\vbox_gset:Nn
\str_case:nnT
\lua_now:n
\text_declare_expand_equivalent:cn
\coffin_gset_horizontal_pole:cnn
\peek_regex:NF
\token_if_eq_catcode:NNT
\tl_new:N
\box_if_exist:cT
\quark_if_nil:oF
\prop_item:cn
\token_if_math_superscript:NTF
\box_scale:Nnn
\str_if_eq_p:no
\peek_regex_remove_once:NT
\clist_gclear:c
\tl_replace_all:Nnn
\cs_if_exist_use:N
\msg_warning:nnxxxx
\intarray_show:N
\str_head:c
\sys_if_platform_unix:TF
\seq_get_left:NNTF
\box_log:Nnn
\str_put_right:Nx
\tl_set:Nx
\clist_if_in:nVF
\text_map_function:nN
\prop_pop:NnNTF
\token_if_math_subscript_p:N
\bool_lazy_all_p:n
\msg_expandable_error:nnf
\text_case_switch:nnnn
\prg_break:n
\prop_get:cvNT
\tl_if_eq:NnTF
\vbox_unpack_drop:c
\seq_if_in:cVT
\str_gset_eq:cc
\token_if_other:NT
\tl_if_empty:nF
\char_set_catcode_active:n
\skip_set_eq:cN
\iow_now:cx
\char_show_value_uccode:n
\token_if_dim_register:NT
\use_none:nnnnnnnnn
\ior_new:c
\msg_note:nnnnn
\tl_put_left:co
\clist_count:c
\muskip_eval:n
\cs_new_nopar:Npx
\fp_gzero_new:N
\c_atsign_str
\tl_if_exist:NF
\use_i_delimit_by_q_recursion_stop:nw
\seq_if_exist:NTF
\exp_last_unbraced:NV
\seq_if_empty:NT
\regex_replace_case_all:nNTF
\skip_if_exist_p:c
\token_case_catcode:NnT
\fp_new:N
\msg_log:nn
\tl_if_head_eq_catcode:oNF
\coffin_ht:N
\str_if_eq:eeT
\seq_set_from_clist:cc
\flag_if_exist:nT
\str_item:nn
\sys_timer:
\seq_gset_item:NnnT
\tl_if_in:cnT
\keys_if_exist:nnF
\tl_count:o
\clist_log:c
\seq_map_function:NN
\seq_gpop_right:cNTF
\seq_get:NNF
\token_if_skip_register_p:N
\tl_gput_right:NV
\exp_args:Nnnf
\fi:
\group_begin:
\clist_gpush:cn
\iow_wrap:nxnN
\coffin_resize:Nnn
\exp_last_unbraced:Nno
\clist_clear:N
\g_tmpb_bool
\quark_if_nil:nTF
\coffin_show:cnn
\exp_args:NNv
\prop_log:c
\str_if_eq:NcF
\file_get:nnN
\exp_args:Nof
\file_get_full_name:VNTF
\l_tmpb_dim
\str_item_ignore_spaces:nn
\fparray_count:N
\clist_concat:ccc
\prop_pop:cnN
\prop_pop:NoN
\exp_not:n
\str_case:nVF
\clist_set:cn
\box_if_horizontal:cTF
\seq_gpop:cNT
\msg_note:nnxxx
\if_box_empty:N
\sys_if_engine_ptex:T
\char_to_nfd:n
\regex_count:nnN
\int_gset_eq:NN
\str_map_break:n
\cs_set_protected:Nx
\quark_if_nil:NF
\bool_gset_eq:cc
\bool_show:N
\prop_get:coN
\coffin_gclear:c
\str_put_left:cn
\str_gset:NV
\token_if_eq_charcode_p:NN
\fp_compare:nF
\l_tmpb_skip
\char_titlecase:N
\cs_new_nopar:Npn
\peek_charcode:NT
\tl_analysis_map_inline:Nn
\exp_args:NcNo
\tl_if_blank:oF
\flag_if_exist_p:n
\c_catcode_other_token
\clist_if_empty:nT
\str_head_ignore_spaces:n
\cs_if_exist_p:N
\file_if_exist:nTF
\prop_gput:cVV
\use_none_delimit_by_q_nil:w
\seq_put_right:cv
\file_hex_dump:nnn
\fp_const:cn
\token_if_parameter:NF
\fp_if_exist_p:c
\token_if_macro:NT
\file_size:n
\keys_set_known:nVN
\box_if_vertical:cF
\tl_if_eq:cNTF
\skip_if_exist:cT
\str_if_eq:NcTF
\clist_item:Nn
\ior_get:NN
\l_tmpa_str
\prop_gput:cVn
\use:n
\prop_get:cVNTF
\prop_remove:cn
\seq_get:cNT
\box_gresize_to_ht_plus_dp:Nn
\int_from_alph:n
\vcoffin_set:Nnn
\file_get_hex_dump:nN
\str_set_eq:Nc
\clist_pop:cNF
\muskip_use:N
\ior_get:NNF
\bool_show:c
\file_get_mdfive_hash:nN
\keys_set_filter:nno
\int_compare:nF
\dim_const:Nn
\prop_gclear_new:c
\muskip_if_exist:NT
\box_clear_new:c
\msg_term:nnxxx
\prop_if_in_p:co
\cs_set_nopar:Npn
\cs_gset:cn
\fp_use:c
\str_const:NV
\cs_gset:Npx
\char_set_catcode_end_line:N
\coffin_gset_vertical_pole:cnn
\exp_args:NNV
\token_case_charcode:NnTF
\cctab_if_exist:cT
\tl_trim_spaces:n
\regex_match:nnT
\legacy_if_set_false:n
\c_sys_platform_str
\clist_map_inline:nn
\dim_log:N
\clist_gput_left:No
\clist_put_right:Nn
\tl_if_single_token_p:n
\token_if_long_macro:NF
\sys_if_shell_unrestricted:T
\bool_new:c
\char_gset_active_eq:NN
\prop_if_in:cVTF
\char_str_lowercase:N
\seq_pop_item:cnNF
\seq_get_right:cNT
\muskip_gset:cn
\use:nnnn
\str_case:nvTF
\prop_if_in:NoF
\flag_if_raised_p:n
\clist_set_from_seq:cc
\hbox_gset_end:
\clist_put_left:cV
\str_gset_convert:Nnnn
\tl_if_head_is_group_p:n
\g_msg_module_type_prop
\tl_if_head_eq_charcode_p:fN
\token_case_charcode:NnF
\skip_if_exist:NTF
\seq_pop:cN
\hcoffin_set:Nw
\peek_remove_spaces:n
\box_resize_to_wd_and_ht_plus_dp:Nnn
\seq_gset_eq:cN
\c_false_bool
\seq_put_left:NV
\token_if_macro:NF
\int_if_exist_p:N
\skip_if_finite:nF
\char_set_active_eq:NN
\box_gresize_to_ht:cn
\tl_if_blank:nTF
\tl_if_single:cTF
\muskip_const:Nn
\clist_set:Nx
\coffin_dp:N
\str_map_variable:NNn
\box_resize_to_wd_and_ht:cnn
\tl_reverse:V
\exp_args:Ncc
\tl_clear:c
\cs_if_exist_use:NTF
\int_if_even:nTF
\cs_new:cpx
\msg_expandable_error:nnnn
\peek_meaning_remove:NF
\file_full_name:n
\msg_fatal:nnxxxx
\exp_args:NNnx
\box_set_trim:cnnnn
\skip_log:c
\cs_set_protected:cpx
\cs_gset_protected_nopar:cn
\cs_if_exist:cF
\seq_map_function:cN
\int_sub:Nn
\keys_if_choice_exist:nnnTF
\clist_clear:c
\exp_stop_f:
\mode_if_inner:TF
\tl_log:N
\hbox_to_zero:n
\bool_if_exist:NTF
\seq_pop_right:NNF
\quark_if_no_value:NF
\tl_gput_left:cn
\clist_const:Nn
\clist_gput_left:cx
\legacy_if:nF
\clist_pop:NNT
\cs_set_protected_nopar:cx
\coffin_if_exist:NT
\box_show:c
\int_compare:nTF
\prop_get:cnN
\coffin_gjoin:NnnNnnnn
\cs_generate_variant:cn
\keys_set_filter:nnvnN
\seq_if_in:NVT
\mode_if_horizontal_p:
\tl_put_left:cx
\str_if_empty_p:n
\vcoffin_gset:Nnn
\int_gzero_new:c
\prop_show:N
\token_to_meaning:N
\text_declare_purify_equivalent:Nn
\str_const:Nx
\fp_gzero_new:c
\prop_gput:Non
\muskip_gset_eq:NN
\cctab_new:c
\clist_if_empty:NT
\dim_sub:Nn
\if_dim:w
\token_case_charcode:NnT
\dim_gadd:cn
\peek_meaning_remove:NTF
\if_hbox:N
\seq_gput_left:Nx
\muskip_if_exist:NF
\int_eval:w
\tl_if_single:cF
\coffin_if_exist:cT
\exp_last_unbraced:Nco
\file_compare_timestamp:nNnTF
\ior_log:N
\ior_shell_open:Nn
\sys_if_rand_exist:F
\cs_generate_from_arg_count:NNnn
\ior_if_eof:NTF
\msg_expandable_error:nnnnnn
\tl_if_eq_p:cN
\tl_if_eq:cnTF
\peek_catcode_collect_inline:Nn
\regex_replace_all:NnNTF
\keys_set_filter:nnVN
\prop_concat:ccc
\int_if_exist:NT
\clist_if_in:nnTF
\token_if_toks_register:NF
\q_no_value
\msg_show:nnxxx
\regex_replace_all:NnN
\color_set:nn
\token_if_math_superscript:NF
\file_get:nnNF
\prop_pop:cnNTF
\tl_put_right:co
\intarray_to_clist:N
\str_map_variable:nNn
\int_show:c
\bool_set_inverse:c
\dim_to_fp:n
\box_gresize_to_wd_and_ht_plus_dp:Nnn
\prop_if_in:NVT
\iow_close:N
\clist_if_in:NoTF
\str_case:on
\prop_gpop:cnN
\box_if_exist:NF
\msg_expandable_error:nnffff
\tl_if_blank:oTF
\c_empty_box
\use_none_delimit_by_s_stop:w
\use_none:nnn
\str_gremove_all:cn
\box_gset_eq_drop:cc
\msg_none:nnnnnn
\str_gclear:c
\exp_args:Nee
\fp_step_function:nnnc
\prg_new_conditional:Npnn
\seq_put_right:Nv
\exp_last_unbraced:NNNNf
\l_keys_choice_tl
\tl_map_inline:Nn
\coffin_clear:N
\cctab_select:N
\tl_log:n
\token_if_chardef:NTF
\peek_regex:nTF
\prop_gpop:coN
\prop_if_in:NnT
\str_const:cn
\tl_gsort:cn
\int_max:nn
\l_tmpb_bool
\exp_args:Nnox
\str_if_eq:VVTF
\token_if_math_superscript:NT
\c_sys_engine_format_str
\msg_critical:nnxxxx
\str_if_eq:ccT
\str_case:NnT
\l_tmpa_dim
\quark_new:N
\peek_regex_remove_once:NTF
\file_get_size:nN
\file_get_hex_dump:nNTF
\seq_set_split:NnV
\tl_if_blank:eT
\prop_pop:coN
\clist_set:cx
\seq_clear_new:N
\prop_get:NoNTF
\bool_case_true:nT
\msg_critical:nnnn
\seq_gput_left:NV
\group_align_safe_begin:
\c_novalue_tl
\tl_if_empty:VF
\int_new:N
\str_clear_new:N
\cs_if_exist:NF
\else:
\str_set_convert:NnnnF
\str_const:cx
\box_set_trim:Nnnnn
\str_case:NnTF
\seq_gset_from_clist:cn
\tl_head:f
\msg_warning_text:n
\msg_new:nnnn
\str_remove_all:cn
\g_tmpb_str
\hbox_unpack_drop:N
\clist_map_function:cN
\peek_analysis_map_inline:n
\ior_show_list:
\int_if_odd:nTF
\int_gset:cn
\seq_put_left:Nv
\use_iv:nnnn
\str_if_eq:nnT
\tl_set:cV
\cs_generate_from_arg_count:cNnn
\box_ht:c
\char_set_catcode_other:n
\sys_if_engine_pdftex_p:
\str_if_eq:nvTF
\exp_args:NVV
\str_if_exist:NT
\tl_new:c
\char_set_catcode_invalid:N
\char_set_catcode_space:n
\token_if_skip_register:NTF
\clist_gset_from_seq:NN
\seq_gset_from_clist:Nn
\peek_regex:NTF
\cs_gset:Nn
\int_mod:nn
\exp_args:NNx
\tl_if_in:nnT
\str_if_eq:vnTF
\tl_range:nnn
\file_get_timestamp:nNF
\mode_if_horizontal:TF
\msg_module_type:n
\file_get_mdfive_hash:nNT
\vcoffin_gset_end:
\box_clip:N
\seq_use:Nn
\msg_show:nnxxxx
\fp_sign:n
\int_gdecr:N
\clist_reverse:c
\clist_greverse:N
\seq_gpush:Nx
\file_log_list:
\cctab_if_exist:NTF
\str_if_eq:nvT
\c_right_brace_str
\tl_case:NnF
\clist_put_right:NV
\tl_gset:cV
\tl_greplace_once:Nnn
\cs_gset_eq:NN
\seq_gput_left:No
\tl_if_eq:nnTF
\peek_analysis_map_break:n
\iow_log:x
\coffin_clear:c
\text_uppercase:nn
\tl_if_single:nTF
\seq_map_tokens:cn
\exp_last_unbraced:NcV
\coffin_log:N
\flag_if_exist:nF
\seq_if_in:cvF
\c_catcode_letter_token
\ior_str_get:NNT
\box_gset_ht:Nn
\cctab_new:N
\tl_map_variable:nNn
\tl_set:cn
\seq_put_right:Nn
\coffin_log:Nnn
\exp_args:NNNo
\cs_set_protected_nopar:Nx
\seq_set_item:cnn
\prop_map_tokens:cn
\dim_if_exist:cF
\tl_if_empty:VT
\peek_analysis_map_break:
\or:
\seq_if_empty_p:N
\box_if_exist:cTF
\str_if_eq:eeTF
\fp_min:nn
\prop_gput:cnn
\cs_new:Npx
\ior_open:Nn
\sys_if_engine_luatex:T
\if_int_odd:w
\peek_regex_remove_once:nT
\ior_map_break:n
\muskip_show:n
\coffin_attach:cnnNnnnn
\muskip_set_eq:cN
\hcoffin_gset_end:
\box_gresize_to_wd_and_ht:Nnn
\quark_if_no_value:NT
\str_if_eq:NNF
\coffin_set_vertical_pole:Nnn
\str_range:Nnn
\regex_show:N
\str_foldcase:n
\prop_gremove:cV
\tl_build_begin:N
\str_if_exist:NF
\bool_if_exist:cT
\cs_new_nopar:cpx
\regex_replace_case_all:nNT
\prop_put:cnx
\sys_if_engine_luatex_p:
\peek_N_type:TF
\skip_show:N
\tl_clear:N
\skip_if_eq_p:nn
\muskip_add:cn
\text_purify:n
\tl_gremove_all:cn
\c_zero_int
\l_keys_usage_load_prop
\pdf_version_min_gset:n
\skip_set_eq:Nc
\skip_if_exist:NT
\str_lowercase:n
\box_gresize_to_wd:cn
\char_set_catcode_active:N
\bool_do_until:nn
\l_keys_usage_preamble_prop
\char_uppercase:N
\l_tmpa_tl
\sys_if_shell_p:
\clist_if_empty_p:n
\g_tmpb_fp
\str_clear:N
\coffin_show:c
\char_value_mathcode:n
\tl_if_eq:cNT
\dim_step_function:nnnN
\clist_get:cN
\seq_if_in:NoT
\prop_get:NvNTF
\int_step_variable:nnnNn
\c_sys_engine_version_str
\seq_pop_item:NnNF
\seq_set_map:NNn
\cs_gset_protected:Npx
\sys_if_engine_uptex:T
\tl_if_head_eq_charcode:fNT
\int_if_odd_p:n
\cs_new_protected_nopar:cpn
\token_if_font_selection:NTF
\msg_if_exist:nnTF
\tl_to_str:V
\prop_gset_eq:cN
\vbox_set:cw
\vbox_set_split_to_ht:ccn
\prop_put_if_new:Nnn
\box_gresize_to_ht_plus_dp:cn
\prop_put:Nno
\str_if_empty:nT
\tl_if_in:VnTF
\flag_if_raised:nF
\prop_gset_from_keyval:cn
\c_term_iow
\skip_if_finite_p:n
\c_empty_prop
\prg_set_conditional:Npnn
\regex_split:nnNF
\str_count:n
\seq_if_in:NxTF
\str_set:Nn
\tl_gput_left:NV
\q_mark
\str_put_right:cn
\regex_show:n
\prop_get:NvN
\file_get_full_name:VNF
\str_if_in:nnF
\keys_set_filter:nnv
\exp_args:Ncoo
\bool_if:nTF
\l_iow_line_count_int
\msg_show:nnn
\coffin_set_horizontal_pole:cnn
\cs_gset_nopar:cn
\token_if_eq_meaning:NNT
\color_model_new:nnn
\seq_rand_item:c
\coffin_show_structure:c
\file_get_full_name:VNT
\msg_if_exist_p:nn
\int_zero:N
\seq_pop_right:NNT
\str_case:nVT
\fp_use:N
\skip_if_eq:nnT
\exp_args:Nooo
\clist_if_exist:cT
\clist_if_exist:NT
\exp_args:NcnV
\token_if_skip_register:NF
\seq_get_right:NNT
\skip_gzero:c
\cs_new_eq:cc
\prop_gclear:N
\g_tmpa_box
\coffin_typeset:Nnnnn
\tl_if_in:nnF
\tl_const:Nn
\dim_gzero_new:c
\vbox_top:n
\sys_if_platform_unix:F
\char_show_value_lccode:n
\muskip_set:Nn
\text_map_break:
\str_clear:c
\msg_line_context:
\str_uppercase:n
\prop_get:coNT
\prop_gput:Nnn
\token_if_skip_register:NT
\tl_gput_right:cx
\prop_get:coNF
\coffin_gattach:cnnNnnnn
\sys_if_output_pdf:TF
\clist_use:nn
\seq_gset_from_clist:Nc
\hbox_set_to_wd:cnn
\box_if_empty:cT
\str_use:c
\mode_if_vertical:F
\prop_if_exist:NT
\seq_map_inline:Nn
\tl_range_unbraced:cnn
\l_keys_key_str
\box_gset_trim:cnnnn
\tl_build_put_right:Nn
\intarray_const_from_clist:Nn
\dim_new:c
\prop_if_in:cVF
\char_lowercase:N
\dim_to_decimal:n
\str_set_convert:NnnnT
\clist_use:Nn
\cs_new_protected:cx
\int_incr:c
\token_if_protected_macro_p:N
\keys_define:nn
\quark_if_no_value_p:n
\tl_if_empty_p:c
\fp_if_nan_p:n
\int_from_oct:n
\seq_pop_right:cNTF
\tl_if_eq:NNF
\msg_expandable_error:nnn
\bool_show:n
\skip_set_eq:NN
\clist_gput_right:No
\clist_gput_left:cn
\sys_if_shell_unrestricted:TF
\str_new:c
\hcoffin_set:Nn
\prop_remove:NV
\tl_gput_left:co
\seq_pop_left:cN
\clist_if_empty_p:N
\c_dollar_str
\coffin_new:N
\prop_gconcat:NNN
\quark_if_nil:VT
\msg_warning:nnn
\tl_if_blank:nT
\seq_gpop_left:NNTF
\tl_if_head_is_N_type_p:n
\int_div_round:nn
\ProvidesExplPackage
\str_if_eq:VVF
\box_gset_wd:cn
\seq_gput_right:co
\token_if_math_subscript:NF
\prop_if_in:NoT
\int_compare:nNnF
\int_gincr:c
\str_log:n
\char_foldcase:N
\clist_if_in:cnTF
\clist_gpop:NNTF
\bool_log:c
\int_new:c
\int_to_Hex:n
\skip_gadd:cn
\flag_clear:n
\legacy_if_p:n
\tl_if_empty:oF
\int_log:N
\token_if_chardef:NF
\bool_lazy_or:nnF
\mode_if_inner_p:
\seq_gpush:Nv
\vcoffin_gset:cnw
\bool_log:n
\fp_show:n
\box_if_vertical_p:c
\box_autosize_to_wd_and_ht:Nnn
\prop_put:cvx
\skip_if_eq:nnF
\clist_item:nn
\seq_set_eq:Nc
\clist_gpush:NV
\seq_pop_left:cNF
\tl_range_braced:Nnn
\fp_max:nn
\str_count:N
\str_if_eq:eeF
\l_tmpa_prop
\cs_new:cn
\debug_on:n
\tl_case:NnTF
\tl_map_tokens:Nn
\tl_if_head_eq_meaning_p:nN
\int_to_roman:n
\token_if_protected_macro:NT
\str_put_left:Nx
\int_case:nnTF
\seq_if_in:cxT
\str_foldcase:V
\seq_use:cnnn
\token_if_eq_meaning:NNF
\box_gresize_to_wd:Nn
\tl_gput_left:No
\seq_if_in:NxT
\vbox_gset_split_to_ht:cNn
\g_tmpb_skip
\fp_log:n
\regex_count:NnN
\coffin_log:c
\msg_none:nnxx
\clist_const:cn
\msg_log:nnnnn
\clist_if_in:noTF
\color_ensure_current:
\prop_if_in_p:cV
\text_map_break:n
\clist_reverse:n
\seq_gpop:cN
\exp_last_unbraced:NNNNo
\seq_gremove_duplicates:N
\fp_new:c
\tl_set:NV
\fp_log:c
\str_if_exist:NTF
\cs_generate_variant:Nn
\cs_new_protected_nopar:Npx
\tl_if_empty_p:o
\bool_case_true:nTF
\box_gclear:c
\dim_if_exist:NTF
\prop_map_tokens:Nn
\tl_if_novalue:nT
\pdf_object_ref_last:
\int_gdecr:c
\seq_if_empty:NF
\muskip_if_exist:cF
\str_map_inline:Nn
\str_if_empty_p:c
\seq_gpop:cNTF
\seq_gput_right:cv
\file_if_exist_input:nF
\quark_if_recursion_tail_stop:n
\token_if_cs:NF
\fp_to_scientific:N
\seq_gset_from_clist:cN
\seq_set_from_function:NnN
\char_set_catcode_parameter:N
\clist_gset:cV
\tl_map_function:NN
\intarray_gset_rand:cnn
\color_export:nnN
\text_declare_case_equivalent:Nn
\box_gset_dp:cn
\box_set_ht:Nn
\fp_set:cn
\bool_gset:Nn
\coffin_scale:cnn
\prop_put:cVV
\msg_fatal:nnx
\dim_until_do:nn
\clist_gset_from_seq:cc
\msg_error:nnnn
\box_set_eq:Nc
\prop_gput:cVx
\sys_if_output_pdf:T
\clist_put_left:cx
\skip_use:c
\cs_gset_protected:cpx
\q_recursion_stop
\sys_if_platform_unix_p:
\regex_extract_once:nnNTF
\prop_const_from_keyval:cn
\cs_set:Npn
\cs_new:cpn
\seq_if_in:NnT
\tl_gset:No
\pdf_version_major:
\color_stroke:nn
\dim_zero_new:c
\seq_gpush:cx
\seq_if_in:cvTF
\vbox_set_to_ht:Nnw
\fparray_item_to_tl:Nn
\cs_set_nopar:cpn
\seq_pop_item:NnNT
\msg_term:nnx
\seq_put_right:cn
\tl_tail:n
\cs_gset_nopar:Npx
\msg_info:nnnn
\exp_args:Ne
\cs_show:N
\l_peek_token
\box_if_empty:NF
\coffin_attach:NnnNnnnn
\seq_remove_duplicates:N
\seq_map_variable:Ncn
\sys_if_engine_pdftex:F
\coffin_grotate:Nn
\dim_until_do:nNnn
\clist_map_inline:cn
\peek_charcode:NF
\box_if_exist:NT
\box_autosize_to_wd_and_ht:cnn
\dim_show:n
\seq_gput_right:cV
\tl_if_eq_p:NN
\clist_clear_new:N
\box_if_vertical_p:N
\iow_now:Nx
\fparray_gset:Nnn
\color_fill:nn
\cs_new:Nx
\box_if_horizontal_p:c
\peek_regex_remove_once:nTF
\text_titlecase_first:nn
\coffin_mark_handle:cnnn
\tl_if_eq:NNT
\clist_gput_right:cV
\c_group_end_token
\prop_gremove:NV
\seq_gpop_right:NNF
\ior_str_get:NNF
\seq_log:N
\int_const:cn
\clist_gpush:No
\clist_gpush:cV
\regex_replace_all:nnN
\l_file_search_path_seq
\seq_gset_item:cnnT
\token_if_font_selection:NF
\prop_if_in:coF
\seq_gpop_right:NNT
\color_math:nn
\peek_regex_replace_once:nn
\seq_get:cN
\peek_regex_replace_once:nnTF
\token_if_long_macro:NTF
\c_sys_minute_int
\prop_if_in_p:NV
\intarray_count:N
\coffin_show:N
\seq_count:c
\file_get_timestamp:nNT
\prop_if_in:NnF
\prop_gput:Noo
\clist_push:cV
\exp_args:Ncx
\dim_gset:cn
\cs_gset_protected_nopar:cpx
\tl_clear_new:c
\seq_gpop_left:NN
\cs_if_eq_p:NN
\tl_rescan:nn
\muskip_const:cn
\clist_if_in:nVT
\cs_if_free:NT
\tl_const:cx
\clist_put_right:cx
\tl_build_put_right:Nx
\token_if_other_p:N
\tl_gset:cx
\token_if_mathchardef:NF
\skip_if_exist:NF
\int_set_eq:cN
\seq_if_empty_p:c
\clist_gset:co
\iow_indent:n
\prop_gput_from_keyval:Nn
\l_tmpa_bool
\tl_if_in:onT
\text_lowercase:nn
\prop_if_in:cVT
\msg_none:nnnnn
\prop_if_empty:cF
\str_case_e:nnF
\box_new:N
\regex_extract_once:nnNT
\tl_set_eq:cN
\prop_clear_new:c
\prop_pop:NnNF
\fp_to_tl:n
\msg_fatal:nnxxx
\seq_pop:cNT
\tl_if_eq:cnF
\fp_to_decimal:c
\peek_regex:nT
\hbox_gset:cn
\str_case_e:nn
\exp_args:Nnno
\if_meaning:w
\flag_show:n
\msg_fatal:nnnn
\seq_push:No
\seq_gremove_all:Nn
\pdf_destination:nn
\GetIdInfo
\g_tmpb_box
\seq_shuffle:N
\sys_if_shell:T
\str_gremove_once:cn
\str_case:onF
\prop_put:Nnx
\str_map_tokens:nn
\exp_args:NNNx
\dim_do_while:nn
\seq_gset_split_keep_spaces:NnV
\keys_set_filter:nnnnN
\seq_gpop_left:cNF
\fp_to_decimal:N
\char_set_catcode_invalid:n
\quark_if_recursion_tail_break:nN
\int_if_odd:nT
\str_if_empty:cTF
\file_get_full_name:nNF
\msg_critical_text:n
\regex_replace_once:NnNF
\muskip_if_exist_p:c
\intarray_item:Nn
\box_set_eq_drop:Nc
\hbox_set:Nn
\bool_while_do:nn
\pdf_version_minor:
\str_compare:eNeT
\prop_if_in:NoTF
\file_if_exist:nF
\str_compare:nNnTF
\dim_eval:n
\clist_map_tokens:cn
\cctab_gset:cn
\seq_map_indexed_inline:Nn
\int_gzero_new:N
\exp_args:Nne
\token_if_parameter_p:N
\prop_get:NoNF
\tl_if_exist_p:N
\tl_gsort:Nn
\token_if_muskip_register:NTF
\exp_args:Nnf
\prop_rand_key_value:c
\exp_args:Ncco
\tl_gset:Nf
\cctab_if_exist:cF
\seq_gput_right:No
\file_get_timestamp:nN
\str_if_eq:VVT
\tl_set_eq:Nc
\box_if_horizontal:cT
\keys_set_known:nVnN
\muskip_gadd:Nn
\keys_if_exist:neT
\token_if_eq_charcode:NNF
\tl_gclear:N
\use_none:n
\prop_get:NVNF
\cs_if_exist:cTF
\clist_if_in:cVTF
\str_put_right:cx
\str_item:Nn
\sys_shell_now:x
\bool_not_p:n
\str_log:c
\mode_if_inner:T
\prop_clear:N
\int_zero_new:N
\c_minus_zero_fp
\clist_show:N
\fp_zero_new:c
\box_log:cnn
\dim_if_exist:NT
\ior_str_map_inline:Nn
\sys_if_output_dvi:TF
\quark_if_no_value:nT
\tl_head:w
\str_if_eq_p:cN
\tl_if_in:noF
\exp_args:NNVV
\int_compare_p:n
\prop_remove:cV
\l_text_expand_exclude_tl
\clist_clear_new:c
\prop_map_function:cN
\clist_push:cx
\c_one_int
\seq_gshuffle:c
\seq_if_in:cnF
\box_log:N
\use_none:nn
\fp_to_dim:n
\seq_set_filter:NNn
\box_grotate:cn
\quark_if_no_value_p:c
\msg_info:nnxx
\clist_put_left:co
\dim_to_decimal_in_bp:n
\dim_sign:n
\keys_if_exist_p:ne
\str_if_eq_p:VV
\seq_if_in:NoTF
\seq_gpop_right:cN
\exp_args:NV
\cs_set_nopar:Npx
\coffin_join:NnnNnnnn
\c_document_cctab
\coffin_rotate:cn
\int_gset:Nn
\pdf_object_if_exist:nF
\fp_step_function:nnnN
\c_underscore_str
\box_gresize_to_wd_and_ht_plus_dp:cnn
\tl_put_right:cx
\text_expand:n
\bool_lazy_all:nF
\l_tmpb_regex
\tl_count:n
\exp_args:NNf
\keys_log:nn
\str_case:nnTF
\clist_gset_eq:cc
\cs_set_eq:cc
\text_declare_case_equivalent:cn
\dim_max:nn
\legacy_if_gset_false:n
\str_if_in:NnF
\exp:w
\tl_if_blank_p:V
\file_get_hex_dump:nnnNF
\clist_remove_all:cn
\str_if_eq:cNT
\clist_set_eq:Nc
\bool_set_eq:cN
\if:w
\use_none:nnnnnnn
\l_tmpa_regex
\iow_term:x
\c_sys_hour_int
\str_if_eq:cNF
\seq_remove_all:Nn
\exp_args_generate:n
\prop_count:N
\group_log_list:
\if_cs_exist:N
\int_if_exist:cT
\int_if_odd:nF
\str_case:VnTF
\seq_set_split_keep_spaces:NnV
\exp_end:
\str_if_in:NnT
\dim_gadd:Nn
\exp_args:Nno
\box_gset_eq:NN
\str_put_left:cV
\bool_case_true:nF
\prop_if_empty:NT
\bool_lazy_any:nF
\muskip_set_eq:Nc
\c_percent_str
\msg_gset:nnnn
\file_get_full_name:nNT
\clist_count:n
\color_group_begin:
\regex_extract_all:NnNTF
\seq_pop_left:NNTF
\coffin_log_structure:c
\tl_put_right:NV
\fp_to_tl:c
\str_if_empty:cF
\tl_if_in:noT
\c_empty_seq
\char_str_foldcase:N
\char_set_catcode_escape:n
\regex_extract_all:nnN
\bool_set:Nn
\box_show:Nnn
\token_if_macro_p:N
\dim_min:nn
\file_parse_full_name:n
\hbox_set:cw
\tl_trim_spaces_apply:oN
\str_gset_eq:cN
\seq_get_right:NN
\hcoffin_gset:cw
\int_while_do:nn
\lua_load_module:n
\tl_if_single_p:N
\int_set:Nn
\tl_build_gput_right:Nn
\bool_case_false:nT
\clist_if_empty:nF
\clist_gset:NV
\str_if_eq:vnF
\l_text_letterlike_tl
\tl_if_eq:NcT
\skip_gsub:cn
\muskip_if_exist:NTF
\vbox_gset_top:Nn
\sys_if_shell_restricted_p:
\msg_critical:nnnnn
\color_set:nnn
\text_titlecase:n
\peek_regex_replace_once:nnF
\clist_sort:Nn
\token_if_primitive:NTF
\file_get:nnNTF
\sys_get_shell:nnNF
\coffin_attach:cnncnnnn
\cs_set:Nx
\seq_set_map_x:NNn
\box_if_vertical:cT
\vbox_unpack:N
\pdf_object_unnamed_write:nn
\muskip_show:c
\prop_gpop:NnNTF
\color_profile_apply:nn
\token_if_group_begin_p:N
\ior_str_get:NNTF
\tl_set_rescan:cnx
\peek_regex_replace_once:NnF
\tl_to_str:c
\char_set_active_eq:Nc
\prop_put:Noo
\str_if_in:nnTF
\dim_set_eq:cN
\use:e
\tl_if_head_eq_charcode:nNTF
\tl_gremove_once:cn
\regex_gset:Nn
\int_compare:nNnT
\clist_if_in:cVT
\cs_gset_protected:cn
\str_if_eq:VnT
\fp_set_eq:cc
\msg_none:nnx
\seq_if_in:cvT
\color_if_exist:nF
\msg_error:nnxxxx
\seq_gset_item:NnnF
\if_int_compare:w
\regex_replace_all:NnNF
\tl_const:Nx
\tl_if_single_token:nF
\token_if_toks_register:NTF
\exp_last_unbraced:NNV
\exp_args:NNno
\muskip_gadd:cn
\clist_set_eq:NN
\tl_if_exist:cT
\cctab_const:cn
\fp_to_dim:N
\int_do_until:nNnn
\seq_get_left:cNF
\seq_gset_split:NnV
\box_new:c
\bool_lazy_or:nnTF
\if_vbox:N
\box_if_horizontal:NTF
\hcoffin_gset:Nw
\str_set:Nx
\clist_put_left:Nx
\seq_count:N
\coffin_wd:c
\skip_set_eq:cc
\sys_if_platform_windows:T
\tl_show:N
\char_show_value_mathcode:n
\prop_gremove:Nn
\muskip_gset:Nn
\seq_gset_eq:Nc
\int_set_eq:NN
\clist_get:NNT
\str_if_exist_p:N
\muskip_zero:c
\str_convert_pdfname:n
\fp_compare_p:nNn
\prop_gset_eq:NN
\msg_note:nnnn
\tl_if_single:nT
\int_use:N
\str_if_exist:cT
\color_export:nnnN
\str_gput_left:Nn
\str_gput_left:cx
\seq_set_item:Nnn
\tl_build_gput_left:Nn
\box_if_vertical:NTF
\iow_now:cn
\prop_remove:Nn
\dim_if_exist:cT
\dim_case:nnTF
\peek_regex:NT
\vbox_set_to_ht:Nnn
\token_if_cs_p:N
\pdf_pageobject_ref:n
\int_step_function:nnN
\peek_catcode_remove:NTF
\seq_pop_item:cnN
\cs_new_protected_nopar:cx
\regex_match:nnTF
\g_msg_module_name_prop
\cs_new_protected:Npx
\use_i:nn
\peek_charcode_collect_inline:Nn
\cs_set_nopar:cpx
\clist_get:cNT
\keyval_parse:nnn
\str_gset:Nn
\cs:w
\fp_if_exist_p:N
\vcoffin_set:cnn
\fp_gadd:Nn
\str_gremove_once:Nn
\msg_expandable_error:nn
\dim_compare:nNnTF
\str_show:n
\bool_if:NTF
\fp_to_scientific:c
\seq_put_left:cx
\coffin_typeset:cnnnn
\regex_replace_case_once:nNT
\seq_set_item:cnnT
\str_count:c
\tl_if_in:onF
\skip_horizontal:c
\iow_open:cn
\clist_gconcat:NNN
\c_e_fp
\fp_do_while:nn
\cs_if_exist:cT
\keys_set_known:nvN
\cs_new_protected:cn
\box_clear:c
\str_concat:NNN
\tl_if_eq:NcTF
\prop_gpop:cnNT
\cs_set:cx
\clist_use:nnnn
\prop_get:cVNT
\use:nn
\prop_gput:cxx
\bool_to_str:n
\coffin_log:cnn
\exp_args:NNoo
\c_sys_month_int
\seq_sort:cn
\clist_gset_from_seq:cN
\tl_concat:NNN
\seq_if_in:coT
\clist_gpush:Nn
\seq_gset_item:Nnn
\ior_close:N
\msg_warning:nnxx
\tl_set:Nn
\exp_last_unbraced:No
\str_range_ignore_spaces:nnn
\file_parse_full_name:nNNN
\coffin_attach:Nnncnnnn
\lua_escape:e
\sys_if_output_pdf:F
\char_set_catcode_ignore:N
\seq_gclear_new:N
\token_if_active_p:N
\token_if_eq_meaning:NNTF
\seq_set_eq:NN
\fp_set_eq:Nc
\seq_gpop_right:NNTF
\prop_if_exist:cT
\vbox_set_end:
\clist_if_in:NVT
\clist_gpop:cNT
\dim_set_eq:Nc
\seq_map_variable:NNn
\prop_if_in:NVTF
\fp_zero:N
\hbox_unpack:N
\keys_if_exist:neTF
\token_if_toks_register:NT
\str_if_eq:vnT
\vbox_set_to_ht:cnw
\clist_gput_left:cV
\box_if_vertical:NT
\prop_if_in_p:Nn
\dim_zero_new:N
\exp_args:Nnff
\tl_if_eq:NNTF
\hbox_set_to_wd:Nnw
\fparray_item:Nn
\msg_log_eval:Nn
\vbox_unpack_drop:N
\c_zero_str
\dim_compare:nTF
\keys_if_choice_exist_p:nnn
\seq_map_variable:ccn
\seq_show:N
\cs_gset_nopar:Nx
\mode_if_inner:F
\prop_if_in:cnTF
\tl_if_blank:VTF
\seq_if_in:coF
\cs_set_eq:cN
\exp_args:Noo
\l_keys_path_str
\bool_lazy_and:nnF
\seq_pop_left:cNT
\muskip_set_eq:NN
\str_gput_right:cx
\vbox_gset_to_ht:cnw
\cctab_if_exist_p:c
\sys_if_engine_xetex:T
\seq_push:Nv
\seq_push:co
\exp_not:o
\use_iii:nnn
\tl_build_gput_left:Nx
\keys_set_filter:nnoN
\box_move_right:nn
\keys_set_groups:nnV
\dim_do_until:nn
\tl_if_single_p:c
\clist_concat:NNN
\prg_break:
\file_get_mdfive_hash:nNTF
\prop_show:c
\str_remove_once:Nn
\use_i:nnn
\tl_if_blank:VT
\seq_set_item:NnnT
\str_if_eq:nnTF
\seq_gpop_left:cNT
\iow_show_list:
\hbox_gset_to_wd:cnw
\box_gautosize_to_wd_and_ht:Nnn
\regex_match_case:nnTF
\seq_gclear:c
\token_if_group_end:NTF
\tl_if_single:NF
\ior_get_term:nN
\lua_shipout:n
\keys_set_filter:nnVnN
\regex_extract_once:NnNT
\int_compare:nT
\clist_gput_left:Nx
\box_gclear_new:N
\mode_leave_vertical:
\token_if_int_register:NT
\dim_set:Nn
\box_use_drop:c
\prop_put_from_keyval:Nn
\prop_map_function:NN
\seq_put_right:NV
\msg_show_item:nn
\box_if_exist_p:N
\color_select:n
\seq_pop_left:NNT
\coffin_set_eq:Nc
\file_show_list:
\exp_end_continue_f:nw
\pdf_object_write:nnn
\int_step_variable:nNn
\g_file_curr_ext_str
\box_gautosize_to_wd_and_ht_plus_dp:cnn
\q_stop
\scan_new:N
\seq_get_right:NNTF
\quark_if_nil:nF
\coffin_if_exist:cF
\tl_replace_all:cnn
\token_if_chardef_p:N
\token_if_math_subscript:NT
\mode_if_math_p:
\use_iii:nnnn
\box_if_vertical:NF
\cs_set_nopar:cn
\skip_zero:c
\prop_if_in:NVF
\bool_set_eq:Nc
\seq_gpush:Nn
\exp_last_unbraced:Nf
\fp_gzero:c
\use_ii:nn
\regex_match_case:nn
\c_true_bool
\clist_gset:Nx
\tl_tail:v
\box_set_eq_drop:NN
\dim_show:N
\cs_set_protected_nopar:Npx
\bool_lazy_any:nT
\seq_set_item:cnnF
\sys_if_engine_ptex:TF
\char_show_value_sfcode:n
\clist_gpop:NNT
\coffin_show_structure:N
\clist_gset_eq:cN
\token_case_catcode:NnF
\sys_get_shell:nnNT
\str_if_eq:noF
\prop_get:cVN
\sys_load_debug:
\seq_if_in:NvTF
\vbox_set_split_to_ht:NNn
\coffin_ht:c
\box_gclear:N
\seq_gconcat:NNN
\bool_case_false:nTF
\tl_analysis_log:n
\exp_args:Nnx
\exp_not:e
\cs_if_free:cT
\pdf_object_write:nnx
\tl_remove_all:cn
\tl_put_left:No
\prop_get:cnNF
\bool_if_exist:NT
\skip_if_exist:cTF
\peek_regex:nF
\tl_if_exist:NTF
\tl_gset:co
\tl_map_inline:nn
\int_rand:n
\str_gset_convert:NnnnTF
\prop_if_in_p:cn
\prop_gpop:cnNTF
\box_if_empty_p:c
\box_move_down:nn
\seq_gput_right:Nv
\tl_if_in:cnF
\muskip_sub:cn
\msg_if_exist:nnT
\token_if_int_register:NTF
\skip_gset_eq:NN
\tl_trim_spaces:N
\int_add:cn
\seq_if_exist:cT
\cs_gset_protected_nopar:cx
\tl_if_blank_p:n
\box_gclear_new:c
\msg_expandable_error:nnff
\mode_if_math:TF
\tl_if_in:VnF
\msg_term:nnnn
\tl_if_head_is_space:nT
\clist_if_in:NVF
\hcoffin_set_end:
\regex_extract_once:NnNF
\seq_put_left:cV
\regex_match_case:nnF
\tl_analysis_map_inline:nn
\tl_rand_item:n
\seq_set_from_clist:cn
\cs_set_eq:NN
\token_if_eq_catcode:NNF
\msg_none:nnxxxx
\g_file_curr_dir_str
\tl_analysis_show:N
\clist_put_left:Nn
\msg_note:nnxx
\coffin_join:cnnNnnnn
\skip_gadd:Nn
\g_tmpa_regex
\str_case_e:nnTF
\coffin_join:Nnncnnnn
\dim_sub:cn
\tl_if_in:NnT
\seq_gpop_item:cnNT
\keys_set_filter:nnvN
\dim_log:c
\tl_if_head_eq_catcode:nNF
\ior_if_eof:NF
\box_set_eq:cN
\seq_set_eq:cN
\tl_build_gclear:N
\cs_new_protected_nopar:Nx
\fp_to_decimal:n
\prg_return_false:
\tl_gput_left:Nx
\file_get_full_name:nNTF
\iow_new:c
\sys_if_engine_pdftex:T
\group_align_safe_end:
\mode_if_math:T
\scan_stop:
\quark_if_nil:NTF
\tl_build_gbegin:N
\clist_map_break:n
\msg_error:nnn
\prop_if_in:NnTF
\exp_last_unbraced:NNNf
\intarray_gzero:c
\keys_set_filter:nnnN
\seq_get:cNF
\cs_new_protected_nopar:cpx
\clist_if_exist_p:N
\msg_term:nnxx
\fp_gset_eq:NN
\regex_replace_case_once:nNF
\if_charcode:w
\clist_if_empty:NTF
\peek_regex_remove_once:NF
\skip_const:Nn
\cs_new_nopar:Nx
\flag_if_exist:nTF
\regex_extract_once:NnN
\str_gremove_all:Nn
\str_case:Nn
\coffin_grotate:cn
\hcoffin_set:cw
\int_case:nnF
\keys_set_known:nnnN
\seq_pop:NNT
\char_set_mathcode:nn
\cs_new_nopar:cpn
\c_max_register_int
\clist_gput_right:cx
\peek_meaning:NT
\vbox:n
\tl_if_blank_p:o
\cs_new_protected:cpn
\fp_step_variable:nnnNn
\int_set:cn
\tl_clear_new:N
\msg_none:nn
\cs_set_nopar:Nx
\c_backslash_str
\msg_new:nnn
\if_bool:N
\intarray_gzero:N
\token_to_meaning:c
\c_alignment_token
\fp_while_do:nNnn
\str_case:nVTF
\clist_map_function:nN
\coffin_set_eq:cc
\c_max_int
\str_set_eq:cN
\peek_meaning:NF
\regex_replace_case_all:nNF
\box_if_empty:cF
\box_set_dp:Nn
\legacy_if:nTF
\seq_if_in:coTF
\tl_build_clear:N
\sys_rand_seed:
\pdf_object_ref:n
\str_greplace_once:Nnn
\if_false:
\clist_map_inline:Nn
\tl_reverse:N
\fp_if_exist:cTF
\bool_set:cn
\file_get_mdfive_hash:nNF
\str_greplace_all:Nnn
\box_set_eq:cc
\g_tmpa_muskip
\if_true:
\bool_if_exist:cTF
\pdf_object_if_exist:nTF
\str_if_eq_p:vn
\cs_gset:cpn
\color_group_end:
\tl_if_head_is_N_type:nF
\char_gset_active_eq:Nc
\clist_gpop:cNTF
\seq_if_exist:cTF
\muskip_gset_eq:cN
\prop_put:cno
\peek_charcode_remove:NTF
\tl_if_head_is_N_type:nTF
\msg_log:nnxx
\clist_gpop:NNF
\str_compare:eNeTF
\char_set_catcode_group_begin:n
\tl_if_in:noTF
\seq_push:cn
\vbox_gset_to_ht:Nnw
\skip_gset_eq:cN
\exp_args:Neee
\seq_get_left:NN
\quark_if_nil:oTF
\tl_if_single:NTF
\token_if_protected_macro:NTF
\mode_if_vertical:TF
\clist_gput_left:NV
\box_gset_eq:Nc
\exp_args:Nf
\mode_if_horizontal:F
\tl_map_tokens:cn
\regex_extract_all:NnNF
\prop_if_in_p:No
\coffin_gclear:N
\pdf_version_compare:NnF
\fp_gzero:N
\vbox_unpack:c
\sys_if_rand_exist:TF
\str_if_empty:cT
\c_pi_fp
\coffin_gjoin:cnnNnnnn
\tl_put_right:cV
\c_initex_cctab
\fp_while_do:nn
\clist_gremove_duplicates:c
\dim_add:cn
\exp_not:c
\tl_if_head_eq_charcode:fNF
\tl_if_eq:cnT
\prop_gpop:NoN
\token_case_meaning:NnF
\tl_if_empty:nT
\str_replace_once:Nnn
\int_if_even:nT
\lua_shipout_e:n
\tl_set:cf
\coffin_scale:Nnn
\tl_if_head_is_space:nF
\flag_clear_new:n
\tl_put_left:NV
\token_if_int_register:NF
\coffin_gscale:Nnn
\prg_new_conditional:Nnn
\keys_set_known:nvnN
\file_input:n
\exp_last_unbraced:NNNo
\box_if_horizontal:NT
\box_set_viewport:cnnnn
\str_map_inline:nn
\file_get_hex_dump:nnnN
\dim_new:N
\str_if_in:cnF
\sys_if_output_dvi:T
\fp_step_inline:nnnn
\token_case_charcode:Nn
\cs_gset_eq:cN
\int_to_symbols:nnn
\file_get_size:nNTF
\use:c
\use_ii:nnnn
\tl_if_blank:oT
\skip_set:cn
\clist_push:co
\file_if_exist:nT
\tl_if_blank:eF
\sys_if_shell_restricted:T
\fp_to_dim:c
\str_gset:Nx
\g_tmpa_fp
\iow_allow_break:
\int_from_hex:n
\seq_gpop:cNF
\c_group_begin_token
\str_gput_left:cn
\mode_if_vertical_p:
\seq_clear:N
\prop_if_empty:cT
\prop_gpop:NnNT
\token_if_muskip_register_p:N
\fp_until_do:nn
\fp_gset_eq:cN
\ior_if_eof:NT
\char_set_catcode_letter:N
\tl_if_head_eq_charcode:nNF
\char_set_catcode_comment:n
\token_if_protected_macro:NF
\iow_show:c
\tl_case:cnF
\fp_compare:nNnT
\dim_step_variable:nnnNn
\int_gadd:Nn
\prop_gput:coo
\msg_error:nn
\regex_split:nnNT
\clist_gset:Nn
\sys_if_platform_windows:TF
\seq_get_right:cN
\c_other_cctab
\keyval_parse:NNn
\char_generate:nn
\fp_gset_eq:Nc
\dim_step_inline:nnnn
\token_if_expandable:NT
\tl_gset_eq:cc
\debug_suspend:
\peek_regex_replace_once:Nn
\bool_do_while:nn
\box_if_vertical:cTF
\token_if_alignment:NT
\sys_if_shell_unrestricted_p:
\bool_gset_eq:Nc
\box_move_up:nn
\token_if_math_toggle_p:N
\prop_clear:c
\tl_if_empty:NF
\g_tmpa_dim
\sys_get_shell:nnN
\clist_if_empty:cF
\tl_build_put_left:Nn
\char_set_active_eq:nN
\sys_finalise:
\regex_split:NnN
\clist_pop:NNF
\tl_put_right:No
\msg_info:nnxxxx
\msg_log:nnxxxx
\ior_open:cn
\peek_N_type:F
\pdf_object_if_exist_p:n
\tl_if_eq_p:cc
\cs_undefine:c
\exp_not:V
\seq_if_in:NVF
\token_if_math_subscript:NTF
\str_if_eq_p:Nc
\muskip_new:c
\str_greplace_once:cnn
\sys_if_platform_windows_p:
\str_if_empty:NTF
\bool_do_until:cn
\seq_gset_split_keep_spaces:Nnn
\prg_new_protected_conditional:Nnn
\seq_gpop_item:cnNF
\str_count_ignore_spaces:n
\fp_compare_p:n
\g_tmpa_iow
\sys_if_shell_restricted:TF
\str_gset:cx
\dim_set:cn
\coffin_show:Nnn
\clist_log:N
\use_ii_i:nn
\coffin_if_exist:cTF
\str_if_empty:NT
\prop_get:cnNT
\prop_put:NnV
\token_if_group_end:NT
\tl_if_head_eq_catcode:nNT
\cs_gset:cx
\box_dp:N
\token_if_dim_register:NF
\coffin_rotate:Nn
\clist_if_empty_p:c
\char_set_active_eq:nc
\peek_after:Nw
\intarray_item:cn
\str_set:cx
\seq_remove_all:cn
\cs_gset_eq:cc
\tl_case:NnT
\l_tmpa_seq
\token_if_group_end_p:N
\cs_if_free_p:c
\str_tail:n
\cs_set:cpn
\sys_if_engine_ptex:F
\dim_do_until:nNnn
\skip_eval:n
\str_if_eq_p:cc
\int_to_Alph:n
\tl_item:nn
\bool_lazy_all:nTF
\msg_note:nnn
\seq_mapthread_function:NNN
\iow_shipout:cn
\skip_zero_new:N
\seq_set_from_clist:Nc
\box_gset_eq:cc
\tl_if_eq:NcF
\seq_push:NV
\regex_const:Nn
\file_input_stop:
\int_value:w
\prop_map_break:n
\int_add:Nn
\legacy_if_set_true:n
\bool_gset:cn
\tl_head:N
\g_peek_token
\coffin_wd:N
\clist_gsort:Nn
\dim_compare:nNnT
\hbox_set_to_wd:cnw
\tl_case:cnTF
\char_set_catcode_parameter:n
\clist_gpop:NN
\msg_fatal:nnn
\box_show:cnn
\tl_if_head_eq_catcode:nNTF
\str_if_empty:NF
\seq_if_exist_p:c
\msg_show_item_unbraced:n
\peek_regex_replace_once:nnT
\prop_put:Nvx
\coffin_if_exist:NF
\msg_error:nnxx
\seq_gpop_item:NnNTF
\flag_if_raised:nTF
\ior_open:NnT
\c_hash_str
\token_if_primitive:NF
\c_max_dim
\str_if_eq:VnTF
\seq_gput_left:Nn
\int_sub:cn
\str_remove_all:Nn
\str_put_left:cx
\str_if_in:cnT
\cs_set_protected:Nn
\box_if_horizontal_p:N
\tl_if_exist:cF
\seq_if_in:NxF
\keys_if_choice_exist:nnnT
\int_abs:n
\ior_get:NNTF
\tl_reverse:n
\token_if_math_toggle:NTF
\clist_map_variable:nNn
\fp_sub:cn
\intarray_rand_item:c
\prop_get:NoNT
\str_map_function:NN
\char_set_catcode_space:N
\dim_gsub:cn
\bool_gset_inverse:N
\hbox_gset:Nn
\prop_get:NoN
\seq_pop_item:cnNT
\lua_escape:n
\fp_set:Nn
\msg_fatal_text:n
\iow_shipout:Nx
\seq_set_eq:cc
\l_tmpa_muskip
\bool_gset_true:N
\int_step_variable:nnNn
\seq_if_in:NnTF
\c_sys_year_int
\tl_if_in:cnTF
\coffin_new:c
\seq_gclear_new:c
\iow_log:N
\str_set_convert:NnnnTF
\clist_set:NV
\seq_gpop_item:NnN
\msg_set:nnnn
\bool_if:cT
\cs_set_protected_nopar:cn
\str_head:n
\dim_case:nnF
\str_map_inline:cn
\msg_log:nnnn
\seq_map_indexed_function:NN
\str_if_empty_p:N
\fp_do_while:nNnn
\clist_set:co
\coffin_display_handles:cn
\bool_set_eq:cc
\intarray_show:c
\muskip_log:c
\seq_get_left:NNT
\clist_map_variable:cNn
\tl_map_break:n
\tl_if_blank:VF
\str_set_eq:cc
\sys_if_engine_uptex:F
\cctab_if_exist:NF
\keys_show:nn
\quark_if_no_value:cF
\char_set_catcode_end_line:n
\msg_expandable_error:nnnnn
\clist_get:cNTF
\exp_args:NcVV
\tl_set:No
\clist_item:cn
\exp_last_unbraced:Nfo
\clist_map_break:
\dim_while_do:nn
\str_set:cn
\g_tmpa_bool
\coffin_gattach:Nnncnnnn
\fp_do_until:nNnn
\sys_if_platform_windows:F
\file_hex_dump:n
\l_tmpa_clist
\ExplSyntaxOn
\str_if_eq:noT
\clist_if_empty:cTF
\g_tmpb_coffin
\fp_add:Nn
\use_none:nnnnn
\box_move_left:nn
\seq_gshuffle:N
\hcoffin_set:cn
\keys_set_groups:nno
\text_declare_expand_equivalent:Nn
\str_count_spaces:N
\file_get_timestamp:nNTF
\seq_push:cV
\str_put_right:cV
\skip_gset:Nn
\dim_compare:nT
\bool_lazy_any_p:n
\exp_args:Nnnc
\seq_if_in:NnF
\peek_charcode:NTF
\token_if_primitive:NT
\skip_if_eq:nnTF
\int_while_do:nNnn
\text_declare_purify_equivalent:Nx
\ior_get:NNT
\seq_if_in:cxF
\tl_set_rescan:Nno
\str_map_function:nN
\coffin_gscale:cnn
\keys_set_filter:nnV
\sys_shell_now:n
\msg_if_exist:nnF
\tl_range_braced:nnn
\box_gset_dp:Nn
\clist_gclear_new:N
\str_case:nvT
\prop_if_in:cnT
\color_stroke:n
\str_if_eq:onTF
\c_one_fp
\tl_if_in:onTF
\tl_map_tokens:nn
\prop_if_in:coTF
\regex_replace_once:NnN
\token_if_letter_p:N
\cs_set_protected:Npx
\int_if_even:nF
\tl_if_single_p:n
\box_set_eq_drop:cN
\clist_remove_all:Nn
\seq_if_empty:cT
\intarray_log:N
\str_replace_once:cnn
\tl_gset_rescan:Nnx
\sys_if_shell:F
\quark_if_nil_p:N
\iow_shipout:cx
\prop_gpop:NnN
\tl_map_function:nN
\seq_map_inline:cn
\use_i_ii:nnn
\prop_put:cVn
\ior_open:NnTF
\prop_put:cnn
\if_predicate:w
\clist_put_right:No
\exp_args:NnV
\clist_put_right:Nx
\seq_mapthread_function:NcN
\bool_while_do:cn
\tl_if_head_is_N_type:nT
\tl_gset:Nx
\l_text_titlecase_check_letter_bool
\msg_show_eval:Nn
\token_if_cs:NTF
\l_tmpb_box
\tl_if_eq:NnT
\exp_not:f
\bool_log:N
\regex_split:NnNT
\char_set_catcode_other:N
\tl_if_in:NnTF
\tl_analysis_show:n
\prg_set_eq_conditional:NNn
\msg_note:nnxxxx
\seq_set_item:NnnF
\seq_sort:Nn
\l_keys_choice_int
\muskip_show:N
\box_grotate:Nn
\c_colon_str
\prop_new:N
\prop_if_exist:NTF
\clist_pop:cNT
\hcoffin_gset:Nn
\clist_if_in:NnTF
\int_gset_eq:Nc
\seq_item:cn
\l_keys_value_tl
\clist_const:cx
\seq_gpop_item:NnNF
\int_from_base:nn
\regex_extract_all:nnNF
\bool_gset_true:c
\c_empty_tl
\seq_gput_right:Nn
\tl_set_rescan:cnn
\seq_gpop_left:cNTF
\regex_replace_once:NnNT
\prop_pop:NnNT
\prop_get:NnN
\exp_args:NNc
\fp_if_exist:NTF
\vbox_gset_to_ht:cnn
\c_sys_engine_exec_str
\seq_gput_right:cn
\tl_if_head_eq_catcode:oNTF
\seq_put_left:cn
\seq_pop_right:cN
\tl_greverse:N
\fp_compare:nNnTF
\str_if_eq_p:on
\exp_args:Nccc
\seq_gclear:N
\seq_gpop_right:cNT
\legacy_if_set:nn
\l_color_fixed_model_tl
\tl_head:V
\str_case:nV
\clist_gremove_all:NV
\token_if_muskip_register:NT
\exp_args:Noox
\bool_xor_p:nn
\box_gclip:c
\seq_gpop_item:cnNTF
\cs_set:cpx
\tl_gset_eq:NN
\clist_gput_left:co
\int_decr:N
\prg_break_point:
\fp_add:cn
\muskip_if_exist:cTF
\tl_remove_once:cn
\box_wd:c
\hbox_gset_to_wd:Nnn
\msg_term:nn
\str_show:N
\ior_show:N
\exp_args:Ncnx
\g_tmpb_clist
\seq_put_left:Nn
\quark_if_no_value:cT
\bool_lazy_and:nnT
\seq_if_in:NvF
\clist_if_in:nVTF
\tl_trim_spaces_apply:nN
\dim_do_while:nNnn
\tl_build_put_left:Nx
\cctab_if_exist:NT
\token_if_dim_register_p:N
\bool_set_false:N
\clist_map_tokens:nn
\str_gput_right:cV
\prop_if_exist_p:N
\seq_put_right:Nx
\fp_until_do:nNnn
\vbox_to_ht:nn
\skip_if_finite:nTF
\cs_set:Nn
\prop_if_in:coT
\msg_warning:nnnn
\exp_args:Noc
\prop_gput:cno
\seq_if_in:cVF
\sys_if_output_pdf_p:
\prg_do_nothing:
\tl_map_variable:NNn
\token_if_group_begin:NF
\dim_use:c
\prop_gput:cvx
\str_count_spaces:n
\msg_info:nnnnnn
\tl_put_left:cV
\seq_get_left:NNF
\char_set_catcode_comment:N
\prg_set_protected_conditional:Nnn
\exp_args:Ncno
\str_if_eq:NNTF
\msg_critical:nnn
\msg_module_name:n
\tl_if_head_is_group:nTF
\peek_catcode:NF
\prop_if_in:cnF
\int_set_eq:cc
\c_inf_fp
\dim_compare:nF
\group_insert_after:N
\g_tmpb_muskip
\cctab_select:c
\msg_note:nnx
\cs_set_protected_nopar:Npn
\box_gset_eq_drop:NN
\msg_critical:nnx
\tl_tail:V
\clist_if_in:noF
\exp_args:NNNV
\tl_sort:Nn
\seq_gset_from_clist:cc
\str_set_convert:Nnnn
\clist_put_right:cV
\muskip_zero_new:N
\msg_term:nnxxxx
\prg_return_true:
\cs_set_protected:cpn
\token_if_alignment:NF
\tl_if_empty:cT
\msg_show:nnnn
\seq_const_from_clist:cn
\dim_gset_eq:cN
\coffin_set_eq:NN
\skip_add:cn
\ExplSyntaxOff
\prop_pop:cnNT
\skip_gzero_new:c
\token_if_space_p:N
\char_set_catcode_math_toggle:n
\int_gsub:Nn
\seq_gset_map:NNn
\tl_gset:Nv
\box_ht:N
\color_if_exist_p:n
\str_put_right:Nn
\seq_rand_item:N
\box_if_empty:NTF
\muskip_use:c
\char_set_catcode_group_end:N
\char_set_catcode_math_superscript:n
\legacy_if_gset_true:n
\l_tmpb_tl
\seq_gset_item:cnn
\seq_get_right:cNTF
\fp_compare:nNnF
\hbox_overlap_center:n
\text_map_inline:nn
\box_gset_eq:cN
\str_if_empty:nTF
\color_show:n
\prop_gput:Nno
\cs_prefix_spec:N
\msg_show:nnnnnn
\clist_reverse:N
\seq_if_empty:cF
\seq_put_right:co
\g_tmpb_prop
\g_tmpa_clist
\int_min:nn
\tl_if_single_token:nT
\if_mode_inner:
\exp_args:Nnc
\keys_set:nn
\quark_if_no_value:nF
\q_nil
\box_gset_trim:Nnnnn
\fp_gset_eq:cc
\l_tmpa_box
\flag_if_raised:nT
\coffin_gresize:Nnn
\str_gput_right:Nn
\exp_args:Nnv
\tl_if_eq:ccF
\str_gput_left:cV
\token_if_other:NF
\regex_match:NnT
\prop_if_exist:cF
\prop_concat:NNN
\tl_if_empty_p:V
\prop_get:NvNT
\str_const:Nn
\int_incr:N
\muskip_gsub:cn
\clist_set_from_seq:NN
\fparray_new:Nn
\exp_args:Ncf
\msg_error:nnxxx
\dim_gset_eq:Nc
\tl_use:c
\str_head:N
\pdf_object_new:n
\seq_put_left:Nx
\g_tmpa_seq
\exp_last_unbraced:Nx
\cs_new:Nn
\int_step_inline:nn
\iow_shipout_x:cn
\l_char_active_seq
\clist_new:N
\int_to_oct:n
\file_mdfive_hash:n
\prop_gput_from_keyval:cn
\seq_if_in:cnT
\token_if_font_selection_p:N
\clist_gconcat:ccc
\clist_get:NN
\tl_put_right:Nx
\file_get_size:nNT
\box_rotate:cn
\dim_show:c
\cs_new_protected:Nx
\vcoffin_gset:Nnw
\peek_regex_replace_once:NnTF
\seq_gset_filter:NNn
\seq_if_exist:NT
\vcoffin_set_end:
\keys_set:nV
\cctab_if_exist_p:N
\coffin_log_structure:N
\exp_args:Nv
\prop_put:Nxx
\sys_if_engine_xetex:F
\clist_show:c
\clist_new:c
\int_gincr:N
\iow_log:n
\seq_concat:NNN
\int_log:c
\bool_if:NT
\prop_gclear:c
\clist_put_right:cn
\prg_replicate:nn
\tl_if_eq:cNF
\tl_greplace_once:cnn
\clist_put_left:cn
\ior_log_list:
\char_to_nfd:N
\str_gset:cn
\coffin_if_exist_p:N
\seq_if_empty:cTF
\tl_use:N
\bool_if:NF
\exp_args:NNcf
\fp_zero:c
\seq_if_in:cnTF
\cs_gset:Npn
\box_resize_to_ht_plus_dp:Nn
\coffin_gattach:NnnNnnnn
\skip_log:N
\exp_args:Nfo
\cs_if_eq:NNF
\tl_gset:cf
\file_compare_timestamp:nNnT
\bool_xor:nnT
\regex_replace_case_once:nNTF
\char_show_value_catcode:n
\bool_while_do:Nn
\int_gzero:c
\tl_if_single_token:nTF
\cs_gset_protected:Npn
\seq_if_exist:cF
\muskip_set_eq:cc
\cs_if_free:cF
\clist_put_left:NV
\tl_show:c
\seq_pop_right:NNTF
\str_if_in:NnTF
\muskip_gzero:N
\tl_count:c
\c_sys_jobname_str
\tl_if_novalue_p:n
\token_if_mathchardef:NT
\cs_set:cn
\str_remove_once:cn
\prop_if_empty_p:c
\iow_char:N
\iow_shipout_x:Nx
\regex_extract_once:NnNTF
\quark_if_nil:nT
\sys_load_backend:n
\str_compare_p:nNn
\clist_gpop:cNF
\str_if_exist:cTF
\ior_str_get:NN
\exp_last_unbraced:Noo
\seq_gset_item:cnnTF
\fp_to_int:n
\clist_gset:cx
\color_select:nn
\hbox_set:cn
\prg_new_eq_conditional:NNn
\seq_greverse:c
\dim_abs:n
\token_if_math_toggle:NT
\tl_build_gput_right:Nx
\seq_gremove_all:cn
\tl_if_head_eq_charcode:nNT
\skip_zero_new:c
\prop_get:NVN
\box_gset_viewport:cnnnn
\box_ht_plus_dp:N
\prop_gset_eq:Nc
\seq_push:cv
\cs_new_protected:Nn
\tl_put_right:cn
\clist_gput_right:cn
\color_if_exist:nTF
\clist_map_tokens:Nn
\cs_gset_protected_nopar:Nn
\prop_get:cvN
\skip_gset_eq:Nc
\vbox_gset_end:
\cctab_begin:c
\clist_if_in:coTF
\c_catcode_other_space_tl
\keys_set_known:nv
\box_gset_ht:cn
\prop_if_empty:cTF
\coffin_mark_handle:Nnnn
\regex_extract_all:nnNTF
\if_catcode:w
\l_tmpb_prop
\box_gautosize_to_wd_and_ht:cnn
\box_gset_viewport:Nnnnn
\box_resize_to_wd:cn
\seq_put_right:No
\cs_if_free_p:N
\seq_new:N
\dim_gsub:Nn
\tl_if_head_eq_charcode_p:nN
\if_mode_horizontal:
\dim_set_eq:NN
\coffin_join:cnncnnnn
\muskip_gzero:c
\str_range:nnn
\seq_gset_split:Nnn
\file_parse_full_name:VNNN
\str_gconcat:NNN
\regex_log:n
\msg_warning:nn
\cs_new_protected:cpx
\str_map_tokens:Nn
\text_titlecase:nn
\msg_term:nnnnn
\tl_map_variable:cNn
\file_get_hex_dump:nnnNTF
\box_resize_to_ht_plus_dp:cn
\msg_critical:nnxxx
\prop_if_empty:NF
\tl_if_head_is_space:nTF
\c_catcode_active_space_tl
\str_gset_eq:Nc
\box_gresize_to_wd_and_ht:cnn
\clist_get:cNF
\cs_if_exist_use:NF
\prop_map_break:
\tl_gput_left:cV
\box_set_to_last:c
\seq_clear_new:c
\seq_pop:NNF
\vcoffin_gset:cnn
\c_sys_output_str
\msg_error_text:n
\int_to_base:nn
\bool_do_until:Nn
\msg_info_text:n
\pdf_version_compare_p:Nn
\fp_to_tl:N
\char_set_catcode:nn
\seq_shuffle:c
\sys_shell_shipout:n
\tl_rand_item:N
\ProvidesExplFile
\str_map_tokens:cn
\cs_set_protected_nopar:cpx
\int_div_truncate:nn
\box_set_ht:cn
\token_if_expandable:NF
\clist_pop:NN
\prop_set_eq:cc
\clist_remove_duplicates:c
\l_tmpb_fp
\sys_shell_shipout:x
\int_until_do:nNnn
\vbox_gset_to_ht:Nnn
\tl_if_exist:cTF
\intarray_count:c
\tl_gset_eq:cN
\tl_put_left:Nn
\seq_if_in:NoF
\clist_gset_from_seq:Nc
\seq_mapthread_function:ccN
\box_gset_to_last:c
\tl_gtrim_spaces:N
\tl_if_novalue:nTF
\prop_get:cvNF
\str_const:cV
\token_if_alignment_p:N
\exp_args:No
\fp_to_scientific:n
\fp_if_exist:cF
\skip_set:Nn
\skip_horizontal:n
\hbox_to_wd:nn
\file_parse_full_name_apply:nN
\sys_ensure_backend:
\hbox_unpack:c
\clist_push:NV
\tl_set:cv
\sys_if_output_dvi:F
\str_replace_all:Nnn
\bool_const:cn
\prop_clear_new:N
\fp_compare:nT
\box_if_empty:NT
\tl_gset:cv
\flag_height:n
\token_case_meaning:NnT
\token_if_expandable_p:N
\muskip_add:Nn
\clist_rand_item:c
\prop_get:NnNF
\sys_if_shell:TF
\str_map_variable:cNn
\c_empty_clist
\exp_last_unbraced:NNNV
\cs_new_eq:Nc
\msg_info:nnnnn
\prop_get:cvNTF
\quark_if_recursion_tail_stop_do:on
\fp_do_until:nn
\debug_resume:
\vbox_to_zero:n
\msg_none:nnxxx
\seq_put_right:cV
\iow_term:n
\tl_if_in:VnT
\seq_set_from_clist:cN
\clist_use:cn
\tl_if_head_eq_meaning:nNT
\char_set_lccode:nn
\vbox_gset_split_to_ht:ccn
\regex_extract_once:nnN
\file_timestamp:n
\str_greplace_all:cnn
\prop_put_from_keyval:cn
\skip_if_finite:nT
\cctab_item:Nn
\keys_set_known:noN
\prop_get:cnNTF
\prop_set_eq:NN
\clist_if_exist:NF
\peek_charcode_remove:NT
\cs_gset_eq:Nc
\tl_if_eq_p:Nc
\int_step_function:nN
\prop_gpop:NnNF
\bool_until_do:nn
\exp_args:Noof
\pdf_version_compare:NnTF
\iow_show:N
\dim_compare_p:nNn
\tl_gconcat:ccc
\vbox_set_split_to_ht:Ncn
\clist_set_from_seq:cN
\str_if_eq:VnF
\prop_put:Non
\prop_map_inline:cn
\seq_show:c
\token_if_toks_register_p:N
\dim_if_exist:cTF
\hbox_gset_to_wd:cnn
\regex_extract_once:nnNF
\c_sys_shell_escape_int
\quark_if_no_value_p:N
\str_case:nvF
\box_resize_to_wd_and_ht:Nnn
\msg_info:nn
\tl_if_empty:NTF
\box_scale:cnn
\str_gset:cV
\str_case:Vn
\cs_meaning:N
\tl_gremove_once:Nn
\seq_get_left:cNT
\tl_if_head_eq_catcode:oNT
\cs_if_exist:NT
\c_ampersand_str
\seq_get:NNTF
\clist_set_eq:cN
\cs_generate_from_arg_count:Ncnn
\regex_replace_all:NnNT
\box_set_viewport:Nnnnn
\sys_if_output_dvi_p:
\bool_lazy_and_p:nn
\fp_gset:cn
\box_resize_to_ht:Nn
\str_set:NV
\dim_gzero_new:N
\l_text_case_exclude_arg_tl
\tl_tail:f
\prop_gput:NVn
\skip_gset:cn
\exp_args:NNe
\keys_precompile:nnN
\regex_replace_once:nnNT
\seq_gpush:cn
\tl_put_right:Nn
\msg_note:nnnnnn
\int_gset_eq:cN
\seq_gput_left:co
\skip_vertical:n
\char_str_titlecase:N
\char_set_sfcode:nn
\str_if_eq:onT
\intarray_gset_rand:Nnn
\box_gset_to_last:N
\msg_show:nnx
\str_if_eq:onF
\seq_push:Nx
\int_to_alph:n
\skip_const:cn
\char_set_catcode_letter:n
\bool_gset_false:c
\peek_gafter:Nw
\box_resize_to_wd_and_ht_plus_dp:cnn
\tl_replace_once:cnn
\box_gscale:cnn
\bool_set_eq:NN
\tl_if_eq:NnF
\clist_remove_duplicates:N
\skip_vertical:N
\clist_pop:NNTF
\fp_zero_new:N
\str_case_e:nnT
\cs_if_exist_use:c
\prop_gput:cnV
\tl_if_empty:cF
\int_if_exist:cTF
\dim_to_decimal_in_sp:n
\str_map_break:
\msg_warning:nnxxx
\msg_fatal:nn
\tl_gclear:c
\seq_if_in:cVTF
\seq_gpop_item:cnN
\int_do_while:nNnn
\int_case:nnT
\hcoffin_gset:cn
\color_fill:n
\iow_open:Nn
\quark_if_recursion_tail_break:NN
\coffin_dp:c
\tl_if_in:nnTF
\msg_error:nnnnn
\regex_split:nnN
\iow_shipout_x:cx
\token_if_protected_long_macro:NTF
\c_catcode_active_tl
\tl_build_end:N
\intarray_gset_rand:Nn
\dim_to_decimal_in_unit:nn
\tl_gset:Nn
\box_set_dp:cn
\cs_if_exist_use:cTF
\exp_args:cc
\str_if_eq:ccTF
\token_if_space:NF
\file_if_exist_input:n
\token_if_chardef:NT
\file_get_hex_dump:nNT
\prop_put_if_new:cnn
\exp_args:NcV
\str_if_in:cnTF
\cs_gset_nopar:Npn
\regex_replace_case_all:nN
\tl_set:cx
\skip_gzero_new:N
\clist_gput_right:co
\msg_see_documentation_text:n
\clist_gset_eq:NN
\tl_if_in:NnF
\tl_set_eq:cc
\box_gscale:Nnn
\keys_set_filter:nnn
\prop_gput:NVx
\clist_if_in:nnF
\l_tmpb_clist
\str_gclear:N
\tl_if_exist_p:c
\int_to_hex:n
\quark_if_nil:VTF
\regex_extract_all:NnN
\iow_log_list:
\coffin_gjoin:cnncnnnn
\cs_new_nopar:Nn
\int_const:Nn
\seq_set_item:NnnTF
\bool_case_false:nF
\char_set_catcode_group_end:n
\box_use_drop:N
\fp_if_nan:nTF
\prop_put:coo
\int_gzero:N
\tl_gclear_new:c
\exp_after:wN
\prop_rand_key_value:N
\box_autosize_to_wd_and_ht_plus_dp:Nnn
\box_if_exist_p:c
\tl_if_head_is_group:nF
\str_case:onT
\box_show:N
\regex_replace_once:nnN
\token_if_group_end:NF
\debug_off:n
\c_minus_inf_fp
\bool_xor:nnTF
\pdf_version:
\mode_if_math:F
\str_if_eq_p:Vn
\tl_gremove_all:Nn
\file_get_full_name:nN
\char_value_lccode:n
\exp_args:Nco
\prop_item:Nn
\token_if_parameter:NTF
\msg_show:nnnnn
\seq_pop_item:NnN
\dim_gzero:N
\seq_gput_left:cv
\cs_gset_protected:Nx
\str_tail:c
\seq_map_break:
\dim_add:Nn
\clist_gset:No
\msg_log:nnnnnn
\char_str_uppercase:N
\tl_gset_rescan:cno
\tl_gput_right:Nn
\tl_if_single:NT
\iow_close:c
\muskip_gsub:Nn
\token_if_cs:NT
\tl_if_empty:nTF
\seq_map_break:n
\regex_split:NnNF
\tl_const:cn
\token_if_primitive_p:N
\c_code_cctab
\exp_not:N
\exp_args:NVo
\flag_raise:n
\exp_last_unbraced:NNo
\seq_gpush:cV
\msg_set:nnn
\str_tail_ignore_spaces:n
\quark_if_no_value:NTF
\exp_last_unbraced:NnNo
\prop_gput:con
\tl_map_function:cN
\clist_use:Nnnn
\if_cs_exist:w
\clist_map_variable:NNn
\tl_if_blank_p:e
\int_until_do:nn
\cs_new:cx
\prop_get:NVNT
\bool_gset_eq:cN
\prop_get:NVNTF
\mode_if_horizontal:T
\prop_map_inline:Nn
\msg_warning:nnx
\use_none:nnnnnnnn
\use:x
\l_tmpb_seq
\muskip_if_exist_p:N
\prop_gpop:cnNF
\seq_item:Nn
\clist_gset:cn
\clist_gsort:cn
\msg_term:nnnnnn
\tl_reverse:o
\seq_if_exist_p:N
\g_tmpa_prop
\prop_set_from_keyval:cn
\tl_if_blank:eTF
\str_gput_left:Nx
\str_if_eq:noTF
\int_to_arabic:n
\seq_if_in:NVTF
\bool_if_p:N
\box_resize_to_wd:Nn
\msg_redirect_class:nn
\bool_if_p:c
\bool_if:nT
\g_tmpa_tl
\if_mode_vertical:
\seq_greverse:N
\str_range:cnn
\cs_if_eq:NNT
\str_if_eq:cNTF
\tl_if_empty_p:N
\tl_if_single:nF
\muskip_if_exist:cT
\prop_gclear_new:N
\seq_gpop:NNF
\exp_args:NcNc
\g_tmpb_ior
\coffin_display_handles:Nn
\cs_new_protected_nopar:cn
\cs_log:N
\prop_gput:cnx
\g_tmpa_ior
\intarray_gset:Nnn
\muskip_gzero_new:N
\bool_gset_eq:NN
\str_lowercase:f
\tl_trim_spaces:c
\tl_trim_spaces:o
\bool_until_do:Nn
\use_none_delimit_by_q_recursion_stop:w
\tl_remove_all:Nn
\muskip_sub:Nn
\sys_if_engine_xetex_p:
\seq_gset_from_function:NnN
\flag_log:n
\seq_gsort:Nn
\box_dp:c
\intarray_const_from_clist:cn
\clist_gput_right:NV
\skip_gset_eq:cc
\token_if_active:NTF
\prop_to_keyval:N
\l_text_math_delims_tl
