\str_if_eq:VnTF
\bool_log:N
\clist_show:N
\tl_tail:n
\clist_if_empty:nF
\use:e
\ior_close:N
\tl_reverse:N
\token_if_other:NTF
\int_if_exist:NF
\l_tmpa_clist
\seq_gput_left:cx
\quark_if_nil_p:N
\sys_if_platform_unix:TF
\l_text_expand_exclude_tl
\seq_put_left:No
\vcoffin_gset:cnn
\prop_put:cno
\prop_map_function:cN
\g_tmpa_prop
\intarray_show:N
\fp_set_eq:NN
\mode_if_math_p:
\seq_if_empty:NTF
\msg_show:nnxxx
\str_gput_right:Nn
\tl_map_tokens:Nn
\tl_if_in:nnF
\tl_set_rescan:Nno
\seq_pop_right:cNTF
\dim_to_decimal:n
\msg_info:nnnnn
\c_max_register_int
\box_if_exist:NF
\prop_gpop:cnN
\skip_if_finite:nF
\int_gincr:N
\tl_if_single:cT
\c_one_int
\keys_set_groups:nnv
\prop_new:c
\str_if_eq:noT
\seq_if_exist_p:c
\exp_last_unbraced:NV
\token_if_eq_catcode:NNT
\msg_fatal:nnx
\vbox_set:cn
\prop_map_tokens:cn
\coffin_gresize:cnn
\use_ii:nnn
\tl_if_empty:VF
\keys_set_filter:nnonN
\sort_return_same:
\prop_if_empty_p:N
\str_case:nnT
\token_if_skip_register:NTF
\fp_compare:nNnT
\str_gset:Nx
\tl_replace_once:Nnn
\fp_to_tl:n
\str_put_right:NV
\char_show_value_lccode:n
\if_dim:w
\prop_put:cnn
\tl_tail:N
\cs_if_eq:NNTF
\vbox_gset_to_ht:Nnn
\dim_gset_eq:cc
\prop_gpop:NnNT
\prop_remove:cn
\msg_critical_text:n
\keys_set_filter:nnnN
\hbox_unpack:c
\str_if_eq:nvTF
\bool_if:NF
\tl_set_rescan:Nnn
\box_gautosize_to_wd_and_ht:cnn
\prop_get:NVNF
\legacy_if:nT
\prg_set_protected_conditional:Nnn
\int_abs:n
\fp_to_decimal:N
\box_gset_dp:Nn
\sys_if_output_dvi:T
\box_set_viewport:cnnnn
\c_group_end_token
\seq_gpush:No
\intarray_gset_rand:cnn
\msg_log:nnxx
\file_get_full_name:nNT
\peek_charcode_remove:NF
\coffin_scale:Nnn
\intarray_count:N
\tl_set:cv
\GetIdInfo
\int_const:Nn
\tl_if_in:noF
\box_if_exist:cT
\clist_gset_from_seq:NN
\str_set:cx
\prop_const_from_keyval:cn
\tl_gconcat:NNN
\tl_put_left:cV
\box_if_empty:cT
\prop_get:NoNF
\clist_put_right:No
\bool_log:n
\g_tmpb_fp
\token_if_other_p:N
\g_tmpb_prop
\char_str_foldcase:N
\cs_gset_eq:cc
\prop_new:N
\tl_if_eq:NnTF
\clist_rand_item:n
\fp_gadd:Nn
\c_max_dim
\char_gset_active_eq:NN
\exp_after:wN
\tl_gset:Nn
\tl_clear_new:N
\prop_get:cvNF
\skip_new:N
\coffin_new:N
\prg_replicate:nn
\sys_if_engine_xetex:F
\token_if_chardef:NTF
\fp_while_do:nn
\intarray_const_from_clist:Nn
\clist_gput_right:cx
\exp_args:NNNV
\cctab_gset:cn
\seq_gpop_right:cNT
\clist_use:Nnnn
\sys_if_platform_windows:TF
\str_if_in:nnF
\exp_args:Nnnc
\vbox_gset_split_to_ht:ccn
\keys_set_filter:nnoN
\tl_if_head_eq_catcode_p:oN
\seq_gpush:Nv
\muskip_gzero_new:N
\bool_do_while:nn
\prop_put_if_new:Nnn
\msg_log_eval:Nn
\bool_set_eq:Nc
\box_gset_wd:cn
\tl_gremove_once:Nn
\str_count:c
\clist_put_right:cV
\clist_if_in:NoT
\msg_critical:nnxxx
\tl_if_blank:oF
\tl_if_eq:NcTF
\bool_lazy_or:nnTF
\group_align_safe_begin:
\tl_if_eq_p:Nc
\seq_gpush:cv
\clist_gconcat:ccc
\dim_to_decimal_in_bp:n
\cs_if_free_p:c
\hbox_gset:Nn
\box_set_wd:cn
\sys_get_shell:nnN
\seq_gremove_duplicates:c
\peek_regex_remove_once:nTF
\dim_gzero:c
\str_map_variable:cNn
\seq_map_tokens:Nn
\dim_add:cn
\tl_set:cx
\int_if_even_p:n
\intarray_gset:cnn
\g_tmpb_tl
\tl_if_in:cnTF
\tl_gtrim_spaces:N
\tl_if_head_is_group:nTF
\char_set_catcode_parameter:n
\box_gresize_to_ht:Nn
\flag_if_exist:nTF
\msg_show:nn
\bool_new:N
\peek_regex:nT
\muskip_log:c
\char_set_catcode_comment:N
\token_if_long_macro_p:N
\cs_gset_protected:Nn
\msg_set:nnnn
\prop_gremove:cn
\box_autosize_to_wd_and_ht_plus_dp:Nnn
\exp_args:Noof
\file_parse_full_name_apply:nN
\tl_put_left:NV
\clist_put_left:No
\prop_gput:cnV
\peek_N_type:TF
\prop_gset_eq:cN
\msg_warning:nnn
\muskip_if_exist:cT
\coffin_set_eq:cN
\if_predicate:w
\tl_build_clear:N
\file_input:n
\exp_args:NNv
\token_case_meaning:NnF
\sys_if_output_pdf_p:
\str_put_left:cV
\seq_log:N
\tl_build_gbegin:N
\tl_if_exist:NTF
\int_sign:n
\cs_generate_from_arg_count:cNnn
\vbox_set_to_ht:cnw
\keys_set_known:nV
\prop_gpop:NoN
\fp_to_int:c
\box_dp:N
\g_tmpa_box
\if_case:w
\int_show:n
\seq_pop_left:NNF
\l_text_math_arg_tl
\ior_map_inline:Nn
\str_if_empty:cT
\sys_if_engine_luatex:TF
\prop_set_from_keyval:cn
\int_gzero_new:N
\skip_gset_eq:Nc
\hbox_gset_to_wd:Nnw
\cs_set_nopar:Npn
\token_if_group_begin:NT
\prop_gclear:c
\prop_get:NnN
\clist_item:Nn
\sys_if_engine_pdftex:TF
\regex_extract_once:NnNF
\str_if_eq:NcTF
\seq_item:Nn
\prop_get:cnNT
\dim_while_do:nNnn
\cs_gset_eq:NN
\seq_set_eq:cN
\tl_if_novalue:nTF
\token_if_math_superscript_p:N
\debug_off:n
\prop_gput:coo
\clist_if_empty_p:n
\coffin_gset_horizontal_pole:Nnn
\cs_if_exist_use:cTF
\sys_if_shell_unrestricted:F
\token_case_charcode:NnF
\seq_reverse:N
\dim_if_exist:cT
\l_keys_path_str
\str_convert_pdfname:n
\tl_build_gput_right:Nx
\str_const:cn
\str_set_convert:Nnnn
\cs_gset_nopar:cpx
\seq_gpop_left:NN
\flag_raise:n
\if_hbox:N
\str_set_eq:NN
\token_case_catcode:Nn
\seq_pop:cNTF
\seq_if_in:NvTF
\int_max:nn
\token_if_group_end:NF
\box_gset_viewport:Nnnnn
\muskip_gadd:cn
\vcoffin_gset:cnw
\seq_map_indexed_function:NN
\file_get_size:nN
\keys_set:nv
\if_true:
\box_set_eq_drop:NN
\exp_args:Neee
\int_to_arabic:n
\muskip_log:n
\prop_get:cnNTF
\int_compare:nNnTF
\clist_sort:Nn
\hbox_set_to_wd:Nnw
\msg_module_name:n
\fp_log:n
\prop_if_exist:cF
\c_math_superscript_token
\token_if_space:NF
\q_recursion_stop
\fp_compare:nNnF
\int_eval:w
\prop_clear:N
\quark_if_nil:nF
\prg_new_protected_conditional:Npnn
\iow_now:Nx
\int_case:nnTF
\g_tmpa_ior
\seq_get_left:cNT
\msg_fatal:nnnnn
\tl_remove_all:cn
\prop_if_in:NoF
\cs_gset_protected_nopar:Nn
\str_if_exist:NT
\prg_return_true:
\skip_gsub:cn
\cs_if_exist_p:N
\clist_gset:cV
\prg_set_conditional:Nnn
\char_set_catcode_alignment:n
\fp_const:cn
\cs_gset_eq:cN
\seq_pop_right:cNT
\intarray_log:N
\seq_gset_split:NnV
\cs_end:
\str_map_function:nN
\msg_new:nnnn
\skip_gzero:N
\peek_analysis_map_break:n
\file_get_hex_dump:nnnN
\prop_pop:cnNTF
\c_colon_str
\lua_shipout:n
\fparray_new:Nn
\seq_get_left:cNTF
\file_get:nnNTF
\prop_gput:Noo
\token_if_cs:NTF
\msg_term:nnnnn
\sys_get_shell:nnNTF
\file_get_hex_dump:nN
\coffin_if_exist:cF
\q_no_value
\quark_if_recursion_tail_break:nN
\int_const:cn
\coffin_if_exist_p:c
\token_if_letter_p:N
\coffin_scale:cnn
\seq_gput_right:No
\fp_abs:n
\s_stop
\msg_term:nnxxx
\tl_if_in:nnTF
\token_if_muskip_register:NF
\c_max_skip
\vbox_gset_to_ht:cnw
\if_bool:N
\msg_log:nnxxx
\tl_if_blank_p:o
\msg_see_documentation_text:n
\bool_set_inverse:N
\clist_use:cn
\g_tmpa_regex
\int_while_do:nn
\char_set_catcode_group_end:N
\cs_new_eq:Nc
\int_eval:n
\char_set_catcode_alignment:N
\keys_set_filter:nnvnN
\sys_shell_shipout:n
\tl_set:Nf
\file_get_full_name:VNF
\iow_now:Nn
\prop_gset_eq:Nc
\intarray_to_clist:N
\box_set_eq:cN
\prop_gput_if_new:cnn
\box_set_eq_drop:Nc
\prop_if_in:coT
\cs_if_exist:NF
\tl_range:nnn
\skip_if_finite_p:n
\tl_if_eq_p:NN
\cs_if_exist_use:N
\seq_gput_right:cn
\int_from_alph:n
\sys_shell_shipout:x
\prop_gclear_new:c
\coffin_attach:Nnncnnnn
\text_declare_expand_equivalent:cn
\int_if_exist:cTF
\seq_gset_from_inline_x:Nnn
\token_if_protected_macro:NF
\prop_set_eq:cc
\sys_if_shell_restricted:T
\skip_if_eq:nnF
\str_gset_convert:NnnnTF
\tl_if_eq:nnT
\str_case:nv
\seq_gput_right:cv
\hbox_overlap_center:n
\seq_push:cV
\mode_if_inner_p:
\msg_warning:nnnnnn
\use_none:nn
\tl_remove_once:Nn
\msg_new:nnn
\legacy_if:nF
\str_case_e:nnF
\use_none_delimit_by_q_recursion_stop:w
\tl_analysis_map_inline:nn
\sys_load_deprecation:
\clist_gput_right:cn
\exp_not:n
\cs_new:cpn
\iow_shipout:cn
\token_if_dim_register_p:N
\clist_show:c
\int_gset_eq:cc
\str_clear_new:c
\ior_open:cnF
\str_if_eq:nnT
\tl_if_head_eq_catcode:oNT
\str_log:n
\peek_regex_remove_once:nF
\exp_stop_f:
\cs_undefine:c
\exp_args:Nnno
\box_new:c
\coffin_gset_horizontal_pole:cnn
\box_use_drop:N
\msg_term:nn
\clist_sort:cn
\box_gset_eq_drop:cc
\seq_get_left:cN
\cs_new_protected:cn
\int_compare_p:n
\str_case:nn
\seq_map_break:
\token_if_group_end_p:N
\seq_put_left:cV
\fp_log:N
\prg_new_eq_conditional:NNn
\clist_gset_from_seq:cN
\char_set_catcode_other:n
\coffin_gattach:cnnNnnnn
\cs_new_nopar:cn
\clist_if_in:cVT
\skip_set_eq:Nc
\bool_if:NTF
\msg_expandable_error:nn
\prop_get:NnNTF
\box_grotate:Nn
\tl_gput_right:cV
\sys_if_engine_luatex:F
\clist_if_in:noF
\str_const:cV
\peek_meaning_remove_ignore_spaces:NTF
\str_gset:Nn
\ProvidesExplClass
\token_if_macro_p:N
\box_gset_trim:cnnnn
\tl_if_blank:VF
\iow_shipout:cx
\skip_gset_eq:cc
\seq_remove_duplicates:c
\clist_pop:NNF
\use_none:nnn
\token_if_macro:NT
\dim_log:c
\str_if_exist_p:N
\keys_set_filter:nnv
\char_set_catcode_letter:N
\token_if_int_register_p:N
\cs_gset_nopar:cx
\seq_gput_right:cV
\box_clip:N
\box_gset_eq_drop:Nc
\cs_if_exist_use:NF
\seq_get_right:cNT
\muskip_new:c
\regex_replace_once:nnNT
\color_group_end:
\fp_log:c
\coffin_grotate:Nn
\box_gresize_to_wd:cn
\tl_gput_right:Nn
\str_if_eq_p:ee
\peek_meaning:NT
\vbox_set_top:cn
\clist_if_exist:NF
\vbox_gset:cw
\seq_gpush:Nn
\file_get:nnNF
\cs_gset_nopar:Nn
\prop_gput:NVn
\if_false:
\clist_gpush:co
\prop_pop:NnN
\cs_if_exist:NTF
\tl_if_head_is_space:nT
\seq_count:N
\char_set_uccode:nn
\peek_regex_replace_once:NnT
\char_set_catcode_math_superscript:n
\prop_put:Nnx
\debug_resume:
\clist_put_right:co
\exp_end:
\c_zero_str
\sys_if_shell_restricted:F
\clist_gput_right:co
\char_set_catcode_ignore:N
\str_concat:NNN
\token_if_group_begin:NF
\c_sys_minute_int
\ior_open:Nn
\vbox_gset_split_to_ht:Ncn
\token_if_toks_register:NF
\str_if_eq_p:VV
\use_none:n
\coffin_if_exist:NTF
\token_if_group_end:NTF
\bool_gset_false:c
\exp_args:NcNc
\str_new:c
\scan_stop:
\int_if_even:nF
\clist_gset:co
\prop_put:cVV
\iow_shipout:Nn
\prg_return_false:
\exp_args:NcVV
\skip_horizontal:n
\seq_gpop_right:cN
\exp_last_unbraced:NNNNf
\tl_item:nn
\ior_open:NnTF
\fp_to_dim:N
\tl_reverse:n
\peek_regex:nTF
\if_vbox:N
\tl_clear:c
\if_eof:w
\cs_split_function:N
\exp_args:Noo
\seq_remove_duplicates:N
\cs_if_exist_use:cF
\int_if_even:nT
\token_if_other:NT
\box_if_vertical:NF
\tl_if_empty:oTF
\prop_const_from_keyval:Nn
\quark_if_nil:NTF
\seq_gpop:NNT
\cctab_select:N
\bool_set_true:N
\tl_set:No
\seq_set_from_clist:cN
\box_clear:c
\prop_if_exist_p:c
\tl_reverse_items:n
\peek_charcode_ignore_spaces:NTF
\int_do_until:nn
\sys_if_shell:TF
\clist_pop:NNT
\char_show_value_catcode:n
\seq_gput_left:Nn
\dim_case:nnF
\bool_lazy_and:nnF
\vbox_unpack:c
\seq_gput_right:NV
\if:w
\cs_gset_protected_nopar:cpx
\msg_log:nnn
\exp_args:cc
\tl_if_in:nnT
\seq_if_in:cxT
\tl_map_break:n
\ProvidesExplFile
\bool_if_exist:NF
\file_if_exist:nF
\char_set_catcode_invalid:N
\l_tmpa_dim
\coffin_gclear:N
\regex_show:N
\token_if_group_end:NT
\tl_if_eq:nnF
\peek_catcode_remove_ignore_spaces:NF
\tl_if_exist_p:c
\tl_trim_spaces:c
\iow_close:N
\cs_gset_nopar:Npn
\c_sys_output_str
\fp_if_exist:NTF
\str_uppercase:n
\cs_new_nopar:Npn
\prop_log:N
\bool_gset:cn
\regex_replace_once:nnNTF
\box_resize_to_wd_and_ht:cnn
\prop_gpop:coN
\tl_if_empty:cTF
\file_compare_timestamp:nNnF
\cctab_const:cn
\msg_gset:nnnn
\cs_set_protected:cpn
\skip_if_exist:cTF
\prop_map_break:
\bool_case_false:nTF
\iow_shipout_x:Nx
\fp_to_tl:N
\clist_count:c
\clist_pop:NNTF
\dim_gset:Nn
\tl_if_empty:NTF
\seq_if_in:cvT
\str_case:nVF
\clist_gset_eq:cN
\str_if_eq:vnF
\token_to_str:N
\prop_get:NnNT
\prop_gput_if_new:Nnn
\exp_args:Nxx
\cs_new_eq:NN
\fp_to_tl:c
\sort_return_swapped:
\str_case:VnT
\tl_if_eq:NcT
\c_log_iow
\exp_args:NNoo
\skip_log:N
\use:nnn
\int_add:Nn
\clist_put_left:cx
\seq_concat:ccc
\seq_new:c
\char_to_utfviii_bytes:n
\text_titlecase:n
\dim_ratio:nn
\regex_replace_all:NnNTF
\muskip_if_exist:cTF
\c_initex_cctab
\seq_pop_left:NN
\prop_rand_key_value:c
\dim_use:c
\tl_if_head_eq_charcode:fNTF
\box_if_exist:NT
\token_if_math_superscript:NT
\fp_gset_eq:cN
\prg_generate_conditional_variant:Nnn
\msg_info:nnxxxx
\msg_log:nnnnnn
\box_set_trim:Nnnnn
\tl_reverse:o
\seq_if_in:NVTF
\tl_log:n
\token_if_space:NTF
\dim_show:n
\muskip_const:cn
\int_set:Nn
\seq_gpush:cn
\box_move_left:nn
\g_tmpa_skip
\skip_add:cn
\msg_set:nnn
\str_tail:n
\keys_if_choice_exist:nnnT
\coffin_if_exist:cTF
\dim_compare:nNnTF
\str_case:onT
\fp_to_decimal:n
\bool_do_while:cn
\coffin_display_handles:Nn
\tl_map_inline:Nn
\msg_show_item:n
\char_set_catcode_space:N
\box_clear_new:N
\hbox_set:Nn
\exp_not:V
\fp_gzero:c
\cctab_new:c
\str_put_left:cx
\seq_pop_right:cN
\tl_set:cV
\bool_lazy_and_p:nn
\prop_pop:NnNTF
\clist_gremove_all:Nn
\seq_use:Nnnn
\str_if_in:nnT
\seq_put_left:NV
\prop_if_exist:NTF
\c_term_iow
\prop_clear:c
\str_map_function:NN
\seq_gpop:NNTF
\legacy_if_p:n
\str_if_in:cnF
\token_case_catcode:NnTF
\box_gset_eq:Nc
\l_tmpb_seq
\coffin_set_vertical_pole:cnn
\hbox_set_to_wd:cnw
\seq_put_right:cn
\seq_pop:cNF
\ior_str_get:NNF
\tl_if_empty:NF
\fp_gset_eq:NN
\muskip_set_eq:cc
\token_if_math_superscript:NTF
\tl_to_str:N
\msg_info:nnxx
\c_sys_engine_version_str
\prop_gput:cxx
\clist_remove_duplicates:N
\c_atsign_str
\tl_map_function:NN
\str_if_eq:eeTF
\cs_if_free:cF
\tl_if_exist_p:N
\clist_gput_right:cV
\bool_set_inverse:c
\exp_args:Ncco
\char_value_mathcode:n
\box_if_exist_p:c
\c_max_int
\int_if_exist:NT
\token_if_expandable:NTF
\cs_gset_protected_nopar:cx
\dim_set_eq:NN
\coffin_wd:c
\cs_if_eq_p:NN
\cs_generate_variant:cn
\cs_new_protected:Nx
\ior_if_eof:NT
\file_get_full_name:nNTF
\str_if_eq:noTF
\char_value_catcode:n
\coffin_set_vertical_pole:Nnn
\sys_if_engine_pdftex:F
\text_purify:n
\clist_map_function:NN
\seq_gpop:cNT
\prop_if_in:NnF
\str_case:Vn
\bool_until_do:nn
\peek_charcode_remove_ignore_spaces:NT
\peek_meaning_collect_inline:Nn
\cs_new_protected_nopar:Npx
\box_move_right:nn
\tl_gclear_new:c
\seq_if_exist:NT
\cctab_if_exist_p:c
\c_other_cctab
\tl_if_in:VnTF
\tl_if_head_is_space:nTF
\cs_gset_nopar:cpn
\box_if_horizontal:NT
\intarray_new:Nn
\seq_mapthread_function:NcN
\str_map_function:cN
\regex_extract_all:nnNTF
\text_declare_purify_equivalent:Nn
\prop_if_in:NnT
\clist_map_function:cN
\skip_gset:cn
\str_gset_convert:Nnnn
\str_set_convert:NnnnTF
\keys_set_known:nnN
\exp_last_unbraced:NnNo
\seq_if_empty:NF
\cs_if_exist_p:c
\seq_if_exist:NF
\file_get_timestamp:nN
\box_gset_eq:cN
\tl_gput_left:cV
\str_put_left:Nx
\msg_show:nnn
\box_dp:c
\prop_show:c
\token_if_font_selection:NTF
\ior_map_variable:NNn
\str_remove_all:Nn
\token_if_math_subscript:NTF
\keys_set_filter:nnVnN
\sys_if_shell_unrestricted_p:
\hbox_overlap_left:n
\coffin_dp:N
\exp_args:NNox
\c_zero_fp
\use_i:nnnn
\int_zero:N
\int_case:nnT
\msg_critical:nnnn
\regex_replace_all:NnNF
\str_range_ignore_spaces:nnn
\tl_if_in:onF
\msg_if_exist:nnT
\int_show:c
\mode_if_math:TF
\seq_put_left:Nn
\token_if_active:NT
\clist_push:Nx
\peek_catcode_remove_ignore_spaces:NTF
\tl_gset:Nf
\seq_get_right:NNTF
\g_tmpa_muskip
\box_log:N
\fp_if_exist:cF
\fp_gzero_new:c
\token_if_math_toggle:NF
\muskip_zero:N
\tl_replace_all:Nnn
\tl_if_head_is_group:nF
\str_if_exist_p:c
\l_text_math_delims_tl
\l_tmpb_skip
\skip_set:cn
\prg_set_conditional:Npnn
\dim_show:N
\ior_open:cnTF
\clist_gput_left:NV
\coffin_set_eq:Nc
\int_until_do:nn
\token_if_font_selection_p:N
\coffin_gscale:cnn
\token_if_skip_register_p:N
\prop_put:cVx
\seq_put_right:Nv
\str_gput_left:cx
\exp_args:NVo
\box_show:N
\msg_term:nnx
\exp_args:Noc
\str_case:nnF
\cs_if_free:cT
\token_to_meaning:N
\peek_charcode_ignore_spaces:NF
\sys_get_shell:nnNT
\str_case:VnTF
\ior_map_break:n
\cs_set_protected:cpx
\box_if_vertical:NT
\g_peek_token
\skip_if_exist_p:c
\l_tmpb_str
\str_if_exist:NTF
\use:nnnn
\seq_pop_left:cNF
\keys_set_groups:nnV
\file_compare_timestamp:nNnT
\sys_if_platform_unix:F
\tl_to_str:c
\int_div_round:nn
\ior_get:NNT
\sys_if_output_pdf:TF
\prop_put:cvx
\clist_gset:NV
\quark_if_nil:nT
\l_tmpa_str
\msg_warning:nnnnn
\peek_regex_replace_once:NnF
\str_if_in:nnTF
\seq_show:c
\box_set_wd:Nn
\hcoffin_gset:cn
\seq_if_in:cvF
\exp_not:f
\seq_pop_right:NNT
\regex_replace_once:NnN
\hcoffin_set_end:
\dim_use:N
\ExplSyntaxOn
\str_greplace_all:cnn
\seq_gset_from_clist:cn
\msg_redirect_module:nnn
\prop_get:cvNTF
\tl_set:co
\fp_use:N
\clist_log:N
\cs_gset_nopar:Nx
\prop_if_exist:NF
\dim_gsub:cn
\muskip_use:N
\clist_if_in:noTF
\tl_reverse:V
\int_new:c
\clist_greverse:c
\clist_use:cnnn
\str_gset_eq:NN
\tl_if_eq_p:cc
\seq_get_right:NNT
\tl_gput_right:Nx
\prop_if_empty:cF
\peek_regex_remove_once:NF
\cs_undefine:N
\exp_args:Ncx
\prop_map_inline:cn
\seq_map_variable:Ncn
\seq_if_in:cnF
\msg_info:nnnn
\clist_set_from_seq:cN
\g_tmpa_dim
\seq_gsort:cn
\bool_case_true:nTF
\int_compare:nF
\dim_compare:nNnF
\vbox_unpack_drop:N
\seq_map_variable:cNn
\c_catcode_active_tl
\int_from_bin:n
\iow_shipout_x:cn
\mode_if_inner:T
\coffin_new:c
\msg_expandable_error:nnnnnn
\prg_break_point:
\peek_catcode:NF
\tl_put_right:cn
\str_gconcat:NNN
\bool_while_do:nn
\msg_term:nnn
\keys_if_choice_exist:nnnTF
\char_set_catcode_math_superscript:N
\clist_get:cNTF
\seq_if_in:NxT
\char_set_catcode_math_subscript:n
\int_rand:nn
\prop_if_in_p:NV
\sys_if_engine_luatex_p:
\flag_clear:n
\str_tail:c
\seq_shuffle:c
\skip_use:c
\fi:
\flag_show:n
\seq_set_map_x:NNn
\clist_get:cNT
\str_map_inline:nn
\prop_get:cVNT
\coffin_set_eq:cc
\msg_critical:nnnnnn
\box_scale:cnn
\clist_new:c
\tl_if_empty:oF
\file_get_hex_dump:nnnNTF
\seq_clear_new:N
\dim_log:N
\skip_zero:N
\clist_gset:No
\coffin_attach:NnnNnnnn
\tl_head:V
\seq_mapthread_function:cNN
\fp_if_exist:cT
\char_value_sfcode:n
\bool_if_p:N
\fp_if_nan:nTF
\token_if_chardef:NF
\int_step_function:nnN
\ior_str_get_term:nN
\str_new:N
\tl_gset_eq:cN
\int_do_until:nNnn
\ior_if_eof:NTF
\tl_if_in:cnT
\seq_sort:Nn
\clist_gpush:cx
\clist_rand_item:N
\skip_gadd:cn
\clist_if_exist:cTF
\clist_gput_right:NV
\flag_if_raised:nF
\fp_step_inline:nnnn
\ior_str_map_variable:NNn
\quark_if_no_value:nT
\char_set_catcode_active:n
\clist_show:n
\exp_args:NNno
\cs_log:c
\cs_if_free:NT
\clist_if_empty:nT
\seq_if_in:cVF
\seq_gshuffle:c
\seq_use:Nn
\seq_push:Nn
\tl_count:c
\box_set_viewport:Nnnnn
\c_empty_clist
\regex_match:NnF
\seq_pop_right:NNF
\if_mode_math:
\seq_gset_map:NNn
\fp_until_do:nNnn
\flag_if_raised:nT
\str_remove_once:Nn
\tl_gset:cV
\l_keys_choice_tl
\tl_if_blank:eTF
\dim_to_decimal_in_sp:n
\clist_if_in:coF
\prop_put:Noo
\sys_if_engine_uptex_p:
\lua_now:e
\seq_if_in:NnF
\quark_if_recursion_tail_stop:N
\msg_critical:nn
\str_clear:N
\c_sys_engine_exec_str
\peek_analysis_map_inline:n
\fp_compare:nTF
\box_set_eq:cc
\cs_new:cpx
\file_get_hex_dump:nnnNT
\skip_if_finite:nT
\clist_if_in:cnF
\bool_gset_inverse:N
\fp_to_dim:n
\if_mode_horizontal:
\tl_if_head_is_space_p:n
\file_compare_timestamp_p:nNn
\str_concat:ccc
\box_if_horizontal_p:c
\dim_until_do:nNnn
\token_if_expandable:NF
\clist_const:cx
\exp_args:Nnx
\coffin_gresize:Nnn
\cs_new:cn
\char_set_catcode_other:N
\seq_put_left:Nv
\muskip_gset_eq:NN
\clist_gput_right:Nx
\peek_charcode_collect_inline:Nn
\str_put_right:Nx
\exp_last_unbraced:No
\exp_args:Nccx
\coffin_join:cnncnnnn
\seq_gremove_all:cn
\sys_load_debug:
\cs_new_protected_nopar:Nx
\token_if_muskip_register_p:N
\fp_const:Nn
\tl_remove_all:Nn
\file_size:n
\skip_horizontal:N
\box_rotate:Nn
\vcoffin_set_end:
\tl_if_in:onTF
\g_tmpa_int
\seq_put_right:cv
\fp_set_eq:cN
\skip_const:cn
\muskip_if_exist:NF
\msg_module_type:n
\c_novalue_tl
\tl_use:c
\muskip_set:Nn
\box_if_vertical_p:c
\box_if_exist:NTF
\token_to_str:c
\tl_build_put_right:Nx
\clist_concat:ccc
\ior_open:cnT
\file_full_name:n
\c_false_bool
\sys_if_shell_unrestricted:T
\dim_sub:Nn
\bool_if:nT
\token_if_eq_charcode:NNF
\ior_new:N
\box_resize_to_ht:Nn
\cs_new_eq:cN
\c_inf_fp
\sys_if_output_pdf:T
\box_wd:c
\skip_show:n
\regex_const:Nn
\clist_set_from_seq:NN
\seq_gpop_right:NN
\coffin_dp:c
\clist_get:NNF
\str_case_e:nnTF
\tl_set_rescan:Nnx
\box_if_horizontal:NF
\hcoffin_gset_end:
\msg_line_context:
\tl_count:n
\clist_count:n
\fparray_gzero:N
\int_if_odd:nTF
\msg_show:nnx
\prop_if_in:coF
\tl_clear:N
\prop_if_in:NoT
\box_set_to_last:c
\file_if_exist:nT
\c_catcode_letter_token
\tl_if_head_is_N_type:nF
\int_compare:nT
\prop_pop:NnNF
\keys_set_known:no
\l_tmpa_tl
\str_if_eq_p:Nc
\msg_expandable_error:nnffff
\cs_new_protected_nopar:Npn
\prop_set_from_keyval:Nn
\use_i:nnn
\bool_lazy_or_p:nn
\bool_do_until:cn
\box_gset_eq:NN
\str_if_eq:onT
\tl_gset:cx
\clist_put_left:cn
\str_case_e:nn
\cs_replacement_spec:N
\tl_gset:Nv
\tl_if_head_eq_charcode:fNT
\file_hex_dump:nnn
\clist_gset:cn
\ior_get:NN
\l_keys_value_tl
\tl_if_eq:NNF
\coffin_gjoin:Nnncnnnn
\char_set_catcode_active:N
\quark_if_nil_p:n
\fp_zero:N
\box_if_horizontal:cTF
\muskip_gset_eq:cc
\exp_last_unbraced:NNNf
\seq_if_in:NoF
\skip_if_exist:NTF
\clist_gclear_new:N
\tl_if_empty:cT
\cs_gset_nopar:cn
\prop_gput:cVx
\quark_if_nil_p:V
\peek_charcode_remove_ignore_spaces:NTF
\seq_gset_from_clist:cc
\str_case:nvT
\seq_gpop_right:cNF
\regex_extract_once:NnNT
\fp_gadd:cn
\mode_if_horizontal:T
\coffin_set_eq:NN
\vbox_gset:Nn
\dim_compare_p:nNn
\str_if_eq:NcF
\seq_if_in:cVTF
\dim_to_decimal_in_unit:nn
\token_if_eq_charcode_p:NN
\seq_if_in:cVT
\seq_gclear:c
\clist_gconcat:NNN
\flag_if_raised_p:n
\tl_gset_rescan:Nnn
\dim_gzero_new:N
\str_if_eq:nvF
\prop_set_eq:NN
\seq_set_from_inline_x:Nnn
\regex_replace_all:nnNTF
\bool_if:cT
\text_titlecase_first:n
\box_if_exist:cF
\seq_get_right:NNF
\str_set_eq:Nc
\c_right_brace_str
\tl_case:NnF
\seq_put_left:co
\clist_gput_left:cn
\exp_args:Ne
\token_if_math_subscript:NT
\l_peek_token
\seq_set_from_clist:Nc
\iow_allow_break:
\regex_extract_all:NnNT
\g_tmpa_seq
\fp_show:c
\skip_vertical:n
\int_if_exist_p:N
\token_if_math_subscript_p:N
\muskip_set:cn
\box_set_dp:cn
\int_decr:c
\prop_gremove:cV
\token_if_muskip_register:NT
\box_gresize_to_wd_and_ht:Nnn
\prop_get:coNF
\vcoffin_set:Nnn
\bool_case_true:n
\box_resize_to_wd_and_ht:Nnn
\peek_regex:NT
\prop_gpop:cnNT
\fp_gsub:Nn
\char_set_catcode_group_begin:n
\ior_str_map_inline:Nn
\prop_clear_new:N
\int_set_eq:NN
\fp_gset_eq:Nc
\cs_new:Npx
\coffin_typeset:cnnnn
\box_if_empty_p:c
\tl_if_empty:cF
\seq_concat:NNN
\prop_put:cxx
\fp_compare:nT
\seq_set_eq:cc
\flag_if_raised:nTF
\regex_count:nnN
\dim_log:n
\file_if_exist_input:nF
\quark_if_nil:NT
\cs_new_protected_nopar:cx
\clist_map_break:
\peek_charcode:NTF
\hbox_to_wd:nn
\regex_set:Nn
\bool_gset_eq:cc
\vcoffin_gset:Nnw
\quark_if_nil:VTF
\int_gsub:cn
\skip_zero_new:N
\seq_gput_right:co
\tl_if_in:cnF
\prop_set_eq:cN
\l_tmpa_prop
\g_tmpb_coffin
\dim_set:cn
\muskip_gzero:N
\str_uppercase:f
\hbox_gset_to_wd:cnw
\str_if_empty:NTF
\sys_if_engine_ptex:T
\coffin_join:Nnncnnnn
\l_tmpa_skip
\quark_if_recursion_tail_stop_do:nn
\exp_args:Nnf
\cs_gset_protected_nopar:Npx
\l_text_titlecase_check_letter_bool
\tl_case:cnF
\cs_gset:Npx
\tl_if_head_eq_catcode_p:nN
\coffin_mark_handle:Nnnn
\seq_gpop:cNTF
\ior_shell_open:Nn
\prop_pop:cnNT
\tl_greplace_all:cnn
\cs_new_nopar:Npx
\tl_gclear_new:N
\tl_gput_left:co
\dim_if_exist:NT
\clist_set:Nn
\clist_set_eq:cc
\tl_case:NnT
\regex_split:NnNT
\clist_put_left:co
\int_set_eq:Nc
\seq_rand_item:N
\c_empty_tl
\box_gautosize_to_wd_and_ht:Nnn
\iow_log_list:
\seq_gconcat:NNN
\dim_to_fp:n
\seq_map_function:NN
\prop_gput:cvx
\dim_if_exist:NTF
\g_tmpb_skip
\str_if_eq:VVF
\skip_vertical:c
\clist_if_in:coT
\cs_set_protected_nopar:cpx
\dim_until_do:nn
\vbox_gset_to_ht:cnn
\msg_show:nnxxxx
\clist_gset_eq:NN
\dim_max:nn
\msg_error:nnxxx
\msg_log:nnnnn
\tl_if_eq:cNTF
\bool_xor:nnF
\coffin_set_horizontal_pole:Nnn
\bool_case_true:nF
\str_if_empty:NT
\box_gresize_to_wd:Nn
\exp_args:Nff
\seq_gput_left:cV
\prop_gpop:NnNTF
\tl_trim_spaces:o
\regex_replace_once:NnNT
\cs_gset_protected:cx
\dim_sub:cn
\seq_gput_right:Nv
\prop_if_in_p:co
\cs_set_protected_nopar:Npn
\clist_log:n
\str_range:cnn
\tl_count:o
\dim_if_exist:NF
\str_if_exist:NF
\clist_if_in:NoTF
\text_titlecase:nn
\prop_if_in:cnT
\exp_last_unbraced:Nx
\quark_if_no_value:nTF
\tl_clear_new:c
\mode_if_inner:TF
\str_if_eq:nVTF
\keys_set_filter:nnn
\seq_gpop_left:cN
\tl_if_single_p:N
\l_tmpb_regex
\tl_gset:No
\str_if_eq_p:vn
\keys_set_filter:nno
\if_cs_exist:w
\tl_put_left:co
\str_if_eq:vnTF
\tl_item:cn
\dim_compare:nT
\skip_use:N
\hbox_set:cw
\box_gset_to_last:c
\char_set_catcode_comment:n
\clist_get:NN
\c_sys_engine_str
\token_if_eq_charcode:NNTF
\if_box_empty:N
\bool_gset_false:N
\bool_gset_eq:NN
\prop_if_empty:NTF
\vbox_set_to_ht:cnn
\seq_if_in:cnTF
\box_use:N
\token_if_cs:NT
\coffin_if_exist_p:N
\str_range:nnn
\int_if_odd:nF
\prop_gput:NVx
\vbox_gset_end:
\prop_gput:cnx
\cs_new_protected:Nn
\char_str_titlecase:N
\tl_put_right:No
\bool_gset_eq:Nc
\tl_set_eq:NN
\box_set_ht:cn
\msg_redirect_name:nnn
\l_text_accents_tl
\clist_reverse:n
\skip_if_exist:cF
\tl_gput_left:cx
\token_if_skip_register:NT
\cs_generate_from_arg_count:Ncnn
\sys_if_rand_exist:F
\seq_gset_split:Nnn
\seq_clear_new:c
\str_count:n
\if_int_odd:w
\regex_extract_all:nnN
\tl_greplace_once:cnn
\file_get_timestamp:nNTF
\dim_new:N
\int_min:nn
\seq_gpop:cNF
\c_alignment_token
\clist_gput_left:cx
\clist_if_in:nVTF
\box_gset_ht:Nn
\g_msg_module_type_prop
\tl_gsort:cn
\sys_if_platform_unix_p:
\keys_define:nn
\clist_remove_all:cn
\fp_step_function:nnnN
\str_if_eq:cNF
\tl_if_empty:nF
\tl_trim_spaces:n
\flag_clear_new:n
\str_use:c
\hbox_unpack_drop:N
\tl_if_single:nT
\fp_set:cn
\bool_if_exist_p:N
\sys_if_engine_uptex:F
\skip_set_eq:NN
\muskip_if_exist:NT
\str_if_eq:vnT
\sys_if_shell:T
\coffin_gjoin:cnncnnnn
\int_from_roman:n
\hbox_set_to_wd:Nnn
\c_circumflex_str
\g_file_curr_ext_str
\coffin_display_handles:cn
\bool_until_do:cn
\int_do_while:nn
\char_set_catcode_escape:n
\prop_if_in_p:No
\exp_args:NNx
\c_document_cctab
\prop_item:Nn
\int_use:c
\dim_sign:n
\str_if_eq:NNF
\seq_set_from_clist:cn
\skip_if_exist_p:N
\char_set_catcode_math_toggle:n
\seq_gpop:NN
\str_greplace_all:Nnn
\tl_show:N
\str_if_eq:NNTF
\int_compare:nNnF
\int_from_base:nn
\str_gset_convert:NnnnT
\msg_show_eval:Nn
\fp_gzero_new:N
\c_catcode_other_token
\msg_none:nnnnn
\bool_if_exist_p:c
\str_put_right:cV
\tl_concat:ccc
\regex_match:nnF
\quark_if_no_value_p:n
\tl_if_exist:NF
\prop_if_in_p:cV
\seq_gput_left:No
\clist_push:Nn
\peek_regex_replace_once:nnT
\cs_argument_spec:N
\use:n
\token_if_active_p:N
\str_set_convert:NnnnF
\prop_put:cVn
\skip_const:Nn
\sys_gset_rand_seed:n
\cs_set_eq:NN
\tl_analysis_map_inline:Nn
\tl_set_rescan:cnx
\token_if_math_superscript:NF
\msg_error_text:n
\prop_put:cnx
\char_set_catcode_ignore:n
\token_if_group_begin_p:N
\muskip_log:N
\tl_build_gend:N
\tl_if_eq_p:cN
\tl_if_head_eq_charcode:nNT
\cs_set_protected:Npn
\fp_sub:cn
\quark_if_no_value:nF
\quark_if_recursion_tail_break:NN
\msg_expandable_error:nnn
\sys_if_rand_exist:TF
\msg_expandable_error:nnf
\sys_if_shell_restricted:TF
\seq_get:NNT
\file_get_hex_dump:nNTF
\dim_if_exist_p:c
\box_if_vertical_p:N
\token_if_mathchardef_p:N
\peek_meaning_remove:NTF
\seq_gclear_new:c
\peek_regex_remove_once:NTF
\iow_now:cx
\coffin_gset_eq:cN
\str_head:n
\tl_rand_item:c
\tl_if_novalue_p:n
\seq_gpop:cN
\quark_if_no_value_p:c
\bool_if_exist:cF
\seq_if_in:coTF
\prg_break:
\seq_map_variable:ccn
\str_replace_once:cnn
\box_if_vertical:cF
\box_if_empty:cTF
\keyval_parse:nnn
\int_gzero:c
\c_sys_year_int
\l_tmpb_clist
\int_if_exist:NTF
\ior_get_term:nN
\mode_if_inner:F
\char_set_catcode_end_line:n
\use_none:nnnnnn
\str_const:NV
\token_if_long_macro:NT
\regex_new:N
\exp_not:v
\clist_gpush:NV
\exp_args:No
\prop_if_exist_p:N
\box_if_empty:NF
\muskip_use:c
\tl_if_in:noT
\keys_if_exist_p:nn
\tl_build_gput_right:Nn
\dim_zero_new:N
\bool_do_while:Nn
\prg_new_conditional:Npnn
\prop_put:Nno
\skip_show:N
\c_backslash_str
\msg_warning:nnnn
\peek_regex:nF
\box_if_vertical:cTF
\int_case:nnF
\seq_pop:cN
\cs_log:N
\box_set_eq_drop:cN
\clist_map_inline:cn
\tl_gput_left:Nx
\seq_get_right:cN
\quark_if_nil_p:o
\bool_lazy_any:nTF
\prop_gpop:cnNF
\exp_args:NVV
\exp_args:Ncc
\sys_if_platform_unix:T
\str_case:nnTF
\int_until_do:nNnn
\c_empty_seq
\iow_shipout:Nx
\exp_args:NNf
\prop_gclear:N
\vbox_set_split_to_ht:cNn
\exp_last_unbraced:Nno
\tl_show:c
\coffin_gattach:NnnNnnnn
\clist_set:No
\cctab_if_exist:cT
\seq_const_from_clist:Nn
\cs_set_nopar:cx
\cs_if_exist:cF
\exp_args:NNNv
\str_if_exist:cT
\seq_if_empty:cTF
\token_case_meaning:Nn
\c_hash_str
\exp_args:Nf
\box_resize_to_wd_and_ht_plus_dp:Nnn
\coffin_if_exist:cT
\prop_if_exist:cTF
\str_set_eq:cN
\mode_if_vertical_p:
\msg_expandable_error:nnff
\clist_gput_left:No
\quark_new:N
\dim_do_until:nNnn
\peek_meaning_ignore_spaces:NT
\l_tmpb_coffin
\sys_if_platform_windows_p:
\token_if_long_macro:NF
\cs_new_protected:Npn
\dim_zero:N
\seq_if_in:cxTF
\clist_push:NV
\msg_warning:nn
\tl_map_variable:NNn
\bool_set_false:N
\ior_show_list:
\l_tmpb_int
\tl_if_empty_p:N
\cs_set_protected_nopar:Npx
\regex_replace_once:nnNF
\clist_if_empty:cF
\muskip_new:N
\token_if_macro:NTF
\exp_not:o
\vbox_set:Nn
\prop_remove:cV
\tl_new:N
\str_if_eq:NcT
\clist_gremove_all:cn
\clist_if_in:cnT
\bool_set_true:c
\sys_if_engine_xetex:T
\seq_if_empty:cT
\seq_put_right:Nx
\token_if_eq_meaning:NNF
\clist_clear:c
\cs_set:Npx
\fp_set_eq:Nc
\peek_charcode_remove:NT
\file_hex_dump:n
\int_if_exist:cF
\cs_set_protected:Nx
\str_if_eq:NNT
\exp_args:Ncnx
\int_case:nn
\seq_gset_eq:cN
\str_gput_right:Nx
\clist_map_break:n
\str_if_eq_p:NN
\intarray_const_from_clist:cn
\muskip_gset_eq:Nc
\cctab_if_exist:cTF
\clist_if_in:coTF
\c_e_fp
\exp_args:NV
\seq_gconcat:ccc
\int_gadd:cn
\box_log:c
\int_compare:nNnT
\cs_new_protected_nopar:Nn
\exp_args:Ncv
\str_case:onTF
\text_titlecase_first:nn
\skip_vertical:N
\seq_set_eq:NN
\tl_build_gput_left:Nn
\prop_map_inline:Nn
\coffin_clear:c
\hbox_set:Nw
\char_set_lccode:nn
\token_case_catcode:NnT
\seq_remove_all:cn
\token_if_parameter:NT
\use_i_delimit_by_q_stop:nw
\intarray_gset:Nnn
\clist_if_in:cVF
\iow_new:c
\sys_shell_now:n
\regex_split:NnN
\tl_gconcat:ccc
\tl_range_unbraced:nnn
\bool_const:cn
\box_resize_to_ht:cn
\file_parse_full_name:n
\dim_new:c
\exp_args:Nnnf
\str_if_eq:nVF
\fp_if_exist_p:N
\seq_set_map:NNn
\dim_compare_p:n
\clist_if_in:NVF
\clist_set_from_seq:cc
\clist_log:c
\tl_if_single_p:n
\int_step_variable:nnNn
\tl_if_eq:ccTF
\str_if_empty_p:c
\iow_close:c
\tl_reverse:c
\prop_gput:cno
\skip_gset:Nn
\prop_if_empty_p:c
\quark_if_recursion_tail_stop:o
\ior_if_eof_p:N
\if_cs_exist:N
\l_tmpb_prop
\seq_push:cn
\tl_set_eq:Nc
\prop_put:NVn
\muskip_zero_new:N
\tl_map_variable:cNn
\str_map_inline:cn
\exp_args_generate:n
\prop_if_in_p:cn
\token_case_charcode:NnTF
\box_new:N
\peek_meaning:NTF
\token_if_chardef:NT
\dim_compare:nNnT
\str_case:nvTF
\clist_gput_left:Nn
\regex_extract_once:nnNF
\exp_args:Nee
\vcoffin_set:cnn
\l_tmpa_int
\str_case:nV
\prop_put:coo
\str_set:Nn
\token_case_charcode:NnT
\str_greplace_once:cnn
\regex_gset:Nn
\l_char_special_seq
\tl_build_get:NN
\str_item_ignore_spaces:nn
\skip_eval:n
\tl_if_novalue:nT
\scan_new:N
\int_gset_eq:NN
\seq_if_exist:NTF
\c_parameter_token
\clist_set_from_seq:Nc
\bool_while_do:cn
\fp_compare_p:n
\dim_do_while:nNnn
\seq_set_split:NnV
\int_step_inline:nn
\int_to_base:nn
\c_catcode_other_space_tl
\clist_gpop:NNT
\bool_show:N
\str_if_in:cnT
\clist_gclear:N
\quark_if_no_value:cF
\tl_to_str:V
\box_gresize_to_ht_plus_dp:Nn
\box_gclip:c
\clist_item:cn
\hcoffin_gset:Nn
\char_str_uppercase:N
\file_parse_full_name:nNNN
\tl_if_eq:cnT
\str_if_eq:VnT
\cs_if_exist_use:NTF
\dim_gset:cn
\peek_meaning_ignore_spaces:NTF
\msg_none:nnxxx
\str_case:on
\bool_lazy_or:nnF
\use_ii:nn
\msg_gset:nnn
\token_if_mathchardef:NTF
\intarray_item:Nn
\seq_get_left:NNT
\msg_error:nnn
\l_tmpa_regex
\clist_pop:cNF
\fp_show:N
\box_set_trim:cnnnn
\box_gset_viewport:cnnnn
\box_if_horizontal_p:N
\coffin_gclear:c
\group_end:
\clist_greverse:N
\iow_new:N
\muskip_zero_new:c
\prg_break_point:Nn
\box_gclear_new:c
\msg_critical:nnnnn
\cs_gset_protected:cn
\exp_last_unbraced:Nfo
\str_gput_right:cn
\int_step_inline:nnn
\tl_if_eq:NnF
\file_timestamp:n
\seq_gpop_right:NNT
\sys_rand_seed:
\tl_put_left:cx
\keys_show:nn
\keys_set_known:nVnN
\iow_indent:n
\msg_error:nnxxxx
\clist_new:N
\vbox_gset_split_to_ht:cNn
\exp_last_unbraced:NNo
\debug_suspend:
\token_if_math_toggle_p:N
\token_if_other:NF
\c_empty_prop
\l_tmpa_fp
\coffin_clear:N
\tl_if_head_eq_meaning:nNT
\cctab_if_exist:NT
\str_gclear:c
\reverse_if:N
\intarray_gset_rand:Nnn
\str_if_eq:nvT
\seq_if_in:NnTF
\dim_zero:c
\exp_end_continue_f:w
\ior_str_get:NNT
\vcoffin_gset_end:
\text_lowercase:n
\muskip_show:N
\prop_get:NvNT
\msg_warning:nnx
\int_if_even:nTF
\msg_none:nnnn
\bool_xor_p:nn
\tl_if_in:VnT
\tl_case:Nn
\char_set_sfcode:nn
\quark_if_recursion_tail_stop:n
\seq_gpop_left:cNF
\msg_show_item:nn
\dim_gset_eq:Nc
\box_ht:N
\box_gset_eq:cc
\regex_extract_all:nnNF
\prop_count:N
\sys_if_engine_ptex:F
\tl_if_blank:nT
\fp_trap:nn
\dim_set_eq:cc
\dim_gset_eq:cN
\muskip_set_eq:NN
\keys_set_filter:nnVN
\seq_map_tokens:cn
\prop_if_in:cVF
\skip_set_eq:cc
\msg_expandable_error:nnfff
\int_step_function:nN
\token_if_skip_register:NF
\int_to_oct:n
\keys_set_groups:nno
\tl_range_braced:nnn
\tl_if_blank_p:V
\fparray_item_to_tl:Nn
\box_gresize_to_ht_plus_dp:cn
\group_insert_after:N
\cs_new_nopar:cpn
\c_str_cctab
\prop_gput:con
\box_if_vertical:cT
\fp_to_scientific:n
\tl_gset:co
\tl_gset:NV
\tl_if_single:nTF
\prop_get:NvNF
\bool_if_exist:NTF
\seq_put_right:cx
\exp_end_continue_f:nw
\int_zero:c
\token_if_toks_register:NT
\clist_if_empty_p:c
\g_tmpa_coffin
\iow_open:Nn
\bool_log:c
\token_if_int_register:NTF
\seq_if_in:NnT
\prop_gput:Nvx
\skip_if_eq:nnT
\tl_remove_once:cn
\hbox_gset_to_wd:Nnn
\peek_meaning_remove:NF
\cctab_gset:Nn
\token_if_alignment:NT
\token_if_active:NTF
\l_keys_key_str
\prop_put:cnV
\seq_gput_right:Nx
\skip_log:c
\tl_map_function:nN
\seq_gset_eq:cc
\seq_use:cn
\fp_if_nan_p:n
\prop_if_empty:NT
\clist_set:co
\peek_catcode_ignore_spaces:NT
\seq_use:cnnn
\intarray_gset_rand:Nn
\ior_get:NNTF
\tl_put_left:No
\seq_gpop_left:cNT
\cs_if_free:NTF
\keys_set_known:nnnN
\muskip_add:Nn
\l_tmpa_box
\tl_set:Nx
\tl_show:n
\seq_pop_right:cNF
\coffin_grotate:cn
\mode_if_vertical:T
\prop_gset_eq:cc
\clist_gsort:cn
\seq_push:Nv
\peek_regex_remove_once:nT
\tl_rand_item:N
\tl_gput_left:Nn
\tl_set:cn
\tl_if_empty_p:c
\tl_put_left:cn
\prop_pop:NnNT
\token_if_eq_catcode_p:NN
\cs_set_protected_nopar:Nn
\cs_gset_eq:Nc
\bool_do_until:nn
\msg_error:nnxx
\keys_set_known:nv
\str_case_e:nnT
\use_i_delimit_by_q_nil:nw
\coffin_show_structure:N
\fp_new:c
\g_msg_module_name_prop
\box_move_down:nn
\seq_gpush:co
\file_compare_timestamp:nNnTF
\clist_push:No
\token_if_parameter:NTF
\ior_open:NnT
\clist_gpush:cn
\coffin_mark_handle:cnnn
\q_recursion_tail
\sys_if_output_dvi:F
\file_input_stop:
\str_gput_left:cV
\box_gresize_to_wd_and_ht_plus_dp:Nnn
\str_put_right:cn
\tl_if_eq:cnTF
\dim_show:c
\token_if_alignment_p:N
\clist_remove_all:Nn
\bool_lazy_and:nnTF
\cs_set_nopar:cn
\tl_if_blank:nTF
\bool_set_eq:cc
\fp_use:c
\str_greplace_once:Nnn
\g_tmpb_ior
\skip_if_exist:cT
\seq_put_left:cv
\prop_map_function:NN
\clist_if_empty:NTF
\dim_step_variable:nnnNn
\str_if_exist:cTF
\token_if_mathchardef:NF
\str_put_right:cx
\clist_map_variable:nNn
\msg_none:nnxxxx
\prg_map_break:Nn
\tl_if_eq:NnT
\tl_count:N
\int_sub:Nn
\fp_if_exist:NF
\hbox_gset:cw
\clist_gpop:NNTF
\tl_trim_spaces:N
\int_set:cn
\str_log:N
\tl_gput_left:No
\file_get_hex_dump:nNF
\skip_set_eq:cN
\prop_show:N
\fp_do_until:nNnn
\int_step_variable:nnnNn
\clist_if_in:NnT
\ior_open:NnF
\peek_regex:NF
\tl_if_head_is_space:nF
\box_if_empty_p:N
\quark_if_nil:oT
\token_if_parameter_p:N
\vbox_gset:Nw
\clist_set:cx
\clist_gpop:NN
\box_autosize_to_wd_and_ht_plus_dp:cnn
\exp_args:NcV
\tl_gset_eq:Nc
\seq_get_left:cNF
\vbox_set_split_to_ht:NNn
\str_if_empty_p:N
\prop_map_tokens:Nn
\peek_charcode:NF
\ior_log_list:
\token_if_primitive:NT
\str_if_eq_p:nn
\clist_const:Nx
\tl_gset_eq:NN
\file_get_timestamp:nNT
\skip_add:Nn
\muskip_set_eq:Nc
\box_if_horizontal:cT
\int_if_exist_p:c
\quark_if_nil:nTF
\clist_map_variable:cNn
\seq_get:NN
\cs_if_exist_use:cT
\clist_if_exist_p:c
\intarray_log:c
\box_autosize_to_wd_and_ht:cnn
\clist_const:cn
\int_to_Alph:n
\box_if_vertical:NTF
\cs_set:cpn
\file_parse_full_name:VNNN
\c_zero_muskip
\seq_gpop_left:NNF
\clist_put_right:Nx
\prop_get:NoN
\str_put_left:cn
\seq_map_function:cN
\prop_clear_new:c
\tl_set_eq:cc
\cs_new_nopar:cx
\tl_head:f
\dim_abs:n
\exp_last_unbraced:Noo
\bool_set:Nn
\clist_put_left:cV
\seq_put_right:No
\tl_if_head_eq_catcode:nNF
\coffin_ht:c
\tl_if_empty:nT
\regex_extract_all:nnNT
\skip_gzero_new:N
\seq_gset_map_x:NNn
\muskip_if_exist:NTF
\int_sub:cn
\cs_new:Nn
\cs_if_free:cTF
\int_to_roman:n
\token_if_protected_long_macro:NTF
\seq_gset_eq:Nc
\str_put_left:Nn
\token_if_letter:NF
\bool_gset_true:N
\cs_set_nopar:Nn
\tl_rand_item:n
\char_show_value_sfcode:n
\dim_set_eq:Nc
\prop_if_in:NVT
\clist_if_in:NnF
\clist_get:NNTF
\hcoffin_set:Nn
\peek_regex_replace_once:nn
\tl_if_single:cTF
\dim_gzero_new:c
\ior_if_eof:NF
\str_tail:N
\tl_if_single:NTF
\bool_lazy_all:nF
\char_generate:nn
\tl_gput_right:cn
\l_text_case_exclude_arg_tl
\dim_do_until:nn
\prop_gset_from_keyval:Nn
\seq_gput_left:NV
\seq_push:co
\regex_split:nnNT
\intarray_show:c
\seq_pop_left:NNT
\msg_fatal:nnnn
\c_space_tl
\int_to_alph:n
\char_set_active_eq:NN
\exp_args:Nco
\bool_new:c
\prop_get:cnN
\clist_gpop:NNF
\if_mode_inner:
\regex_extract_once:nnNTF
\tl_map_tokens:cn
\if_meaning:w
\msg_error:nnnnnn
\tl_gput_right:co
\clist_gput_left:co
\box_rotate:cn
\char_to_nfd:N
\prop_gput:NVV
\msg_none:nnn
\str_lowercase:n
\str_map_inline:Nn
\tl_if_exist:cF
\msg_fatal_text:n
\cs_set_protected:Nn
\ior_map_break:
\token_case_catcode:NnF
\skip_sub:cn
\coffin_join:NnnNnnnn
\bool_set_eq:cN
\regex_extract_all:NnNTF
\sys_if_output_dvi_p:
\str_if_exist:cF
\str_if_eq_p:nV
\str_if_eq_p:no
\group_begin:
\clist_gput_right:No
\tl_range:Nnn
\prop_get:NoNT
\color_ensure_current:
\token_if_dim_register:NTF
\muskip_gset:Nn
\tl_set_rescan:cno
\skip_gset_eq:NN
\token_if_space_p:N
\ior_close:c
\file_if_exist:nTF
\str_if_in:NnT
\tl_trim_spaces_apply:nN
\prop_set_eq:Nc
\seq_if_in:NvT
\int_to_symbols:nnn
\msg_fatal:nn
\l_tmpb_tl
\cs_new:Nx
\box_if_exist:cTF
\l_tmpa_muskip
\int_gincr:c
\token_if_letter:NT
\exp_args:Nox
\exp_last_unbraced:NNf
\exp_not:e
\sys_if_shell_restricted_p:
\coffin_gset_vertical_pole:cnn
\seq_map_inline:Nn
\vbox_unpack_drop:c
\seq_greverse:c
\str_if_eq:ccT
\exp_args:NNVV
\cctab_begin:N
\token_if_primitive_p:N
\msg_warning:nnxxx
\box_gclip:N
\peek_catcode_ignore_spaces:NTF
\peek_meaning_remove_ignore_spaces:NF
\clist_if_in:NoF
\coffin_rotate:Nn
\fp_show:n
\skip_zero:c
\l_tmpa_seq
\keys_if_choice_exist_p:nnn
\l_tmpb_box
\tl_const:cx
\int_gdecr:c
\iow_shipout_x:cx
\sys_if_engine_pdftex:T
\msg_info:nnx
\clist_remove_duplicates:c
\use_i_delimit_by_q_recursion_stop:nw
\char_set_catcode_group_begin:N
\tl_head:n
\token_if_alignment:NF
\cs_if_exist:cTF
\tl_build_begin:N
\bool_case_true:nT
\seq_get:cNTF
\int_log:n
\msg_if_exist:nnF
\str_if_eq:cNT
\seq_map_variable:NNn
\prop_get:NVNTF
\quark_if_no_value:cTF
\dim_const:Nn
\exp_args:NNc
\tl_if_eq:NNT
\g_tmpb_str
\tl_analysis_show:n
\use:nn
\token_if_protected_long_macro:NF
\regex_split:nnNF
\vbox_set_split_to_ht:ccn
\fp_gsub:cn
\fp_to_int:n
\cs_meaning:c
\int_gset:cn
\char_set_catcode_invalid:n
\str_gset:cn
\exp_last_unbraced:NcV
\str_map_break:
\token_if_dim_register:NT
\box_resize_to_wd_and_ht_plus_dp:cnn
\vbox_gset_to_ht:Nnw
\exp_args:NNnV
\tl_const:Nx
\flag_if_exist:nF
\char_set_catcode_space:n
\clist_clear_new:N
\exp_args:Nffo
\token_if_int_register:NT
\prop_map_break:n
\tl_gremove_all:cn
\quark_if_nil:VT
\clist_gpop:cNT
\seq_gpop_right:NNTF
\use_ii:nnnn
\seq_set_split:Nnn
\msg_info:nn
\sys_if_output_dvi:TF
\tl_if_empty:nTF
\regex_split:NnNF
\coffin_log_structure:N
\int_compare_p:nNn
\cs_new_protected:cpn
\regex_extract_once:NnN
\tl_if_empty_p:o
\tl_build_put_left:Nn
\token_if_letter:NTF
\clist_if_empty:nTF
\cs_gset_nopar:Npx
\exp_last_unbraced:NNV
\cs_new_protected_nopar:cn
\tl_if_empty:VTF
\fp_if_nan:nF
\bool_if_exist:cTF
\seq_if_in:NVF
\g_tmpb_iow
\coffin_wd:N
\exp_last_unbraced:NNNV
\str_foldcase:n
\token_if_mathchardef:NT
\cs_new_nopar:cpx
\int_gset_eq:cN
\regex_replace_once:NnNTF
\coffin_join:cnnNnnnn
\int_div_truncate:nn
\tl_if_blank:oTF
\exp_args:NcNo
\box_gautosize_to_wd_and_ht_plus_dp:cnn
\tl_gset:cn
\prop_gset_from_keyval:cn
\seq_pop_left:cNTF
\clist_gpush:Nn
\tl_map_tokens:nn
\seq_get:cNF
\tl_new:c
\iow_open:cn
\bool_xor:nnT
\peek_remove_spaces:n
\iow_char:N
\tl_if_head_eq_catcode:nNTF
\seq_pop:NNTF
\str_gset:cx
\tl_if_exist:cT
\cs_new_protected_nopar:cpx
\tl_gset:cv
\seq_set_eq:Nc
\msg_term:nnnnnn
\prop_count:c
\keys_set:no
\str_gremove_once:cn
\str_case:nVTF
\char_gset_active_eq:nN
\cs_set:Nn
\clist_set:cV
\box_gautosize_to_wd_and_ht_plus_dp:Nnn
\clist_if_empty:cT
\regex_extract_all:NnNF
\prop_if_in:cVT
\dim_if_exist_p:N
\cs_gset:Npn
\vbox_to_zero:n
\sys_if_engine_uptex:T
\exp_args:Nof
\file_get_mdfive_hash:nNT
\vbox_set_split_to_ht:Ncn
\seq_put_left:cx
\seq_log:c
\tl_put_right:Nx
\int_log:c
\bool_case_false:n
\cs_gset:Nn
\token_case_meaning:NnT
\tl_put_right:Nn
\muskip_gzero_new:c
\regex_replace_all:NnN
\box_show:c
\fp_to_decimal:c
\tl_to_str:n
\int_while_do:nNnn
\fp_add:Nn
\tl_if_head_eq_charcode_p:fN
\msg_critical:nnn
\dim_gsub:Nn
\msg_fatal:nnnnnn
\char_set_catcode_end_line:N
\seq_put_right:cV
\tl_tail:v
\tl_gset_rescan:Nno
\fp_zero:c
\str_head_ignore_spaces:n
\iow_term:n
\token_if_space:NT
\c_underscore_str
\skip_gzero:c
\clist_if_empty_p:N
\clist_map_function:nN
\seq_greverse:N
\token_if_expandable_p:N
\c_one_degree_fp
\msg_fatal:nnxx
\prop_if_empty:cTF
\cs_set_protected_nopar:cn
\seq_gpush:NV
\fp_gset:cn
\prop_gput:Nnx
\msg_show:nnxx
\seq_map_break:n
\coffin_if_exist:NF
\fparray_item:Nn
\clist_gset_from_seq:cc
\c_dollar_str
\cs_generate_from_arg_count:NNnn
\fp_until_do:nn
\str_show:n
\file_log_list:
\dim_add:Nn
\prop_put:Nnn
\clist_gpop:cN
\coffin_ht:N
\use_none:nnnnn
\str_case:onF
\c_percent_str
\bool_set_false:c
\bool_gset_inverse:c
\box_ht:c
\msg_log:nnnn
\hbox_set:cn
\sys_get_shell:nnNF
\tl_if_blank_p:n
\fp_step_variable:nnnNn
\box_show:Nnn
\seq_gset_eq:NN
\msg_show_item_unbraced:nn
\l_keys_choice_int
\peek_gafter:Nw
\clist_const:Nn
\c_ampersand_str
\exp_args:NNV
\seq_item:cn
\box_set_eq:Nc
\str_show:N
\prop_pop:NoN
\prop_gremove:Nn
\bool_set:cn
\seq_gsort:Nn
\int_step_inline:nnnn
\peek_catcode_ignore_spaces:NF
\regex_match:nnTF
\exp_args:NNcf
\str_gput_left:NV
\clist_put_left:NV
\str_if_eq:VVTF
\exp_args:Nne
\muskip_gset:cn
\clist_set:NV
\muskip_sub:Nn
\seq_gclear:N
\token_if_active:NF
\iow_log:x
\use_none_delimit_by_q_stop:w
\hcoffin_gset:Nw
\seq_if_exist:cTF
\char_set_mathcode:nn
\prop_gpop:NnNF
\tl_replace_once:cnn
\peek_after:Nw
\token_if_eq_catcode:NNF
\str_gset_convert:NnnnF
\cs_show:N
\peek_regex_replace_once:NnTF
\str_set_eq:cc
\int_set_eq:cN
\fp_to_scientific:c
\fparray_gset:Nnn
\file_get_full_name:nNF
\seq_get_right:cNTF
\tl_if_empty_p:V
\exp_args:Nfo
\vbox_set_top:Nn
\str_count:N
\tl_if_blank:eT
\bool_lazy_any_p:n
\str_range:Nnn
\file_get_size:nNTF
\file_get_mdfive_hash:nNTF
\use:c
\box_if_empty:NT
\regex_match:NnTF
\cs_gset:cpn
\cs_show:c
\iow_show_list:
\box_set_eq:NN
\tl_if_head_eq_meaning:nNF
\sys_shell_now:x
\fp_do_while:nn
\msg_error:nnx
\flag_if_exist:nT
\c_space_token
\if_charcode:w
\coffin_gjoin:cnnNnnnn
\prop_if_in:cnTF
\tl_put_right:cx
\prop_pop:coN
\token_if_protected_long_macro:NT
\token_if_toks_register_p:N
\cctab_new:N
\box_resize_to_wd:Nn
\bool_lazy_all:nT
\cs_new_eq:cc
\str_if_eq:nnTF
\bool_lazy_all_p:n
\clist_pop:NN
\fp_zero_new:N
\str_gput_left:Nn
\coffin_typeset:Nnnnn
\bool_gset_true:c
\int_from_oct:n
\intarray_gzero:c
\char_gset_active_eq:Nc
\g_file_curr_name_str
\token_if_eq_charcode:NNT
\fp_if_exist_p:c
\seq_if_in:NxF
\g_file_curr_dir_str
\msg_critical:nnxxxx
\clist_if_in:nVF
\str_gconcat:ccc
\cs_set_eq:Nc
\c_max_char_int
\dim_case:nn
\prop_put:Non
\prop_get:cVNF
\tl_count_tokens:n
\clist_gremove_duplicates:c
\msg_none:nnxx
\exp_args:Nno
\muskip_gset_eq:cN
\char_set_catcode_escape:N
\prop_if_in_p:Nn
\cs_if_free_p:N
\seq_if_in:cnT
\box_set_dp:Nn
\exp_args:Ncf
\exp_args:Nnnx
\token_if_toks_register:NTF
\mode_if_horizontal:F
\mode_if_vertical:F
\tl_gset:cf
\char_value_lccode:n
\msg_info:nnnnnn
\msg_log:nn
\tl_gremove_all:Nn
\muskip_gzero:c
\hbox_overlap_right:n
\tl_map_variable:nNn
\dim_const:cn
\if_catcode:w
\c_pi_fp
\quark_if_recursion_tail_stop_do:on
\fp_gset:Nn
\box_clear:N
\seq_get:cN
\str_set_convert:NnnnT
\intarray_rand_item:c
\clist_map_inline:nn
\clist_gsort:Nn
\vbox_gset_top:Nn
\prop_gput:cnn
\prop_put:Nvx
\str_if_eq_p:nv
\file_get_size:nNT
\seq_gpop_right:cNTF
\cs_set:cn
\cs_set_protected:cn
\bool_not_p:n
\prop_gput:NnV
\g_tmpb_int
\token_if_font_selection:NT
\bool_case_false:nT
\exp_args:Ncno
\seq_new:N
\dim_gadd:Nn
\tl_sort:Nn
\exp_last_unbraced:Nf
\char_set_catcode_group_end:n
\intarray_gset_rand:cn
\tl_range_unbraced:cnn
\skip_if_finite:nTF
\c_sys_backend_str
\clist_if_in:nnT
\cs_new_protected:Npx
\cs_set:cpx
\msg_warning:nnxxxx
\tl_gput_right:cx
\c_math_subscript_token
\prop_get:NnNF
\clist_gpush:Nx
\box_use_drop:c
\box_gset_eq_drop:NN
\vcoffin_gset:Nnn
\coffin_log_structure:c
\hbox_gset_end:
\tl_if_empty:oT
\fp_to_dim:c
\coffin_resize:cnn
\sys_if_shell:F
\bool_if:nF
\cs_to_str:N
\exp:w
\int_set_eq:cc
\peek_N_type:F
\mode_if_math:T
\tl_if_head_eq_catcode:nNT
\c_code_cctab
\hbox_set_to_wd:cnn
\prop_remove:Nn
\prop_gput:Nno
\seq_gset_from_clist:NN
\tl_if_head_is_N_type:nTF
\tl_gset_rescan:cno
\tl_if_exist:cTF
\str_count_spaces:N
\muskip_const:Nn
\c_left_brace_str
\seq_pop_right:NNTF
\peek_charcode_remove_ignore_spaces:NF
\msg_if_exist_p:nn
\cs_gset_protected:Nx
\clist_if_in:NVTF
\tl_concat:NNN
\tl_if_in:VnF
\bool_if:cTF
\peek_meaning:NF
\int_to_bin:n
\tl_if_head_is_group:nT
\muskip_zero:c
\vbox_set_end:
\fp_step_function:nnnc
\prg_set_eq_conditional:NNn
\exp_last_unbraced:Nv
\tl_if_single:NT
\use_iii:nnn
\peek_regex_replace_once:Nn
\g_tmpb_muskip
\exp_args:NNnx
\tl_if_head_eq_catcode:oNTF
\msg_error:nnnnn
\char_titlecase:N
\int_show:N
\box_if_horizontal:NTF
\cs_set_nopar:Nx
\regex_replace_all:nnNT
\clist_put_right:cn
\tl_if_in:NnF
\bool_lazy_and:nnT
\skip_gadd:Nn
\char_lowercase:N
\cs_if_free:NF
\regex_extract_once:nnN
\fp_if_exist:cTF
\coffin_rotate:cn
\str_count_spaces:n
\text_uppercase:n
\vbox_gset_top:cn
\c_zero_skip
\file_if_exist_input:n
\hcoffin_gset:cw
\seq_if_exist:cF
\clist_gremove_duplicates:N
\skip_if_eq:nnTF
\peek_regex_remove_once:NT
\clist_put_left:Nn
\skip_horizontal:c
\box_resize_to_ht_plus_dp:Nn
\skip_if_exist:NT
\tl_if_head_eq_meaning:nNTF
\regex_match:nnT
\clist_pop:cNTF
\bool_lazy_any:nF
\clist_gset:cx
\int_gzero_new:c
\msg_term:nnxx
\tl_log:N
\str_map_variable:NNn
\tl_if_blank:nF
\str_if_eq:eeT
\str_if_eq:ccTF
\peek_regex:NTF
\cs_set_eq:cN
\exp_args:Nnc
\tl_const:Nn
\tl_if_single_token:nT
\g_tmpb_seq
\token_if_alignment:NTF
\token_if_protected_macro:NT
\prop_get:NvNTF
\file_get_full_name:VN
\prop_gset_eq:NN
\prop_get:coNT
\seq_get:cNT
\keys_set_known:nVN
\dim_step_inline:nnnn
\str_if_in:NnF
\seq_if_in:NVT
\tl_if_eq:cnF
\clist_if_in:noT
\lua_escape:n
\int_step_variable:nNn
\prop_gclear_new:N
\sys_if_engine_xetex_p:
\token_if_muskip_register:NTF
\clist_map_inline:Nn
\hcoffin_set:cn
\bool_lazy_any:nT
\clist_clear:N
\str_map_variable:nNn
\prg_set_protected_conditional:Npnn
\bool_lazy_all:nTF
\use_none:nnnnnnnnn
\seq_show:N
\tl_build_gput_left:Nx
\str_gset_eq:cN
\g_tmpa_bool
\clist_gput_left:cV
\tl_if_head_eq_meaning_p:nN
\seq_gput_left:Nx
\regex_split:nnNTF
\cctab_if_exist:NTF
\mode_leave_vertical:
\tl_set:Nv
\tl_if_empty:VT
\int_from_hex:n
\exp_args:Nccc
\prop_put:NVV
\c_empty_coffin
\seq_remove_all:Nn
\prop_put:NnV
\prop_if_empty:NF
\tl_rescan:nn
\tl_if_eq:ccT
\regex_replace_once:NnNF
\seq_if_empty:NT
\prop_gput:cVn
\mode_if_math:F
\cs_set_nopar:cpx
\dim_gadd:cn
\skip_if_exist:NF
\hbox_unpack_drop:c
\char_set_catcode_math_toggle:N
\seq_gremove_all:Nn
\muskip_show:n
\text_uppercase:nn
\dim_gzero:N
\clist_count:N
\cs_gset_protected_nopar:cpn
\prop_put:con
\dim_if_exist:cF
\cs_new:Npn
\str_if_empty:cF
\token_if_font_selection:NF
\vbox_unpack:N
\c_zero_dim
\tl_gput_right:NV
\c_math_toggle_token
\regex_match:NnT
\bool_gset_eq:cN
\box_log:Nnn
\clist_gset:Nn
\sys_if_shell_unrestricted:TF
\cs_set_protected_nopar:cpn
\c_sys_day_int
\tl_if_head_is_group_p:n
\tl_case:cnT
\c_one_fp
\keys_set_known:nonN
\prop_put:Nxx
\str_if_eq:ccF
\sys_if_rand_exist:T
\tl_set:Nn
\char_set_catcode:nn
\exp_not:N
\prop_if_exist:cT
\coffin_gscale:Nnn
\token_if_primitive:NTF
\exp_last_two_unbraced:Noo
\debug_on:n
\msg_show:nnnnn
\coffin_gset_eq:NN
\file_get_timestamp:nNF
\box_move_up:nn
\skip_sub:Nn
\exp_args:NnV
\file_get_mdfive_hash:nN
\tl_if_head_is_N_type:nT
\seq_count:c
\seq_rand_item:c
\peek_catcode_remove:NTF
\text_expand:n
\clist_if_in:cnTF
\str_case:nVT
\prop_remove:NV
\tl_log:c
\clist_push:co
\coffin_attach:cnnNnnnn
\cs_set_protected_nopar:cx
\tl_sort:nN
\muskip_eval:n
\quark_if_no_value:NF
\keys_if_exist:nnT
\clist_concat:NNN
\tl_analysis_show:N
\coffin_attach:cnncnnnn
\flag_new:n
\int_if_exist:cT
\str_gput_right:cV
\cs_set_protected_nopar:Nx
\token_if_long_macro:NTF
\ior_open:cn
\sys_if_rand_exist_p:
\bool_show:c
\tl_if_novalue:nF
\clist_clear_new:c
\tl_if_single_token:nTF
\clist_gset:Nx
\peek_catcode:NT
\regex_replace_all:nnN
\tl_gclear:N
\tl_gput_left:NV
\str_set:NV
\box_gscale:Nnn
\use_ii_i:nn
\seq_set_from_clist:cc
\fp_max:nn
\cs_set_nopar:Npx
\c_max_muskip
\seq_set_from_function:NnN
\g_tmpb_dim
\fp_set_eq:cc
\cs_gset:cn
\sys_if_engine_luatex:T
\cs_gset_protected:Npx
\seq_put_right:co
\box_gset_wd:Nn
\bool_set_eq:NN
\dim_compare:nTF
\tl_trim_spaces_apply:oN
\seq_pop_left:NNTF
\fp_set:Nn
\regex_split:nnN
\keys_set_filter:nnvN
\prop_if_in:cnF
\cs_set:Nx
\file_get_size:nNF
\cs_gset_protected_nopar:cn
\mode_if_vertical:TF
\int_new:N
\msg_term:nnxxxx
\clist_get:cNF
\str_log:c
\clist_if_empty:NF
\hbox_gset:cn
\str_remove_all:cn
\iow_term:x
\seq_pop_left:cNT
\box_set_to_last:N
\box_gclear:N
\msg_none:nn
\msg_fatal:nnxxxx
\tl_if_eq:NcF
\cctab_if_exist:cF
\use:x
\use_none:nnnnnnn
\int_step_function:nnnN
\char_gset_active_eq:nc
\hbox_set_end:
\hbox_to_zero:n
\flag_raise_if_clear:n
\int_rand:n
\str_gset_eq:cc
\g_tmpa_clist
\seq_mapthread_function:ccN
\keys_set:nn
\tl_if_head_eq_charcode_p:nN
\tl_range_braced:Nnn
\ProvidesExplPackage
\mode_if_horizontal:TF
\char_foldcase:N
\box_resize_to_ht_plus_dp:cn
\seq_pop:cNT
\clist_gput_right:Nn
\group_align_safe_end:
\clist_set_eq:NN
\box_grotate:cn
\cctab_begin:c
\seq_if_in:NxTF
\seq_gpush:cx
\keys_set_groups:nnn
\bool_const:Nn
\prop_log:c
\c_sys_engine_format_str
\coffin_gattach:cnncnnnn
\clist_put_left:Nx
\l_tmpb_dim
\char_set_catcode_parameter:N
\c_sys_hour_int
\token_if_macro:NF
\str_gset:NV
\tl_if_single_token_p:n
\seq_gput_left:cv
\clist_gpop:cNF
\peek_catcode_remove:NF
\skip_if_eq_p:nn
\str_item:nn
\box_gclear:c
\bool_if:cF
\tl_gset:Nx
\seq_gpush:cV
\cs_gset_protected:Npn
\token_if_dim_register:NF
\seq_push:Nx
\c_empty_box
\box_if_empty:cF
\iow_newline:
\str_gput_right:NV
\tl_if_head_eq_charcode:fNF
\clist_if_empty:NT
\iow_now:cn
\seq_if_in:NoT
\fp_to_int:N
\cs_meaning:N
\token_if_protected_long_macro_p:N
\char_str_lowercase:N
\l_char_active_seq
\token_if_protected_macro_p:N
\tl_sort:cn
\token_if_math_toggle:NT
\prop_put:NVx
\str_case:VnF
\int_do_while:nNnn
\lua_now:n
\clist_item:nn
\prg_break:n
\int_use:N
\vbox_gset:cn
\l_tmpb_fp
\peek_analysis_map_break:
\msg_log:nnxxxx
\file_get_hex_dump:nnnNF
\clist_if_in:NVT
\muskip_if_exist_p:c
\dim_gset_eq:NN
\fp_compare_p:nNn
\cs_new:cx
\seq_push:cx
\lua_shipout_e:n
\clist_gpush:No
\l_tmpa_bool
\str_clear:c
\tl_if_single:nF
\seq_push:NV
\box_gset_to_last:N
\prop_get:coN
\prop_get:cVN
\seq_get_left:NN
\seq_sort:cn
\if_mode_vertical:
\iow_wrap:nnnN
\muskip_gsub:Nn
\fp_do_until:nn
\msg_warning_text:n
\str_if_eq_p:Vn
\cs_set:cx
\seq_map_inline:cn
\q_mark
\cs_if_eq:NNT
\fp_sub:Nn
\int_incr:c
\fp_new:N
\cs_new_nopar:Nx
\tl_if_head_eq_charcode:nNTF
\seq_if_in:NoTF
\muskip_add:cn
\msg_none:nnnnnn
\sys_if_platform_windows:F
\clist_use:Nn
\bool_case_false:nF
\int_compare:nTF
\l_iow_line_count_int
\cs_gset:cx
\int_value:w
\muskip_gadd:Nn
\box_set_ht:Nn
\prop_if_in:NoTF
\skip_set:Nn
\tl_range_braced:cnn
\clist_put_right:NV
\seq_clear:c
\box_clip:c
\seq_set_from_clist:Nn
\str_if_eq:VVT
\tl_put_left:Nn
\prop_gput:cVV
\seq_push:cv
\g_tmpa_str
\char_uppercase:N
\cs_gset:cpx
\seq_map_indexed_inline:Nn
\cs_new_protected:cx
\exp_last_unbraced:NNNo
\regex_extract_once:nnNT
\fp_zero_new:c
\prop_get:cvNT
\str_remove_once:cn
\seq_gpop_left:NNT
\prop_gput:Non
\str_count_spaces:c
\tl_head:w
\msg_log:nnx
\skip_zero_new:c
\quark_if_recursion_tail_stop_do:Nn
\tl_gtrim_spaces:c
\tl_put_left:Nx
\seq_if_exist_p:N
\box_gresize_to_wd_and_ht:cnn
\c_tilde_str
\sys_if_engine_ptex_p:
\quark_if_no_value_p:N
\sys_if_engine_xetex:TF
\text_declare_purify_equivalent:Nx
\tl_gset_rescan:Nnx
\clist_if_exist:cT
\int_gset:Nn
\token_if_eq_meaning_p:NN
\char_set_active_eq:nN
\int_gadd:Nn
\fp_add:cn
\bool_gset:Nn
\box_if_empty:NTF
\msg_info:nnn
\keys_set_filter:nnnnN
\bool_if:NT
\regex_split:NnNTF
\sys_load_backend:n
\str_if_eq:eeF
\keys_log:nn
\token_if_protected_macro:NTF
\prop_if_empty:cT
\c_true_bool
\else:
\coffin_if_exist:NT
\flag_if_exist_p:n
\tl_if_single_p:c
\keys_set_known:noN
\str_if_eq:noF
\str_if_eq:VnF
\tl_put_right:cV
\msg_fatal:nnn
\clist_pop:cN
\clist_gpop:cNTF
\char_set_catcode_letter:n
\int_to_Base:nn
\token_if_math_subscript:NF
\tl_if_blank:oT
\hcoffin_set:Nw
\seq_gshuffle:N
\c_sys_month_int
\if_int_compare:w
\clist_if_in:nVT
\tl_if_single:NF
\peek_meaning_remove_ignore_spaces:NT
\muskip_gsub:cn
\char_set_catcode_math_subscript:N
\fp_if_exist:NT
\cs_set_protected:cx
\prop_if_in:coTF
\prop_gput:Nxx
\file_get:nnNT
\msg_error:nn
\tl_set:cf
\fp_do_while:nNnn
\str_head:N
\tl_if_eq:NNTF
\iow_wrap:nxnN
\mode_if_horizontal_p:
\exp_args:Nv
\coffin_resize:Nnn
\quark_if_no_value:cT
\exp_args:NNNo
\cs_prefix_spec:N
\tl_set_eq:cN
\str_map_break:n
\cs_set_nopar:cpn
\tl_gsort:Nn
\token_case_charcode:Nn
\str_foldcase:V
\prop_pop:cnN
\dim_do_while:nn
\box_gclear_new:N
\peek_N_type:T
\token_case_meaning:NnTF
\c_minus_inf_fp
\tl_if_in:noTF
\box_gresize_to_wd_and_ht_plus_dp:cnn
\l_tmpa_coffin
\c_sys_platform_str
\tl_count:V
\flag_log:n
\exp_args:NcnV
\seq_get:NNF
\exp_args:Ncoo
\c_zero_int
\hbox_gset_to_wd:cnn
\str_replace_all:Nnn
\int_gdecr:N
\regex_replace_all:NnNT
\tl_if_blank:VT
\seq_gpop_left:cNTF
\msg_info:nnxxx
\g_tmpa_fp
\fparray_count:N
\intarray_rand_item:N
\prop_if_exist:NT
\skip_gsub:Nn
\clist_if_exist:NTF
\peek_meaning_remove:NT
\clist_push:cV
\muskip_set_eq:cN
\ior_str_get:NNTF
\dim_min:nn
\box_show:cnn
\prop_get:NvN
\exp_last_unbraced:Nco
\str_if_empty:NF
\peek_catcode_collect_inline:Nn
\prop_if_in:NVF
\str_put_right:Nn
\box_gset_eq_drop:cN
\box_autosize_to_wd_and_ht:Nnn
\prop_if_in:NnTF
\peek_charcode_remove:NTF
\tl_put_right:co
\exp_args:Nnox
\keys_set_known:nvnN
\str_if_in:NnTF
\dim_eval:n
\clist_put_right:Nn
\seq_gput_right:Nn
\or:
\str_if_eq:cNTF
\clist_if_in:nnF
\prop_if_in:cVTF
\msg_show:nnnn
\skip_show:c
\vbox_set_to_ht:Nnn
\bool_if_exist:NT
\seq_gremove_duplicates:N
\cs_gset_protected:cpx
\coffin_set_horizontal_pole:cnn
\box_set_eq_drop:cc
\str_case:nvF
\cs_if_eq:NNF
\cs_set_protected:Npx
\seq_put_right:NV
\tl_tail:f
\msg_show:nnnnnn
\tl_build_put_right:Nn
\str_if_empty:cTF
\str_gremove_once:Nn
\msg_fatal:nnxxx
\tl_if_blank_p:e
\seq_gset_from_clist:cN
\seq_put_left:Nx
\use_i:nn
\quark_if_nil:NF
\l_text_letterlike_tl
\clist_push:cx
\seq_get_right:NN
\legacy_if:nTF
\cs_set:Npn
\msg_error:nnnn
\tl_gset_eq:cc
\tl_head:v
\seq_clear:N
\seq_set_from_clist:NN
\tl_greverse:c
\seq_gpop:NNF
\prop_gremove:NV
\int_to_Hex:n
\regex_extract_once:NnNTF
\dim_step_function:nnnN
\msg_expandable_error:nnnn
\str_if_eq:onTF
\clist_gpush:cV
\token_if_int_register:NF
\bool_while_do:Nn
\int_decr:N
\clist_set_eq:Nc
\tl_if_in:onT
\coffin_show_structure:c
\regex_replace_once:nnN
\seq_reverse:c
\seq_gset_from_function:NnN
\msg_line_number:
\clist_get:cN
\use_i_ii:nnn
\str_set:cV
\vbox_set:Nw
\seq_get_left:NNTF
\keys_set_filter:nnV
\muskip_if_exist:cF
\seq_gput_left:co
\prop_get:cnNF
\box_log:cnn
\use_iv:nnnn
\c_minus_zero_fp
\cs_generate_variant:Nn
\seq_pop_right:NN
\peek_regex_replace_once:nnTF
\tl_gclear:c
\l_tmpb_bool
\prop_put_if_new:cnn
\bool_if_exist:cT
\tl_item:Nn
\intarray_new:cn
\fp_eval:n
\lua_escape:e
\vbox:n
\msg_if_exist:nnTF
\tl_case:cn
\peek_catcode_remove_ignore_spaces:NT
\clist_gput_left:Nx
\file_get_full_name:VNTF
\box_gset_dp:cn
\tl_const:cn
\tl_gput_right:No
\fp_compare:nF
\dim_case:nnTF
\seq_if_in:coF
\clist_if_in:cVTF
\l_file_search_path_seq
\str_if_eq:nnF
\tl_map_inline:cn
\prop_pop:cnNF
\dim_case:nnT
\int_mod:nn
\tl_if_head_eq_charcode:nNF
\msg_term:nnnn
\int_zero_new:c
\prop_rand_key_value:N
\exp_not:c
\regex_extract_all:NnN
\muskip_show:c
\seq_if_empty_p:c
\clist_if_empty:cTF
\clist_if_exist:NT
\tl_map_inline:nn
\int_if_odd_p:n
\seq_pop:NN
\regex_count:NnN
\fp_gzero:N
\seq_gput_left:Nv
\file_full_name:V
\tl_gput_left:cn
\tl_range_unbraced:Nnn
\bool_if_p:c
\str_const:Nx
\str_item:Nn
\text_declare_expand_equivalent:Nn
\tl_if_in:NnT
\vbox_set:cw
\int_zero_new:N
\exp_args:Nx
\c_catcode_active_space_tl
\bool_xor:nnTF
\cs_new_nopar:Nn
\peek_catcode_remove:NT
\coffin_gset_eq:Nc
\sys_if_shell_p:
\str_if_eq_p:cN
\tl_gremove_once:cn
\msg_critical:nnxx
\file_show_list:
\fp_if_nan:nT
\str_put_left:NV
\seq_if_in:coT
\hbox:n
\tl_gset_rescan:cnn
\file_get:nnN
\cs_gset_protected_nopar:Nx
\str_replace_all:cnn
\str_count_ignore_spaces:n
\clist_gset_from_seq:Nc
\dim_if_exist:cTF
\file_get_full_name:nN
\tl_if_eq:cNT
\sys_if_engine_pdftex_p:
\clist_get:NNT
\clist_gclear:c
\str_lowercase:f
\str_show:c
\quark_if_no_value:NT
\token_to_meaning:c
\fp_compare:nNnTF
\cs_gset_protected:cpn
\seq_mapthread_function:NNN
\msg_none:nnx
\str_set:cn
\skip_gset_eq:cN
\box_wd:N
\cs_new_protected_nopar:cpn
\cs_if_exist_use:NT
\cctab_end:
\sys_if_platform_windows:T
\int_gset_eq:Nc
\fp_min:nn
\clist_put_right:cx
\exp_args:Nc
\box_gset_trim:Nnnnn
\str_const:cx
\cctab_if_exist_p:N
\exp_last_unbraced:Ne
\clist_set:Nx
\coffin_gjoin:NnnNnnnn
\tl_if_eq:nnTF
\peek_regex_replace_once:nnF
\int_add:cn
\clist_if_in:nnTF
\clist_map_variable:NNn
\keys_set_known:nn
\tl_if_blank:eF
\tl_if_exist:NT
\seq_if_in:cxF
\tl_if_in:NnTF
\peek_charcode_ignore_spaces:NT
\tl_if_eq:cNF
\fp_to_scientific:N
\muskip_if_exist_p:N
\cs_if_exist:cT
\seq_get_left:NNF
\tl_if_empty_p:n
\g_tmpb_clist
\coffin_gset_eq:cc
\seq_gpop_left:NNTF
\prop_get:NVN
\dim_compare:nF
\peek_meaning_ignore_spaces:NF
\c_sys_shell_escape_int
\ior_str_get:NN
\quark_if_nil:oF
\exp_args:NNNx
\intarray_item:cn
\tl_greplace_once:Nnn
\str_gset:cV
\cctab_if_exist:NF
\cs_if_exist:NT
\regex_show:n
\box_resize_to_wd:cn
\seq_if_empty:cF
\g_tmpb_box
\ior_new:c
\prg_new_protected_conditional:Nnn
\seq_get:NNTF
\tl_build_put_left:Nx
\g_tmpa_iow
\prg_new_conditional:Nnn
\exp_args:Nnv
\tl_if_head_is_N_type_p:n
\fp_sign:n
\tl_build_gclear:N
\coffin_gattach:Nnncnnnn
\seq_gpop_right:NNF
\tl_case:cnTF
\seq_if_in:NvF
\bool_if_p:n
\vbox_gset_split_to_ht:NNn
\exp_args:NNe
\int_if_odd:nT
\exp_args:Nooo
\file_get_mdfive_hash:nNF
\prop_gpop:cnNTF
\tl_if_head_eq_catcode:oNF
\int_to_Roman:n
\char_set_active_eq:Nc
\clist_rand_item:c
\tl_set_rescan:cnn
\g_tmpb_regex
\seq_gput_right:cx
\clist_gset_eq:Nc
\str_if_eq:nVT
\tl_use:N
\str_replace_once:Nnn
\bool_lazy_or:nnT
\int_log:N
\keys_if_exist:nnF
\clist_if_exist_p:N
\tl_if_eq:ccF
\quark_if_no_value:NTF
\char_set_active_eq:nc
\box_scale:Nnn
\clist_set:cn
\seq_put_right:Nn
\tl_head:N
\c_group_begin_token
\int_incr:N
\seq_shuffle:N
\regex_replace_all:nnNF
\exp_last_unbraced:NNNNo
\cctab_const:Nn
\seq_pop_left:cN
\box_gscale:cnn
\prop_gput:Nnn
\char_show_value_uccode:n
\str_use:N
\hbox_unpack:N
\clist_if_in:NnTF
\vbox_set_to_ht:Nnw
\seq_gset_from_clist:Nn
\msg_critical:nnx
\seq_gpush:Nx
\seq_gclear_new:N
\str_gput_left:Nx
\hcoffin_set:cw
\tl_set:NV
\box_clear_new:c
\quark_if_nil:VF
\g_tmpa_tl
\str_gset_eq:Nc
\exp_args:Nnff
\sys_finalise:
\token_if_eq_meaning:NNTF
\msg_info_text:n
\bool_do_until:Nn
\int_gsub:Nn
\token_if_chardef_p:N
\str_set:Nx
\str_clear_new:N
\bool_until_do:Nn
\prop_get:cvN
\use_iii:nnnn
\keys_if_exist:nnTF
\use_none:nnnnnnnn
\tl_case:NnTF
\tl_map_function:cN
\clist_if_exist:cF
\prop_get:cVNTF
\bool_if:nTF
\clist_gset_eq:cc
\prop_if_in:NVTF
\clist_reverse:c
\tl_build_end:N
\seq_set_filter:NNn
\token_if_eq_meaning:NNT
\ior_get:NNF
\seq_if_empty_p:N
\l_tmpb_muskip
\token_if_cs:NF
\clist_pop:cNT
\file_get_hex_dump:nNT
\box_if_horizontal:cF
\fp_while_do:nNnn
\keyval_parse:NNn
\use_none:nnnn
\c_sys_jobname_str
\seq_gset_from_clist:Nc
\prg_do_nothing:
\cs_set_eq:cc
\seq_const_from_clist:cn
\q_stop
\sys_if_engine_uptex:TF
\seq_pop:NNF
\file_mdfive_hash:n
\intarray_count:c
\peek_catcode:NTF
\seq_pop:NNT
\char_value_uccode:n
\str_if_eq:onF
\clist_gclear_new:c
\seq_get_right:cNF
\color_group_begin:
\int_gzero:N
\token_if_primitive:NF
\sys_if_output_pdf:F
\msg_expandable_error:nnnnn
\seq_if_exist:cT
\str_gclear:N
\exp_args:Nxo
\tl_map_break:
\prop_get:coNTF
\q_nil
\msg_redirect_class:nn
\tl_tail:V
\tl_if_single_token:nF
\dim_set:Nn
\tl_greverse:N
\seq_push:No
\g_tmpb_bool
\text_lowercase:nn
\dim_while_do:nn
\seq_put_left:cn
\box_if_exist_p:N
\dim_zero_new:c
\clist_push:cn
\seq_if_in:cvTF
\str_gremove_all:cn
\token_if_parameter:NF
\exp_args:Noox
\tl_gset_rescan:cnx
\iow_shipout_x:Nn
\box_use:c
\msg_show_item_unbraced:n
\msg_warning:nnxx
\cs_gset_protected_nopar:Npn
\vcoffin_set:cnw
\char_show_value_mathcode:n
\file_get_full_name:VNT
\skip_log:n
\tl_greplace_all:Nnn
\str_if_in:cnTF
\keys_if_choice_exist:nnnF
\str_gremove_all:Nn
\tl_put_right:NV
\flag_height:n
\muskip_sub:cn
\clist_set_eq:cN
\keys_set_known:nvN
\ExplSyntaxOff
\token_if_math_toggle:NTF
\fp_gset_eq:cc
\seq_gset_filter:NNn
\box_gresize_to_ht:cn
\tl_if_blank:VTF
\hbox_gset:Nw
\keys_set:nV
\sys_if_engine_ptex:TF
\str_gput_left:cn
\str_const:Nn
\seq_gput_left:cn
\vbox_top:n
\tl_if_single:cF
\prop_get:NoNTF
\vcoffin_set:Nnw
\dim_set_eq:cN
\tl_if_empty:NT
\token_if_eq_catcode:NNTF
\prop_get:NVNT
\clist_reverse:N
\iow_log:n
\cs_if_exist_use:c
\quark_if_nil:oTF
\vbox_to_ht:nn
\str_if_eq_p:cc
\coffin_gset_vertical_pole:Nnn
\str_tail_ignore_spaces:n
\intarray_gzero:N
\use_none_delimit_by_q_nil:w
\prop_item:cn
\token_if_group_begin:NTF
\peek_charcode:NT
\prop_gpop:NnN
\bool_show:n
\cs:w
\use_none_delimit_by_s_stop:w
\box_gset_ht:cn
\token_if_cs_p:N
\token_if_expandable:NT
\int_to_hex:n
\str_if_eq_p:on
\skip_new:c
\exp_args:NNo
\skip_gzero_new:c
\cs_gset:Nx
\tl_replace_all:cnn
\str_gput_right:cx
\str_head:c
\cs_new_protected:cpx
