\iow_new:c
\fp_add:Nn
\clist_gset_from_seq:NN
\iow_char:N
\prop_pop:cnN
\tl_gclear:N
\clist_set_from_seq:NN
\prop_if_in_p:No
\str_head:N
\cs_set_nopar:Npn
\tl_replace_once:cnn
\char_set_lccode:nn
\bool_lazy_all:nF
\dim_gset_eq:NN
\int_to_symbols:nnn
\hbox_overlap_left:n
\sys_shell_now:n
\fp_use:N
\sys_if_engine_pdftex_p:
\str_gput_left:Nx
\skip_set_eq:NN
\seq_set_from_clist:cn
\vbox_gset:cn
\g_tmpb_iow
\intarray_gset_rand:Nnn
\muskip_if_exist:NF
\box_if_exist_p:N
\str_if_eq_p:NN
\token_if_group_end:NT
\int_show:N
\file_get_full_name:nNTF
\dim_show:c
\vbox_set_to_ht:Nnn
\prop_clear_new:c
\intarray_to_clist:N
\int_from_alph:n
\hbox_gset:Nn
\tl_build_gend:N
\int_set:cn
\clist_set_from_seq:cN
\prop_pop:cnNT
\clist_put_left:cn
\c_sys_hour_int
\cs_set_eq:NN
\token_if_letter:NT
\tl_if_empty_p:o
\cs_generate_from_arg_count:Ncnn
\box_if_horizontal:cTF
\prop_gput:NVn
\str_gset_convert:NnnnF
\msg_fatal:nnn
\str_if_exist:NF
\use:nnnn
\coffin_gattach:NnnNnnnn
\tl_gsort:cn
\keys_set_filter:nnv
\cs_meaning:c
\hbox_unpack_drop:c
\quark_if_no_value:nT
\peek_meaning_ignore_spaces:NTF
\tl_if_exist:cTF
\l_keys_key_str
\coffin_clear:c
\regex_replace_all:nnNTF
\str_gput_right:cx
\str_if_eq:vnF
\cs_gset_protected_nopar:Nn
\int_decr:N
\skip_vertical:c
\msg_warning:nnxx
\hbox_gset:cw
\if_dim:w
\cs_gset_eq:cN
\hbox_gset:Nw
\intarray_show:N
\vbox_gset_to_ht:cnn
\tl_if_blank_p:o
\prop_pop:coN
\int_if_exist:NF
\flag_height:n
\tl_const:Nx
\skip_gset_eq:cc
\clist_if_empty:NT
\bool_do_until:cn
\keys_set:nV
\token_if_space:NF
\tl_gset:co
\fp_if_exist:NF
\vbox_set:Nw
\exp_args:Ncc
\int_step_variable:nnNn
\peek_meaning:NF
\tl_set:cx
\str_put_left:Nx
\peek_charcode_remove_ignore_spaces:NTF
\box_resize_to_wd_and_ht_plus_dp:cnn
\prop_get:coNTF
\prop_gput_if_new:Nnn
\peek_gafter:Nw
\file_compare_timestamp:nNnT
\str_lowercase:n
\prop_if_in:NVF
\clist_if_in:NnTF
\token_if_chardef_p:N
\prop_gput:Non
\tl_if_eq_p:NN
\seq_gshuffle:c
\box_set_eq:cc
\int_until_do:nn
\clist_if_empty:NTF
\clist_if_exist_p:N
\fp_compare:nNnF
\exp_args:Nof
\tl_build_gclear:N
\tl_tail:f
\quark_if_nil:NF
\tl_gput_left:cn
\prop_pop:NoN
\clist_gput_right:NV
\seq_use:cn
\skip_set_eq:cc
\clist_if_in:coT
\clist_if_in:NoTF
\sys_if_shell:T
\box_if_horizontal:NTF
\int_compare:nTF
\bool_while_do:nn
\str_put_right:Nx
\int_compare_p:nNn
\exp_end:
\msg_show_item_unbraced:n
\tl_if_head_eq_catcode_p:nN
\msg_fatal:nnxxxx
\dim_gzero_new:N
\str_if_empty:cF
\tl_gput_right:Nn
\token_if_mathchardef:NT
\sys_if_engine_luatex:T
\clist_gset:co
\coffin_new:c
\int_compare_p:n
\seq_get_right:cNF
\prop_get:NnNTF
\token_if_expandable:NF
\tl_build_put_right:Nx
\iow_shipout:cn
\clist_remove_all:cn
\seq_if_in:NvTF
\str_gput_left:Nn
\exp_args:Nnff
\cs_new_protected:Nn
\seq_put_right:co
\box_if_vertical_p:c
\cs_meaning:N
\seq_get_left:NN
\token_if_expandable_p:N
\str_const:NV
\ior_if_eof_p:N
\coffin_set_eq:cc
\seq_pop_right:cNT
\box_gset_viewport:cnnnn
\seq_count:c
\tl_if_in:onT
\str_set_eq:cc
\cs_gset:Npx
\tl_head:v
\coffin_gjoin:NnnNnnnn
\c_sys_month_int
\tl_if_empty:nF
\clist_pop:NNTF
\coffin_if_exist:NTF
\seq_gput_left:Nx
\char_set_catcode_math_toggle:n
\iow_open:cn
\vcoffin_set:Nnn
\box_set_dp:Nn
\q_no_value
\regex_replace_all:NnNT
\cs_new_nopar:Npx
\str_const:cV
\token_if_letter_p:N
\seq_pop_right:cN
\exp_last_unbraced:NV
\tl_put_left:No
\box_set_ht:cn
\fp_while_do:nNnn
\int_compare:nNnF
\seq_use:cnnn
\cs_new:cpx
\char_set_catcode_group_end:n
\l_iow_line_count_int
\prop_gclear_new:N
\token_if_mathchardef:NTF
\msg_critical:nnx
\token_if_primitive:NTF
\file_if_exist:nTF
\seq_gpop_left:NN
\tl_if_head_is_space_p:n
\str_if_eq_p:no
\seq_get:cNT
\coffin_ht:N
\token_if_alignment_p:N
\seq_gpush:Nx
\seq_get:NNF
\peek_charcode_remove_ignore_spaces:NT
\token_if_space_p:N
\int_if_even:nT
\if_predicate:w
\seq_if_empty:cT
\ior_open:NnF
\group_align_safe_begin:
\intarray_gset:Nnn
\bool_if:nTF
\seq_gput_right:Nv
\exp_last_unbraced:NNV
\seq_if_exist_p:c
\tl_gset:Nn
\cs_set_nopar:cx
\prop_map_function:NN
\tl_case:NnTF
\exp_args:NNcf
\tl_sort:Nn
\seq_put_left:cV
\seq_gpop_right:cN
\bool_gset_true:N
\char_set_catcode_parameter:N
\g_tmpb_ior
\file_get_hex_dump:nnnNT
\box_set_eq:cN
\exp_args:Noo
\tl_case:cnT
\str_foldcase:V
\file_get_full_name:nNT
\l_tmpb_fp
\seq_push:NV
\bool_set_eq:cN
\prop_item:Nn
\dim_to_decimal:n
\str_put_left:cV
\legacy_if:nT
\str_if_eq_p:cc
\fparray_new:Nn
\tl_if_eq:nnF
\prg_new_conditional:Npnn
\seq_if_in:NVF
\char_set_catcode_space:n
\str_if_exist:cTF
\box_ht:N
\tl_tail:v
\tl_map_inline:cn
\cs_set:cn
\int_while_do:nNnn
\quark_if_recursion_tail_break:NN
\seq_set_from_clist:Nc
\str_gset_convert:NnnnTF
\exp_args:Nx
\seq_new:N
\cs_new_nopar:cpn
\c_sys_shell_escape_int
\tl_map_break:
\use_none:nnnnnn
\tl_if_blank:VTF
\prop_if_empty:cF
\sys_gset_rand_seed:n
\cs_gset_nopar:Npx
\seq_if_exist:cF
\token_if_muskip_register:NT
\box_new:c
\vbox_set_to_ht:cnn
\intarray_gset_rand:cnn
\char_set_active_eq:NN
\dim_const:Nn
\l_keys_choice_int
\lua_now:e
\file_get_hex_dump:nNT
\int_case:nnT
\clist_set:co
\box_gresize_to_wd_and_ht_plus_dp:cnn
\iow_newline:
\bool_log:c
\tl_head:N
\sys_if_engine_pdftex:TF
\str_if_empty:cT
\if_bool:N
\seq_gput_left:Nn
\tl_set:cn
\file_get_timestamp:nN
\prop_gset_eq:Nc
\tl_gput_right:Nx
\char_set_catcode_math_superscript:n
\l_text_letterlike_tl
\tl_case:cn
\seq_put_right:Nv
\tl_if_in:nnF
\cs_undefine:N
\c_zero_skip
\box_use_drop:N
\str_put_right:cx
\fp_new:N
\regex_replace_once:nnN
\coffin_join:cnnNnnnn
\bool_lazy_or:nnTF
\int_gzero_new:c
\token_if_primitive:NF
\c_math_toggle_token
\clist_if_in:nnTF
\bool_case_true:nF
\msg_fatal:nnnnnn
\clist_if_in:cVT
\str_set:cn
\char_set_active_eq:nc
\box_if_vertical_p:N
\box_if_empty:NF
\regex_replace_all:nnNF
\vbox_gset:cw
\file_get_full_name:nNF
\prop_if_in:cnTF
\iow_allow_break:
\tl_if_in:NnT
\vbox_set_top:cn
\coffin_gset_eq:cN
\vbox_gset_split_to_ht:cNn
\prop_get:cnNTF
\msg_log:nnxxxx
\dim_gzero_new:c
\tl_if_head_is_space:nTF
\bool_log:n
\dim_if_exist_p:N
\box_if_exist:cF
\clist_clear_new:c
\str_replace_once:cnn
\char_set_catcode_parameter:n
\str_case:nVTF
\clist_put_left:cx
\use_i_delimit_by_q_stop:nw
\regex_replace_all:NnN
\dim_until_do:nNnn
\tl_if_empty:VTF
\ior_map_inline:Nn
\clist_gpush:Nx
\group_align_safe_end:
\file_get_full_name:VNT
\token_if_muskip_register:NTF
\tl_set_rescan:Nnn
\clist_gset:NV
\fp_if_exist:NT
\str_map_inline:nn
\cs_new:Nn
\cs_if_exist_use:c
\use:e
\c_max_char_int
\peek_catcode_remove:NT
\seq_map_break:n
\char_gset_active_eq:Nc
\char_str_lowercase:N
\tl_gremove_once:Nn
\tl_gremove_all:Nn
\fp_gset_eq:Nc
\cs_new:cpn
\fp_if_exist_p:c
\str_if_eq:nVT
\seq_if_empty:NF
\keys_if_choice_exist:nnnF
\str_if_eq:eeF
\skip_new:N
\cs_gset:Npn
\str_map_function:cN
\prg_replicate:nn
\vcoffin_set_end:
\tl_greplace_once:Nnn
\str_gput_right:Nn
\msg_log:nnxx
\intarray_new:Nn
\bool_lazy_and_p:nn
\prg_do_nothing:
\msg_show:nnxx
\exp_args:NNv
\token_if_math_subscript_p:N
\GetIdInfo
\prop_item:cn
\int_step_inline:nn
\fp_if_exist:cTF
\msg_warning:nnnn
\clist_if_empty:cF
\coffin_gjoin:Nnncnnnn
\cs_log:c
\g_tmpb_bool
\token_if_other:NT
\bool_new:N
\clist_gput_left:Nx
\str_if_eq:eeT
\skip_set_eq:cN
\tl_if_head_eq_meaning:nNF
\cs_if_exist:cT
\int_set_eq:cc
\seq_get_left:NNTF
\quark_if_no_value:cT
\regex_replace_once:nnNF
\int_do_while:nNnn
\prg_map_break:Nn
\dim_gset_eq:cN
\dim_compare:nF
\str_case:nvTF
\seq_if_in:cVT
\coffin_rotate:Nn
\cs_gset:cn
\fp_eval:n
\fp_step_inline:nnnn
\str_if_eq:onT
\seq_gpop_left:NNT
\token_if_active:NTF
\str_show:c
\seq_if_exist:NT
\int_if_exist:cF
\prop_new:c
\dim_do_while:nn
\text_titlecase:nn
\fp_new:c
\prop_gset_from_keyval:Nn
\int_from_base:nn
\keys_set_groups:nnV
\token_if_parameter:NT
\seq_set_from_clist:Nn
\skip_horizontal:N
\fparray_gset:Nnn
\box_grotate:Nn
\seq_mapthread_function:ccN
\file_compare_timestamp_p:nNn
\tl_if_in:noF
\cs_if_free_p:N
\int_if_odd:nF
\tl_put_right:cx
\bool_lazy_any:nF
\cs_gset_nopar:cx
\cs_new_protected:cn
\bool_set_false:c
\bool_lazy_or:nnT
\regex_extract_all:nnN
\c_zero_int
\fp_do_until:nNnn
\prop_get:coN
\prop_gput:coo
\cs_new_nopar:Npn
\clist_put_right:Nx
\dim_compare:nT
\quark_if_no_value_p:c
\bool_lazy_and:nnF
\tl_if_in:VnT
\cs_prefix_spec:N
\intarray_log:N
\tl_gput_right:No
\tl_if_head_eq_charcode:nNF
\ior_map_break:n
\tl_if_empty:nT
\use_none_delimit_by_q_stop:w
\tl_if_head_eq_charcode:fNF
\fp_set:cn
\box_use:N
\prg_break_point:
\clist_if_exist:cF
\cs_set_nopar:Nx
\clist_set_from_seq:Nc
\sys_if_shell:F
\seq_clear_new:N
\coffin_set_eq:NN
\str_if_in:nnF
\prop_map_tokens:Nn
\str_greplace_once:Nnn
\regex_replace_once:NnNT
\token_if_expandable:NT
\prg_return_true:
\g_tmpb_fp
\bool_if_p:c
\tl_gput_left:Nx
\coffin_scale:cnn
\cs_new_protected_nopar:cpx
\c_max_int
\coffin_gset_eq:Nc
\keys_set_groups:nno
\clist_sort:cn
\int_to_alph:n
\seq_clear:c
\tl_case:NnF
\seq_gsort:cn
\exp_args:Nffo
\tl_if_novalue_p:n
\hbox_set:cw
\tl_if_head_eq_catcode:nNT
\prop_if_empty_p:c
\tl_if_in:nnT
\prop_if_empty:NT
\str_show:n
\prop_clear_new:N
\clist_set_eq:Nc
\int_if_odd_p:n
\ior_shell_open:Nn
\tl_gput_left:cx
\dim_set_eq:cc
\str_case:nvT
\seq_gset_from_inline_x:Nnn
\token_if_other_p:N
\clist_log:N
\str_if_empty_p:c
\seq_reverse:c
\seq_gput_right:No
\ior_str_get:NNTF
\muskip_new:N
\box_if_vertical:cT
\sys_if_engine_uptex_p:
\q_stop
\seq_gpush:cx
\tl_rand_item:n
\clist_const:cx
\fp_use:c
\exp_args:Nnc
\str_if_eq:VnTF
\box_move_up:nn
\cs_set:cpx
\bool_const:cn
\regex_replace_all:nnN
\exp_not:f
\sys_if_platform_unix:T
\use_ii:nnn
\dim_to_decimal_in_unit:nn
\file_get_hex_dump:nnnN
\g_tmpa_str
\clist_gpush:cV
\tl_if_head_eq_meaning:nNT
\cs_gset_eq:NN
\flag_show:n
\intarray_gset_rand:Nn
\cs_to_str:N
\seq_remove_duplicates:c
\dim_zero_new:N
\tl_if_head_is_N_type:nF
\vbox_gset_end:
\str_if_in:cnTF
\prop_if_in:NVT
\clist_if_in:nVT
\token_if_eq_meaning:NNF
\cs_if_eq:NNT
\cs_set:Nn
\int_if_exist:cTF
\clist_pop:NNT
\seq_if_in:NnTF
\msg_info:nn
\keys_set_known:nVN
\tl_if_empty:VT
\l_tmpb_str
\c_catcode_active_tl
\debug_off:n
\int_gzero:c
\fp_step_function:nnnN
\skip_log:n
\seq_pop_right:NN
\dim_show:n
\skip_zero_new:c
\lua_escape:n
\bool_log:N
\cs_generate_variant:cn
\tl_count:N
\tl_set_eq:NN
\c_pi_fp
\muskip_if_exist:cF
\char_set_catcode_comment:n
\box_if_vertical:NT
\str_item_ignore_spaces:nn
\tl_rand_item:c
\seq_gput_right:cV
\seq_get_left:NNF
\peek_charcode_remove:NF
\tl_if_blank:eT
\sys_if_engine_pdftex:F
\clist_if_in:coF
\str_put_left:cn
\str_count:c
\token_if_int_register:NF
\bool_lazy_and:nnT
\str_if_eq:NNTF
\ProvidesExplFile
\c_max_muskip
\str_if_eq_p:vn
\peek_meaning_remove:NTF
\char_gset_active_eq:nN
\char_set_catcode_letter:N
\keys_set_known:nn
\skip_new:c
\fp_to_tl:N
\box_use_drop:c
\cs_set_protected:cx
\tl_if_single_p:n
\int_compare:nNnTF
\seq_remove_all:cn
\seq_mapthread_function:cNN
\seq_gpop_left:cN
\sys_if_engine_xetex:T
\g_tmpb_regex
\char_to_nfd:N
\file_timestamp:n
\int_to_Roman:n
\file_get_hex_dump:nnnNF
\seq_gput_left:cx
\char_uppercase:N
\fp_if_nan:nF
\tl_if_eq:nnTF
\token_if_primitive_p:N
\muskip_show:N
\g_tmpb_coffin
\token_if_letter:NTF
\box_wd:N
\exp_not:V
\clist_if_in:coTF
\bool_until_do:cn
\msg_critical:nnn
\keys_show:nn
\prop_clear:N
\clist_gput_right:cV
\skip_log:N
\tl_log:N
\flag_if_exist:nTF
\tl_analysis_show:n
\str_replace_all:cnn
\str_if_eq:cNTF
\box_gresize_to_wd_and_ht:cnn
\int_if_even:nF
\cs_if_exist_use:cTF
\hbox_unpack_drop:N
\skip_gzero:N
\tl_if_head_eq_charcode:fNT
\tl_set:Nf
\box_gscale:Nnn
\dim_compare_p:nNn
\quark_if_nil_p:V
\l_keys_choice_tl
\char_set_catcode_math_superscript:N
\c_max_skip
\prop_if_exist:NT
\clist_gput_right:No
\seq_if_in:coF
\seq_gset_eq:NN
\prop_count:c
\regex_new:N
\int_step_function:nnN
\regex_replace_all:NnNF
\prop_put:NVn
\skip_gset:cn
\vbox_set_split_to_ht:Ncn
\seq_pop_left:cNF
\c_left_brace_str
\clist_item:cn
\c_group_begin_token
\int_gincr:N
\fp_log:N
\bool_lazy_any_p:n
\str_greplace_all:cnn
\sys_if_rand_exist_p:
\muskip_gzero_new:c
\tl_new:N
\c_underscore_str
\str_clear:N
\tl_set_rescan:Nnx
\char_set_active_eq:nN
\dim_log:c
\skip_use:c
\seq_gput_right:Nx
\msg_see_documentation_text:n
\seq_gpop:cN
\char_set_uccode:nn
\prop_pop:NnNT
\seq_gpush:No
\skip_sub:cn
\prop_gpop:cnNT
\clist_push:cV
\int_set:Nn
\dim_compare:nNnTF
\cs_if_free:cT
\str_if_eq:nnTF
\seq_get_left:cNF
\clist_gput_left:No
\prg_set_eq_conditional:NNn
\clist_clear:N
\hcoffin_gset:cw
\fp_if_nan_p:n
\bool_gset_eq:cN
\sys_if_engine_luatex_p:
\str_if_in:NnT
\msg_fatal:nnnn
\muskip_set_eq:cN
\exp_args:Neee
\token_if_skip_register:NT
\tl_gput_right:co
\flag_new:n
\cs_new_protected_nopar:Npx
\cs_gset_protected:cpx
\seq_gclear:N
\seq_shuffle:N
\fp_show:n
\file_show_list:
\prop_if_in:coT
\int_gset:cn
\prop_get:NVN
\dim_eval:n
\box_gautosize_to_wd_and_ht_plus_dp:cnn
\int_show:n
\cs_if_exist:cF
\vcoffin_gset:Nnn
\msg_module_name:n
\dim_show:N
\clist_if_in:NoF
\legacy_if:nF
\intarray_const_from_clist:cn
\clist_if_in:NoT
\vbox_gset_top:Nn
\bool_if_exist_p:c
\prg_new_protected_conditional:Nnn
\clist_map_inline:nn
\clist_if_empty:cTF
\token_if_group_end:NTF
\g_file_curr_name_str
\fp_gadd:cn
\clist_log:c
\tl_range_braced:Nnn
\c_max_register_int
\dim_case:nnF
\seq_remove_all:Nn
\seq_if_in:NnT
\token_if_group_begin:NTF
\tl_map_variable:nNn
\if_mode_horizontal:
\token_if_math_superscript:NT
\clist_map_function:NN
\cs_set_protected:Nn
\cs_gset_protected:Npx
\ior_close:c
\str_map_function:NN
\tl_set:Nx
\clist_put_right:co
\seq_gset_split:Nnn
\char_set_catcode_active:N
\prop_if_in_p:co
\tl_const:cx
\msg_none:nnnn
\tl_put_left:co
\token_if_toks_register_p:N
\cs_split_function:N
\mode_if_inner:T
\seq_put_right:cv
\int_from_bin:n
\str_remove_once:cn
\clist_use:Nn
\sys_if_engine_ptex:F
\cs_end:
\g_tmpb_skip
\str_if_eq:noT
\coffin_if_exist_p:c
\prop_gpop:NnNTF
\tl_range_braced:cnn
\dim_gset_eq:cc
\skip_horizontal:c
\str_map_variable:cNn
\seq_if_empty:cTF
\ior_if_eof:NT
\cs_if_free_p:c
\tl_map_tokens:cn
\if_mode_math:
\tl_set:co
\cs_if_eq:NNTF
\msg_expandable_error:nnnn
\seq_pop_right:NNTF
\mode_if_math:F
\l_tmpa_int
\seq_if_in:cvF
\exp_last_unbraced:Nf
\str_head_ignore_spaces:n
\str_if_eq:cNF
\bool_if_exist:NTF
\c_minus_inf_fp
\seq_gpop_right:cNTF
\str_case:nVF
\exp_last_unbraced:Nv
\cs_set_nopar:cn
\cs_gset_protected_nopar:Npn
\clist_gput_right:Nn
\str_case_e:nn
\clist_gpush:NV
\token_if_math_subscript:NTF
\fp_zero_new:c
\prop_new:N
\prop_if_in:NoF
\cs_generate_from_arg_count:NNnn
\sort_return_swapped:
\clist_if_in:noF
\prop_get:NoNTF
\char_set_catcode_group_begin:N
\clist_if_in:cVTF
\str_if_eq_p:nn
\str_set_convert:NnnnF
\msg_none:nnxxx
\char_set_catcode_ignore:N
\int_add:cn
\clist_if_in:nVF
\fparray_count:N
\msg_warning:nnxxx
\str_if_eq:VnT
\seq_pop_right:cNTF
\iow_now:cx
\msg_warning_text:n
\tl_if_blank:nTF
\tl_if_empty_p:n
\sys_if_engine_luatex:F
\token_if_long_macro:NF
\file_get_mdfive_hash:nNTF
\str_gclear:c
\g_tmpb_str
\exp_args:Nxx
\box_autosize_to_wd_and_ht:cnn
\msg_line_context:
\cs_set:Npn
\str_if_eq:onTF
\dim_zero:c
\tl_gset_eq:NN
\str_if_eq:vnT
\sys_if_output_dvi:TF
\clist_pop:NNF
\keys_set_filter:nnoN
\token_if_math_toggle:NT
\clist_gremove_all:Nn
\sys_shell_shipout:n
\tl_log:c
\exp_args:Ne
\clist_if_empty:nF
\bool_case_false:nT
\tl_case:cnF
\tl_put_left:cx
\prop_pop:NnN
\c_empty_tl
\token_if_eq_catcode_p:NN
\str_if_eq_p:Vn
\box_gclip:c
\l_keys_value_tl
\token_if_macro:NTF
\keys_set_filter:nnV
\token_if_protected_long_macro_p:N
\vbox_top:n
\iow_show_list:
\c_sys_output_str
\sys_if_platform_windows:TF
\tl_if_single:cF
\str_if_eq:nVF
\prop_gput:cVV
\dim_min:nn
\intarray_rand_item:c
\str_if_eq:nVTF
\regex_gset:Nn
\clist_pop:cNT
\seq_gset_eq:Nc
\cs_set_nopar:cpn
\seq_if_exist:cT
\sys_if_platform_windows:F
\seq_if_in:NxTF
\tl_analysis_show:N
\seq_clear:N
\int_max:nn
\str_put_right:Nn
\seq_if_in:coT
\fp_gset:Nn
\peek_charcode:NF
\clist_pop:cNTF
\dim_to_decimal_in_bp:n
\c_term_iow
\iow_shipout_x:Nx
\str_case:nVT
\coffin_gresize:cnn
\msg_show:nnnnn
\clist_put_right:Nn
\int_gset_eq:cN
\clist_gset:cx
\dim_gadd:cn
\vbox_set_end:
\g_tmpa_bool
\file_get_size:nNF
\hbox_overlap_right:n
\str_set_convert:NnnnTF
\skip_if_exist:cF
\char_set_catcode_other:N
\fp_gset_eq:cc
\msg_line_number:
\c_colon_str
\fp_sign:n
\char_set_catcode_group_begin:n
\clist_gset:cV
\sys_if_rand_exist:F
\bool_set_false:N
\tl_if_head_eq_catcode:nNTF
\tl_gset:cv
\tl_range_unbraced:Nnn
\vcoffin_set:cnn
\exp_args:Ncf
\int_compare:nNnT
\str_gremove_once:cn
\seq_gput_right:cn
\seq_if_in:cxT
\tl_case:Nn
\keys_if_choice_exist:nnnTF
\skip_gsub:cn
\tl_remove_all:cn
\prop_if_in_p:cV
\quark_if_recursion_tail_stop:n
\skip_gset_eq:cN
\dim_if_exist:NF
\peek_meaning_collect_inline:Nn
\clist_gset_from_seq:Nc
\box_set_wd:Nn
\cs_gset_nopar:Npn
\prop_gpop:cnNF
\use_iii:nnn
\char_value_sfcode:n
\box_gset_viewport:Nnnnn
\prop_get:cnNF
\coffin_display_handles:cn
\box_gset_dp:cn
\seq_gpush:Nn
\bool_until_do:Nn
\str_case:on
\box_if_exist:cTF
\clist_gput_right:co
\l_tmpa_prop
\str_if_eq_p:VV
\int_new:N
\str_set:cx
\dim_set_eq:NN
\coffin_join:cnncnnnn
\int_until_do:nNnn
\prop_if_in:coTF
\seq_if_exist:NTF
\token_if_group_begin_p:N
\scan_stop:
\prop_rand_key_value:N
\peek_meaning_ignore_spaces:NF
\msg_error:nnnnnn
\exp_args:NNf
\exp_args:NcnV
\prop_get:cVNF
\seq_map_tokens:cn
\keyval_parse:NNn
\tl_if_blank_p:V
\if_cs_exist:w
\tl_build_clear:N
\fp_step_function:nnnc
\dim_while_do:nn
\exp_args:Nnv
\exp_args:Nnf
\color_group_begin:
\dim_gsub:Nn
\clist_if_empty:NF
\token_if_parameter_p:N
\tl_if_novalue:nT
\fp_compare:nNnT
\exp_args:Nco
\str_item:Nn
\msg_fatal:nnx
\dim_new:c
\exp_args:Nxo
\bool_gset:cn
\box_gautosize_to_wd_and_ht:Nnn
\tl_if_eq:cNT
\msg_expandable_error:nnffff
\clist_push:cx
\skip_zero:N
\clist_concat:ccc
\bool_gset:Nn
\token_to_meaning:N
\seq_set_eq:NN
\seq_push:No
\quark_if_no_value:cF
\g_tmpa_regex
\fp_log:c
\peek_charcode:NT
\prop_get:cVNT
\exp_args:No
\fp_if_exist:cF
\skip_const:Nn
\str_if_eq_p:nv
\msg_info:nnx
\clist_gpush:cx
\sys_if_platform_windows:T
\msg_if_exist:nnTF
\fp_sub:cn
\q_recursion_stop
\box_gresize_to_ht:Nn
\box_if_exist_p:c
\fp_gset_eq:cN
\tl_if_eq:ccT
\tl_trim_spaces_apply:oN
\prop_gput:cno
\tl_count:V
\cs_set_protected:Npx
\tl_if_head_is_N_type_p:n
\fp_to_int:c
\msg_warning:nnn
\use_none:nnnn
\c_false_bool
\seq_put_left:cx
\seq_push:cV
\clist_const:cn
\skip_set_eq:Nc
\prop_if_in:cVF
\token_if_alignment:NT
\str_if_eq:NNT
\clist_gremove_duplicates:N
\exp_not:N
\c_one_fp
\tl_map_function:nN
\tl_item:Nn
\dim_sign:n
\seq_map_tokens:Nn
\token_to_meaning:c
\tl_build_put_left:Nn
\c_minus_zero_fp
\msg_info:nnnnn
\box_gclip:N
\c_zero_muskip
\str_set_convert:Nnnn
\clist_gremove_all:cn
\str_if_eq:nnT
\int_if_exist_p:c
\clist_push:co
\seq_greverse:N
\seq_if_in:NoTF
\seq_clear_new:c
\coffin_gjoin:cnncnnnn
\clist_concat:NNN
\int_step_variable:nNn
\peek_catcode:NT
\clist_gpush:No
\seq_gpop_left:cNT
\int_if_exist:cT
\tl_trim_spaces:N
\dim_step_function:nnnN
\tl_const:Nn
\clist_gpop:cNT
\lua_now:n
\c_tilde_str
\c_novalue_tl
\coffin_ht:c
\tl_if_empty_p:c
\box_if_vertical:NF
\cs_show:N
\peek_meaning_remove_ignore_spaces:NT
\if_hbox:N
\cs_set_protected_nopar:Nx
\file_compare_timestamp:nNnTF
\seq_gput_left:cv
\box_set_to_last:c
\token_if_long_macro_p:N
\clist_gput_right:Nx
\if_int_compare:w
\bool_lazy_all:nT
\sys_if_engine_luatex:TF
\token_if_letter:NF
\flag_clear:n
\clist_put_left:NV
\tl_if_exist:NF
\tl_count_tokens:n
\int_do_while:nn
\tl_set:Nv
\token_if_eq_catcode:NNTF
\int_while_do:nn
\ExplSyntaxOn
\cs_if_free:cF
\iow_indent:n
\box_gresize_to_wd_and_ht:Nnn
\prop_remove:Nn
\tl_gput_right:cV
\flag_clear_new:n
\exp_after:wN
\seq_item:Nn
\seq_const_from_clist:cn
\token_if_chardef:NTF
\regex_replace_all:nnNT
\l_tmpb_coffin
\bool_set_eq:Nc
\prop_map_inline:Nn
\tl_if_single:cTF
\seq_map_function:NN
\use:x
\keys_set_filter:nnvN
\tl_to_str:c
\seq_if_in:NoF
\ior_str_get:NNT
\g_tmpa_iow
\exp_args:Nne
\hcoffin_set:Nn
\mode_if_horizontal:F
\str_count:n
\prop_gpop:cnNTF
\tl_gset_rescan:cnn
\sys_if_engine_ptex:T
\seq_sort:Nn
\dim_log:n
\seq_gpop:NN
\tl_if_empty:oF
\prop_gset_eq:cN
\clist_gpop:cNF
\prop_if_in:NnTF
\exp_args:Nnox
\keys_set_known:nv
\fp_to_tl:c
\prop_gpop:NnNF
\regex_extract_all:nnNTF
\bool_new:c
\seq_set_filter:NNn
\char_set_catcode_alignment:N
\tl_to_str:V
\keys_set:no
\exp_args:Ncx
\seq_map_inline:Nn
\msg_info:nnxx
\dim_to_decimal_in_sp:n
\str_case:onTF
\clist_put_left:No
\regex_replace_once:nnNTF
\char_show_value_catcode:n
\clist_set:Nx
\tl_if_eq_p:Nc
\dim_compare_p:n
\str_if_eq_p:nV
\token_if_cs:NTF
\l_tmpa_skip
\file_mdfive_hash:n
\regex_match:nnT
\keys_set_filter:nnnnN
\char_set_catcode_end_line:N
\msg_show:nnnn
\msg_gset:nnnn
\msg_info:nnxxx
\exp_args:Nc
\msg_expandable_error:nnn
\str_if_exist_p:N
\str_case_e:nnF
\seq_pop:cNTF
\prop_if_exist:cT
\dim_ratio:nn
\box_gset_eq:Nc
\peek_charcode_ignore_spaces:NTF
\file_get_full_name:nN
\cs_set_protected_nopar:cpx
\int_gadd:cn
\exp_last_unbraced:Nno
\prop_put:cnV
\coffin_new:N
\bool_do_while:cn
\cs_if_exist:NT
\tl_gset_eq:cN
\file_get_timestamp:nNF
\exp_args:NNVV
\bool_set_inverse:N
\box_dp:N
\box_resize_to_ht_plus_dp:cn
\regex_extract_once:nnNT
\bool_xor:nnTF
\use_ii_i:nn
\str_if_eq:ccF
\clist_map_function:nN
\tl_gclear_new:c
\legacy_if_p:n
\keys_set_filter:nnVN
\str_gset_convert:NnnnT
\prop_put:NVV
\token_if_group_begin:NT
\regex_split:NnNT
\coffin_resize:cnn
\file_get_mdfive_hash:nNT
\hbox_gset_to_wd:Nnn
\hcoffin_gset:cn
\clist_get:cN
\msg_fatal:nn
\clist_set:cx
\sys_if_shell_unrestricted:T
\cs_new_eq:Nc
\skip_show:N
\char_set_catcode_letter:n
\tl_tail:N
\prop_gput:cnn
\tl_gset_rescan:cnx
\tl_if_exist_p:c
\fp_gsub:cn
\prop_get:NnNT
\mode_if_inner_p:
\exp_args:NcNc
\str_if_in:nnT
\bool_lazy_or:nnF
\lua_escape:e
\regex_replace_once:NnN
\seq_gpop_left:NNTF
\skip_vertical:N
\coffin_gset_vertical_pole:Nnn
\clist_gremove_duplicates:c
\seq_pop_right:NNF
\dim_do_until:nNnn
\bool_while_do:cn
\peek_catcode:NF
\bool_xor:nnF
\str_case:nnT
\quark_if_recursion_tail_stop:N
\clist_if_in:NVTF
\str_if_eq_p:ee
\prop_map_break:
\seq_pop:NNT
\coffin_if_exist:NT
\prop_if_in_p:NV
\int_gincr:c
\dim_sub:Nn
\token_if_active:NT
\fp_zero_new:N
\int_from_oct:n
\clist_if_exist:cTF
\peek_catcode_collect_inline:Nn
\exp_args_generate:n
\regex_extract_once:nnNF
\dim_const:cn
\cs:w
\ior_open:cnF
\str_if_eq:ccTF
\str_new:c
\seq_if_in:cnF
\int_from_roman:n
\int_if_even:nTF
\fp_show:c
\clist_gput_left:Nn
\token_if_dim_register:NF
\box_gresize_to_ht:cn
\clist_gset:Nx
\exp_args:NNnV
\msg_critical:nnxxxx
\g_file_curr_ext_str
\file_if_exist_input:n
\tl_if_head_eq_charcode_p:nN
\tl_show:c
\tl_if_empty:VF
\box_gset_ht:Nn
\vbox_set_to_ht:cnw
\muskip_gset_eq:NN
\msg_critical_text:n
\cs_new_protected:cx
\tl_new:c
\g_tmpb_clist
\box_move_left:nn
\bool_if:cT
\flag_if_raised:nF
\box_resize_to_wd:cn
\str_set:Nx
\muskip_gadd:Nn
\str_if_exist:cT
\regex_extract_all:NnNF
\seq_put_left:Nx
\str_remove_all:Nn
\seq_indexed_map_function:NN
\cs_new_eq:cN
\coffin_join:NnnNnnnn
\cs_new:cn
\skip_if_eq:nnTF
\bool_lazy_or_p:nn
\clist_put_right:NV
\clist_set_eq:cN
\clist_gput_left:cV
\int_rand:nn
\prop_map_tokens:cn
\seq_gput_right:NV
\prop_if_empty:NTF
\vcoffin_gset_end:
\prop_if_in:NoT
\char_set_catcode_active:n
\vcoffin_gset:cnn
\int_case:nnF
\clist_gpop:NNT
\box_resize_to_wd_and_ht:Nnn
\skip_gsub:Nn
\prop_map_break:n
\tl_gset_eq:Nc
\use_none:nnn
\fp_set_eq:Nc
\str_if_eq:nvTF
\clist_put_right:cn
\box_set_eq:NN
\seq_if_exist:cTF
\quark_if_nil_p:N
\prop_show:c
\token_if_eq_meaning_p:NN
\quark_new:N
\muskip_set_eq:cc
\cs_new_nopar:cx
\seq_pop_right:NNT
\str_case:nv
\vcoffin_gset:Nnw
\str_set_convert:NnnnT
\clist_if_in:cnF
\keys_set_filter:nnnN
\seq_set_from_clist:NN
\prop_if_exist:cTF
\regex_extract_all:NnNTF
\cs_set:cx
\peek_catcode_ignore_spaces:NT
\tl_build_gput_left:Nx
\str_lowercase:f
\tl_build_gput_right:Nn
\regex_show:N
\str_clear:c
\fp_trap:nn
\int_gzero_new:N
\use:c
\keys_set_known:nvN
\s_stop
\str_count_ignore_spaces:n
\tl_reverse:N
\flag_raise_if_clear:n
\l_tmpb_tl
\seq_push:cv
\coffin_gattach:cnncnnnn
\exp_args:NcNo
\int_gsub:cn
\msg_warning:nnx
\exp_not:c
\peek_remove_spaces:n
\tl_use:N
\token_if_chardef:NT
\int_to_Hex:n
\muskip_add:Nn
\iow_wrap:nnnN
\str_clear_new:N
\seq_put_left:cv
\box_gset_eq_drop:cN
\prop_put:cno
\prop_gset_eq:NN
\str_range:nnn
\seq_set_split:NnV
\msg_show:nnxxx
\cs_gset_eq:cc
\g_tmpa_seq
\tl_if_eq_p:cc
\intarray_item:cn
\str_count_spaces:c
\sys_if_shell_unrestricted:F
\msg_error:nnxxx
\fp_step_variable:nnnNn
\prop_pop:NnNF
\use:nnn
\file_get_timestamp:nNTF
\seq_map_variable:cNn
\tl_if_head_is_N_type:nTF
\tl_case:NnT
\seq_put_right:cV
\char_set_active_eq:Nc
\prop_pop:NnNTF
\str_log:n
\prop_put:Nnx
\tl_range:nnn
\tl_replace_once:Nnn
\bool_if_exist:NF
\tl_if_in:VnTF
\tl_head:V
\peek_charcode_remove:NT
\tl_reverse:n
\box_set_eq_drop:NN
\clist_remove_duplicates:N
\l_tmpb_prop
\prop_gput:Nnn
\tl_if_head_is_group:nF
\clist_count:n
\regex_split:nnN
\tl_gset:Nv
\muskip_if_exist_p:N
\bool_const:Nn
\bool_while_do:Nn
\keys_set_known:nonN
\file_get_hex_dump:nNF
\clist_if_empty_p:N
\regex_extract_once:NnNF
\quark_if_no_value:nF
\cs_set:Nx
\str_gset:NV
\c_group_end_token
\quark_if_nil:VT
\str_if_eq:noTF
\msg_error:nnnnn
\dim_gset:Nn
\bool_gset_true:c
\msg_if_exist:nnT
\seq_concat:ccc
\str_const:cx
\prop_gset_eq:cc
\file_parse_full_name:nNNN
\coffin_clear:N
\coffin_if_exist:NF
\seq_pop_right:cNF
\peek_catcode_remove:NTF
\str_case:onF
\if_mode_vertical:
\str_gset:cV
\file_full_name:V
\bool_do_while:Nn
\else:
\prop_put_if_new:Nnn
\exp_args:Nooo
\g_tmpb_muskip
\box_gset_eq_drop:cc
\seq_put_left:co
\prop_get:cVNTF
\clist_pop:cN
\str_set_eq:NN
\str_new:N
\cs_if_eq_p:NN
\intarray_item:Nn
\fp_add:cn
\vbox_set_split_to_ht:NNn
\seq_push:cn
\use_ii:nnnn
\dim_do_until:nn
\seq_if_empty:NTF
\box_set_wd:cn
\str_clear_new:c
\str_gput_right:NV
\g_tmpb_dim
\iow_shipout:cx
\seq_pop:cNF
\keys_set_filter:nnn
\peek_meaning_remove:NT
\msg_log_eval:Nn
\token_if_math_superscript:NF
\seq_gclear:c
\c_true_bool
\cs_gset_protected:Npn
\seq_pop:cN
\keys_if_exist:nnTF
\bool_set_eq:cc
\tl_set_eq:cc
\clist_if_exist:cT
\box_clear_new:c
\prg_new_eq_conditional:NNn
\ior_get:NNF
\tl_if_eq:cNF
\box_if_horizontal:cF
\clist_if_in:cnT
\exp_args:NNno
\clist_map_variable:NNn
\token_if_math_toggle:NTF
\mode_if_vertical:F
\seq_gset_filter:NNn
\skip_vertical:n
\file_size:n
\dim_if_exist_p:c
\dim_gset_eq:Nc
\str_replace_once:Nnn
\clist_put_left:cV
\msg_none:nn
\regex_count:NnN
\ior_if_eof:NF
\c_percent_str
\cs_if_exist_use:cF
\dim_if_exist:cF
\box_if_horizontal:cT
\seq_get_right:cNTF
\fp_gzero:N
\sys_if_engine_xetex_p:
\tl_sort:nN
\iow_shipout_x:Nn
\box_dp:c
\vbox_gset_split_to_ht:Ncn
\peek_charcode_ignore_spaces:NF
\tl_map_tokens:Nn
\tl_if_eq:nnT
\exp_last_unbraced:NNNo
\str_case:nnF
\str_if_empty:NT
\clist_if_empty:nTF
\clist_gconcat:NNN
\skip_eval:n
\mode_if_math:T
\box_gautosize_to_wd_and_ht:cnn
\prop_remove:cn
\dim_compare:nTF
\muskip_gset_eq:cN
\cs_gset_nopar:cn
\seq_get:cNF
\tl_if_empty:nTF
\coffin_dp:c
\skip_if_eq_p:nn
\peek_charcode_remove_ignore_spaces:NF
\coffin_if_exist:cT
\seq_new:c
\str_range:cnn
\int_gset_eq:NN
\char_set_catcode_math_subscript:N
\msg_new:nnnn
\bool_case_false:nF
\token_if_macro_p:N
\cs_set_nopar:Npx
\c_alignment_token
\exp_end_continue_f:nw
\token_if_other:NTF
\ProvidesExplClass
\sys_if_output_pdf:TF
\tl_if_exist:NT
\exp_args:NNe
\fp_set_eq:NN
\dim_while_do:nNnn
\cs_set_protected_nopar:Npx
\msg_error_text:n
\clist_if_exist:NF
\prop_get:cnNT
\quark_if_nil_p:o
\int_gdecr:N
\seq_gpush:co
\token_if_chardef:NF
\cs_set_protected:cpx
\g_tmpb_box
\box_clear:c
\seq_set_split:Nnn
\tl_if_in:noT
\iow_log:x
\box_if_horizontal_p:N
\tl_trim_spaces:n
\clist_if_in:NVF
\clist_put_right:cx
\cs_set_protected_nopar:cx
\skip_gset_eq:Nc
\bool_set_true:c
\seq_if_exist:NF
\seq_gpush:NV
\clist_gclear:c
\str_if_eq:NcF
\seq_get_right:NN
\coffin_wd:N
\str_set_eq:Nc
\tl_if_head_eq_catcode:oNF
\box_clip:c
\msg_set:nnnn
\prop_show:N
\bool_gset_eq:cc
\cs_set_protected_nopar:Nn
\coffin_log_structure:c
\tl_if_head_is_group:nTF
\sys_if_platform_windows_p:
\seq_set_from_clist:cN
\seq_gput_left:co
\clist_gset:Nn
\msg_redirect_module:nnn
\skip_set:Nn
\l_tmpb_muskip
\prop_put:cVn
\clist_get:NNF
\keys_if_exist:nnT
\use_none:nnnnn
\clist_put_right:cV
\int_case:nnTF
\seq_put_right:Nx
\prop_if_empty:cT
\group_begin:
\clist_gset_from_seq:cN
\sys_if_output_dvi:T
\cs_set_eq:cN
\str_gset:cn
\msg_warning:nnxxxx
\use_none_delimit_by_q_nil:w
\clist_push:Nn
\msg_fatal_text:n
\quark_if_nil:nF
\g_tmpa_skip
\box_log:Nnn
\iow_shipout_x:cn
\clist_remove_duplicates:c
\cs_set:cpn
\l_tmpa_tl
\peek_meaning_remove_ignore_spaces:NF
\hbox_set:Nw
\seq_push:Nn
\int_to_bin:n
\coffin_gset_eq:NN
\tl_if_single:nTF
\tl_gput_left:NV
\use_i_delimit_by_q_recursion_stop:nw
\box_grotate:cn
\str_gconcat:NNN
\intarray_gzero:c
\coffin_mark_handle:Nnnn
\seq_get_right:NNT
\fp_gzero_new:N
\exp_last_unbraced:Nfo
\iow_log_list:
\seq_if_in:NnF
\fp_gset_eq:NN
\c_empty_seq
\fp_while_do:nn
\clist_gpop:cN
\cs_gset_protected_nopar:cn
\char_value_lccode:n
\tl_gset:cf
\dim_abs:n
\char_value_catcode:n
\fp_if_exist:cT
\seq_gset_split:NnV
\token_if_long_macro:NTF
\cs_log:N
\prop_if_in:cnF
\msg_info_text:n
\msg_info:nnn
\str_case:Vn
\coffin_show_structure:c
\tl_put_left:NV
\ior_str_get_term:nN
\file_hex_dump:nnn
\fp_do_while:nn
\token_if_cs:NT
\cs_if_exist_use:N
\tl_if_eq:ccTF
\box_gset_trim:Nnnnn
\bool_set_inverse:c
\tl_gset:cx
\quark_if_no_value:NF
\regex_replace_once:nnNT
\int_if_even_p:n
\bool_gset_inverse:N
\str_head:n
\tl_if_blank:eTF
\clist_use:Nnnn
\token_if_skip_register:NTF
\char_set_catcode_invalid:N
\msg_show:nnxxxx
\seq_put_right:No
\char_set_catcode_escape:N
\cs_gset_nopar:Nx
\tl_concat:NNN
\box_rotate:Nn
\c_sys_engine_str
\tl_analysis_map_inline:nn
\clist_gput_right:cx
\skip_set:cn
\tl_head:w
\file_log_list:
\int_if_exist:NTF
\if_int_odd:w
\file_get_full_name:VN
\dim_if_exist:cTF
\int_step_function:nN
\msg_show_item:nn
\tl_if_eq:NcF
\clist_gset:No
\int_to_Base:nn
\tl_count:n
\regex_split:NnNF
\sys_if_engine_pdftex:T
\tl_set_rescan:cnx
\seq_gpop:NNF
\bool_lazy_and:nnTF
\char_set_catcode_group_end:N
\seq_if_in:NoT
\seq_pop_left:NN
\token_if_dim_register:NTF
\regex_extract_all:nnNT
\str_if_in:NnTF
\clist_reverse:n
\sys_if_platform_unix:F
\tl_reverse:o
\l_tmpa_bool
\seq_gremove_all:Nn
\clist_pop:cNF
\str_if_eq_p:cN
\prop_gput:cnV
\coffin_attach:NnnNnnnn
\seq_use:Nn
\flag_if_exist:nT
\regex_split:nnNT
\int_to_oct:n
\ior_get:NNTF
\tl_map_variable:NNn
\vbox_unpack_drop:c
\tl_if_blank:nF
\prop_put:Nnn
\tl_set_rescan:cnn
\g_msg_module_name_prop
\tl_gput_left:co
\tl_item:nn
\int_abs:n
\muskip_log:c
\vcoffin_set:Nnw
\msg_error:nnxx
\str_gset:Nn
\token_if_protected_macro:NT
\prop_remove:cV
\int_gset_eq:cc
\prop_gclear_new:c
\vbox_gset_top:cn
\coffin_mark_handle:cnnn
\ior_new:c
\bool_show:N
\msg_error:nnxxxx
\token_if_alignment:NTF
\regex_extract_once:nnNTF
\sys_if_platform_unix_p:
\str_gset_eq:Nc
\token_if_space:NTF
\prg_return_false:
\int_incr:c
\cs_gset_protected_nopar:cpn
\fp_to_dim:N
\box_resize_to_ht:cn
\msg_info:nnnnnn
\str_if_eq:ccT
\int_const:Nn
\vbox_set_to_ht:Nnw
\ior_new:N
\ExplSyntaxOff
\tl_put_right:No
\cs_if_exist:cTF
\fp_gzero_new:c
\prop_if_in:NoTF
\exp_last_unbraced:Noo
\flag_raise:n
\exp_args:Nox
\flag_if_exist:nF
\int_new:c
\seq_sort:cn
\regex_split:nnNF
\fp_do_until:nn
\token_if_skip_register_p:N
\fp_set_eq:cN
\keys_log:nn
\exp_last_unbraced:NNf
\ior_map_variable:NNn
\coffin_gscale:Nnn
\prop_get:NnN
\int_zero_new:c
\box_gset_wd:cn
\cs_if_exist_p:N
\c_sys_engine_version_str
\dim_gsub:cn
\box_autosize_to_wd_and_ht:Nnn
\peek_meaning_remove_ignore_spaces:NTF
\bool_if:NTF
\seq_get_right:NNTF
\str_case_e:nnT
\tl_if_in:NnTF
\tl_if_blank_p:e
\seq_pop_left:cN
\coffin_wd:c
\skip_zero_new:N
\prop_if_exist:NF
\hbox_set_to_wd:cnw
\l_tmpa_fp
\prop_gset_from_keyval:cn
\l_text_expand_exclude_tl
\if_eof:w
\str_set_eq:cN
\mode_if_vertical:T
\muskip_gzero_new:N
\sys_if_output_pdf:F
\vbox:n
\fp_to_dim:n
\token_if_cs:NF
\box_clip:N
\cs_gset_protected:cpn
\scan_new:N
\file_get_mdfive_hash:nNF
\cs_new_protected_nopar:Nx
\dim_step_inline:nnnn
\box_gclear_new:N
\clist_gset_eq:Nc
\l_char_special_seq
\ior_str_get:NNF
\l_tmpa_seq
\box_gresize_to_wd:cn
\fparray_gzero:N
\str_range_ignore_spaces:nnn
\token_if_math_toggle:NF
\char_set_catcode_alignment:n
\exp_args:Nccc
\str_gput_left:cV
\prop_get:cnN
\peek_after:Nw
\tl_if_eq:NcT
\coffin_gscale:cnn
\seq_mapthread_function:NNN
\token_if_math_superscript:NTF
\vbox_gset_to_ht:Nnw
\str_replace_all:Nnn
\muskip_sub:cn
\str_tail_ignore_spaces:n
\prop_put:NnV
\int_value:w
\tl_greplace_all:Nnn
\regex_const:Nn
\hbox_gset_to_wd:cnn
\str_set:NV
\str_case:nvF
\text_declare_expand_equivalent:cn
\prop_remove:NV
\clist_if_empty_p:n
\int_to_base:nn
\regex_split:nnNTF
\use_iv:nnnn
\clist_if_exist:NTF
\str_if_eq:NcT
\intarray_show:c
\fp_log:n
\c_one_degree_fp
\skip_gadd:Nn
\prop_map_inline:cn
\exp_args:NNnx
\cs_new_eq:NN
\peek_meaning:NT
\hbox_set:Nn
\tl_if_single:nF
\prop_count:N
\ior_get_term:nN
\coffin_grotate:Nn
\tl_reverse_items:n
\token_if_eq_catcode:NNT
\str_put_right:NV
\cs_set_nopar:cpx
\int_eval:w
\exp_last_unbraced:NNo
\cs_if_free:NT
\int_log:N
\tl_put_right:co
\dim_do_while:nNnn
\regex_extract_once:NnNT
\skip_gzero_new:c
\exp_args:NVo
\exp_args:NcV
\coffin_scale:Nnn
\tl_greverse:N
\seq_gclear_new:c
\str_put_left:cx
\int_from_hex:n
\str_gput_right:cV
\seq_gset_from_clist:cN
\seq_gpush:cn
\seq_get:cN
\str_if_eq:noF
\ior_log_list:
\use_i:nnn
\tl_if_exist:NTF
\str_case:nn
\hbox_to_wd:nn
\int_step_inline:nnn
\int_to_roman:n
\seq_if_in:cVF
\dim_log:N
\skip_add:Nn
\str_gput_right:Nx
\int_step_variable:nnnNn
\tl_if_in:cnTF
\tl_if_blank:eF
\box_gclear:c
\hcoffin_gset:Nw
\seq_mapthread_function:NcN
\msg_none:nnn
\box_gresize_to_wd:Nn
\dim_case:nn
\fp_do_while:nNnn
\str_put_left:NV
\str_if_exist:NT
\bool_do_until:nn
\int_show:c
\str_map_function:nN
\tl_to_str:n
\msg_info:nnxxxx
\color_ensure_current:
\skip_show:c
\str_greplace_once:cnn
\box_if_vertical:NTF
\muskip_log:n
\prop_get:coNF
\tl_tail:n
\prop_put:Noo
\tl_log:n
\int_set_eq:Nc
\box_gscale:cnn
\tl_map_variable:cNn
\prop_gput:con
\tl_clear_new:c
\fp_set:Nn
\muskip_if_exist_p:c
\box_if_exist:NT
\tl_set:Nn
\exp_args:Nnnx
\box_clear:N
\seq_gpop_right:NNTF
\clist_remove_all:Nn
\coffin_gset_horizontal_pole:Nnn
\clist_greverse:N
\exp_args:Ncno
\tl_gset_rescan:Nnn
\c_right_brace_str
\bool_set_eq:NN
\seq_if_in:cnTF
\g_tmpa_muskip
\seq_if_in:cVTF
\cs_gset_protected:Nn
\muskip_log:N
\tl_build_begin:N
\msg_gset:nnn
\bool_show:n
\bool_lazy_all_p:n
\prop_set_eq:Nc
\tl_set:cf
\exp_last_unbraced:NnNo
\str_set:Nn
\seq_gpop_right:NN
\token_if_protected_macro:NF
\file_get:nnNF
\exp_args:Nfo
\muskip_zero:N
\file_if_exist:nF
\token_if_mathchardef_p:N
\clist_rand_item:c
\seq_gset_from_function:NnN
\clist_if_in:NnF
\msg_critical:nnnnnn
\msg_error:nnx
\seq_if_in:coTF
\skip_if_exist:cTF
\tl_gset:Nf
\seq_get:cNTF
\dim_compare:nNnF
\box_gclear_new:c
\regex_match:NnT
\prop_get:NVNT
\quark_if_nil:nT
\hbox_unpack:N
\tl_if_head_is_space:nF
\token_if_dim_register_p:N
\str_log:c
\coffin_set_vertical_pole:Nnn
\exp_not:o
\int_if_exist_p:N
\clist_map_inline:Nn
\bool_if_exist:NT
\msg_none:nnnnn
\sys_if_shell_restricted:T
\str_set:cV
\keys_set_known:nVnN
\fp_to_scientific:N
\g_tmpa_ior
\vbox_to_ht:nn
\exp_args:Nnnf
\g_file_curr_dir_str
\seq_pop_left:cNTF
\tl_if_single_token:nT
\cs_new:Nx
\use:nn
\clist_if_in:NVT
\str_case:VnTF
\seq_concat:NNN
\token_if_protected_macro:NTF
\seq_const_from_clist:Nn
\quark_if_no_value_p:n
\color_group_end:
\tl_map_function:NN
\sys_if_engine_xetex:TF
\msg_log:nnnn
\if_charcode:w
\iow_log:n
\msg_critical:nnnn
\seq_if_in:NxT
\keys_set_groups:nnn
\char_set_sfcode:nn
\cs_gset_protected:cx
\regex_extract_once:nnN
\str_gset_eq:cN
\cs_set_eq:cc
\seq_put_left:cn
\quark_if_nil:VF
\coffin_dp:N
\str_map_variable:nNn
\char_show_value_uccode:n
\token_if_math_superscript_p:N
\box_resize_to_ht_plus_dp:Nn
\cs_set_protected_nopar:cpn
\prop_get:NoNF
\str_gset:Nx
\tl_if_empty:NTF
\str_if_empty:NTF
\quark_if_recursion_tail_stop_do:nn
\clist_set:NV
\tl_replace_all:Nnn
\l_tmpb_box
\tl_build_gput_right:Nx
\msg_expandable_error:nnf
\muskip_sub:Nn
\box_gset_to_last:c
\prop_put:cVV
\clist_map_break:n
\char_value_uccode:n
\int_gdecr:c
\str_if_eq:vnTF
\char_gset_active_eq:nc
\box_autosize_to_wd_and_ht_plus_dp:Nnn
\ProvidesExplPackage
\quark_if_nil:VTF
\exp_args:Nv
\keys_if_choice_exist_p:nnn
\msg_warning:nnnnnn
\tl_if_head_eq_meaning:nNTF
\skip_if_finite_p:n
\tl_set:NV
\clist_gpush:cn
\prop_put:con
\c_empty_box
\file_get:nnNTF
\clist_get:cNT
\tl_if_empty:cF
\tl_reverse:c
\tl_item:cn
\quark_if_recursion_tail_stop_do:on
\ior_map_break:
\file_get:nnNT
\ior_get:NN
\tl_put_left:Nx
\seq_put_left:Nv
\dim_until_do:nn
\prop_if_in:coF
\str_if_empty:NF
\tl_if_eq:NcTF
\box_log:cnn
\str_declare_eight_bit_encoding:nnn
\file_get_full_name:VNTF
\muskip_set:cn
\clist_map_function:cN
\fp_compare:nNnTF
\dim_use:c
\ior_close:N
\cs_gset_eq:Nc
\hbox_unpack:c
\cs_set:Npx
\token_if_math_subscript:NT
\intarray_gzero:N
\exp_stop_f:
\seq_shuffle:c
\skip_add:cn
\str_gput_left:cx
\fp_to_int:n
\if_true:
\c_e_fp
\prop_gput:NVV
\prop_get:coNT
\seq_gput_right:cx
\seq_pop:NN
\bool_not_p:n
\tl_if_blank:nT
\ior_open:NnT
\cs_new_protected_nopar:cpn
\g_tmpa_int
\tl_if_in:noTF
\vbox_gset_split_to_ht:NNn
\seq_gset_map:NNn
\tl_if_blank:VT
\coffin_if_exist:cTF
\tl_if_head_is_space:nT
\seq_get_left:NNT
\seq_get:NNTF
\prop_rand_key_value:c
\prop_gput:Nnx
\box_if_empty:NTF
\or:
\peek_charcode_collect_inline:Nn
\tl_if_novalue:nTF
\l_tmpa_regex
\bool_do_while:nn
\fp_const:cn
\box_set_viewport:Nnnnn
\box_resize_to_wd_and_ht:cnn
\tl_count:c
\token_if_long_macro:NT
\seq_if_in:NVTF
\iow_open:Nn
\muskip_add:cn
\box_clear_new:N
\c_sys_jobname_str
\coffin_gattach:cnnNnnnn
\coffin_gset_horizontal_pole:cnn
\skip_if_exist:NTF
\msg_error:nnn
\mode_leave_vertical:
\sys_if_engine_uptex:TF
\prg_set_protected_conditional:Npnn
\seq_reverse:N
\g_tmpb_prop
\tl_if_blank:oTF
\seq_gpop:NNTF
\char_show_value_sfcode:n
\clist_set:cV
\c_circumflex_str
\cs_set_nopar:Nn
\cs_set_protected_nopar:Npn
\box_gset_eq:cc
\cs_replacement_spec:N
\peek_catcode_remove_ignore_spaces:NF
\sys_if_engine_uptex:F
\coffin_if_exist_p:N
\use_ii:nn
\regex_match:nnTF
\peek_charcode_remove:NTF
\tl_if_single_token:nF
\seq_gpush:cV
\ior_open:NnTF
\box_resize_to_wd:Nn
\box_gset_to_last:N
\tl_if_empty:oT
\bool_do_until:Nn
\sys_get_shell:nnN
\prop_get:NnNF
\str_case:onT
\clist_const:Nn
\skip_const:cn
\fp_until_do:nNnn
\keys_set_groups:nnv
\box_if_empty:cT
\seq_greverse:c
\seq_log:c
\muskip_if_exist:NTF
\exp_args:NNx
\str_if_eq:VVTF
\tl_put_right:Nx
\seq_if_in:cxF
\cs_set_protected:cn
\str_put_right:cn
\dim_set:Nn
\box_gresize_to_wd_and_ht_plus_dp:Nnn
\tl_count:o
\token_if_protected_long_macro:NF
\int_sub:Nn
\tl_range:Nnn
\legacy_if:nTF
\g_tmpa_prop
\exp_args:NNc
\coffin_show_structure:N
\tl_gset:cn
\int_set_eq:NN
\ior_if_eof:NTF
\sys_if_engine_uptex:T
\tl_gconcat:NNN
\c_space_token
\box_show:Nnn
\keys_set:nn
\keys_set_filter:nnVnN
\int_gzero:N
\q_recursion_tail
\tl_if_exist:cT
\prg_break:
\tl_gclear_new:N
\clist_gclear_new:c
\token_if_toks_register:NT
\tl_if_head_eq_charcode_p:fN
\dim_to_fp:n
\str_case:nnTF
\regex_split:NnNTF
\box_show:N
\regex_replace_all:NnNTF
\exp_last_two_unbraced:Noo
\tl_if_head_is_N_type:nT
\msg_show:nnn
\fp_gsub:Nn
\box_set_eq_drop:cN
\msg_fatal:nnxxx
\clist_if_in:cnTF
\text_lowercase:n
\clist_gset:cn
\hcoffin_gset_end:
\bool_until_do:nn
\use_i:nn
\muskip_if_exist:NT
\seq_gpop_left:cNF
\tl_build_get:NN
\cs_if_exist:NTF
\clist_gclear:N
\clist_set_eq:cc
\seq_gshuffle:N
\seq_count:N
\box_gresize_to_ht_plus_dp:cn
\coffin_grotate:cn
\prop_get:NoNT
\seq_gsort:Nn
\token_if_eq_catcode:NNF
\seq_gpop_right:NNT
\dim_use:N
\coffin_gclear:N
\prg_generate_conditional_variant:Nnn
\coffin_display_handles:Nn
\str_head:c
\vbox_gset_to_ht:cnw
\token_if_active:NF
\cs_new_nopar:cn
\clist_gpop:NNTF
\exp_args:NNo
\char_set_catcode_math_toggle:N
\cs_gset_nopar:cpn
\keys_set_known:noN
\tl_gset_rescan:cno
\seq_gpop:cNF
\box_gset_eq_drop:Nc
\coffin_gset_vertical_pole:cnn
\cs_gset:cx
\msg_fatal:nnnnn
\clist_put_left:Nn
\iow_wrap:nxnN
\vbox_set:cn
\str_count:N
\int_use:c
\tl_gput_left:cV
\q_nil
\hbox_gset_to_wd:Nnw
\prg_new_protected_conditional:Npnn
\msg_critical:nn
\iow_shipout:Nn
\bool_if:NT
\quark_if_no_value:NTF
\tl_range_unbraced:cnn
\seq_put_right:Nn
\cs_gset:Nx
\tl_if_eq:ccF
\lua_shipout:n
\seq_if_in:cnT
\bool_gset_false:c
\tl_if_head_eq_catcode:nNF
\fp_to_scientific:n
\if_box_empty:N
\sys_get_shell:nnNT
\prop_log:c
\exp_args:Nee
\str_gremove_once:Nn
\peek_meaning:NTF
\seq_gset_from_clist:cc
\clist_const:Nx
\msg_log:nnnnn
\seq_gpop:cNTF
\dim_step_variable:nnnNn
\debug_resume:
\clist_clear:c
\cs_new_protected:Npx
\fparray_item_to_tl:Nn
\seq_gset_eq:cN
\muskip_set:Nn
\int_zero_new:N
\clist_sort:Nn
\clist_push:No
\hcoffin_set_end:
\bool_xor:nnT
\prop_gpop:NoN
\msg_new:nnn
\clist_gput_left:co
\fparray_item:Nn
\prop_set_eq:cc
\clist_gset_eq:cN
\peek_N_type:F
\box_resize_to_ht:Nn
\cs_gset:Nn
\exp_args:Nf
\l_tmpa_box
\str_if_eq:VVF
\exp_args:Nccx
\seq_gset_from_clist:cn
\seq_if_in:cvTF
\fp_to_int:N
\prop_gpop:NnNT
\box_move_down:nn
\tl_gconcat:ccc
\exp_args:Noox
\regex_extract_all:NnNT
\fp_compare:nTF
\msg_if_exist_p:nn
\peek_meaning_remove:NF
\ior_open:Nn
\str_put_left:Nn
\seq_gremove_duplicates:N
\file_get_hex_dump:nnnNTF
\cs_set_protected:cpn
\mode_if_vertical_p:
\l_char_active_seq
\tl_trim_spaces:c
\msg_module_type:n
\clist_map_variable:nNn
\token_if_int_register_p:N
\coffin_attach:cnncnnnn
\tl_gset_rescan:Nnx
\dim_zero_new:c
\int_to_arabic:n
\coffin_set_eq:Nc
\prop_gclear:c
\seq_rand_item:c
\msg_critical:nnnnn
\tl_if_empty:NF
\tl_build_put_right:Nn
\c_inf_fp
\clist_clear_new:N
\exp_args:NNNV
\regex_split:NnN
\mode_if_inner:F
\dim_if_exist:NTF
\tl_set:No
\int_gset:Nn
\coffin_gset_eq:cc
\skip_if_finite:nTF
\tl_remove_once:cn
\str_const:Nn
\clist_push:cn
\file_full_name:n
\dim_case:nnT
\bool_if_exist:cT
\ior_open:cnT
\prop_get:NVNF
\tl_if_in:cnF
\int_eval:n
\tl_if_empty:NT
\vbox_unpack_drop:N
\seq_get_right:NNF
\prop_if_exist_p:N
\int_div_truncate:nn
\use_none_delimit_by_s_stop:w
\if_case:w
\seq_gpush:Nv
\skip_show:n
\if_vbox:N
\prop_put_if_new:cnn
\coffin_gjoin:cnnNnnnn
\exp_last_unbraced:Nco
\cs_new_protected_nopar:Npn
\iow_now:cn
\l_text_accents_tl
\box_gset_ht:cn
\box_set_eq_drop:cc
\box_gset_wd:Nn
\box_scale:cnn
\c_ampersand_str
\char_lowercase:N
\tl_map_tokens:nn
\str_tail:n
\tl_set_rescan:Nno
\if:w
\coffin_typeset:Nnnnn
\keys_set:nv
\tl_if_single:NTF
\fp_sub:Nn
\msg_expandable_error:nnff
\token_if_group_begin:NF
\prop_if_in:cVTF
\tl_use:c
\str_gset_eq:cc
\bool_if:cF
\reverse_if:N
\tl_put_left:cn
\coffin_if_exist:cF
\prop_get:cVN
\coffin_gresize:Nnn
\coffin_attach:cnnNnnnn
\prg_new_conditional:Nnn
\dim_zero:N
\muskip_use:N
\cs_generate_variant:Nn
\int_min:nn
\token_if_cs_p:N
\coffin_set_horizontal_pole:cnn
\intarray_new:cn
\box_rotate:cn
\box_if_vertical:cF
\exp_args:Noof
\bool_gset_eq:NN
\vbox_set:Nn
\char_set_catcode_invalid:n
\tl_if_novalue:nF
\tl_set:cv
\msg_log:nnnnnn
\box_log:c
\fp_const:Nn
\coffin_rotate:cn
\tl_if_single:NF
\str_item:nn
\keys_if_choice_exist:nnnT
\fp_gadd:Nn
\msg_show_item:n
\iow_now:Nx
\int_gset_eq:Nc
\coffin_typeset:cnnnn
\clist_if_in:nnF
\msg_warning:nnnnn
\bool_if_p:N
\clist_show:n
\use_i:nnnn
\muskip_use:c
\sys_if_shell_restricted:TF
\clist_put_right:No
\seq_set_eq:Nc
\quark_if_no_value_p:N
\tl_map_function:cN
\prop_log:N
\sys_load_backend:n
\clist_map_break:
\coffin_join:Nnncnnnn
\str_concat:ccc
\bool_case_true:nT
\char_set_catcode_other:n
\int_use:N
\seq_show:N
\box_if_empty:NT
\seq_put_left:NV
\quark_if_nil:NT
\prop_if_in_p:cn
\seq_if_in:NvT
\tl_if_exist_p:N
\c_sys_backend_str
\skip_gadd:cn
\iow_term:x
\file_get_size:nNTF
\seq_map_variable:ccn
\msg_expandable_error:nnnnn
\cs_new_protected:cpx
\tl_concat:ccc
\regex_show:n
\str_const:Nx
\int_set_eq:cN
\str_case:VnT
\exp_args:NcVV
\c_empty_coffin
\token_if_expandable:NTF
\vbox_set_split_to_ht:ccn
\tl_head:f
\cs_new:Npx
\seq_if_empty_p:N
\cs_set_protected_nopar:cn
\int_if_exist:NT
\seq_put_left:No
\token_if_protected_long_macro:NTF
\c_sys_day_int
\dim_if_exist:NT
\prop_clear:c
\str_uppercase:n
\seq_gpop:cNT
\tl_gset:cV
\file_get_hex_dump:nNTF
\fp_set_eq:cc
\file_get_mdfive_hash:nN
\ior_show_list:
\cs_gset:cpn
\token_if_eq_charcode:NNF
\l_tmpa_clist
\fp_show:N
\use_none:n
\str_map_break:
\clist_gpop:cNTF
\hbox_set_to_wd:cnn
\file_get_size:nN
\tl_if_empty:oTF
\box_gresize_to_ht_plus_dp:Nn
\token_if_parameter:NTF
\sys_get_shell:nnNTF
\l_tmpa_str
\muskip_gzero:c
\fp_compare:nF
\skip_horizontal:n
\prop_put:cnn
\clist_gpush:co
\cs_if_free:cTF
\quark_if_nil:nTF
\msg_redirect_name:nnn
\prop_const_from_keyval:Nn
\clist_if_empty:nT
\cs_new_eq:cc
\peek_catcode:NTF
\use_none_delimit_by_q_recursion_stop:w
\g_tmpb_seq
\fp_abs:n
\cs_new_nopar:cpx
\l_file_search_path_seq
\muskip_gsub:Nn
\skip_if_finite:nT
\skip_gzero_new:N
\box_if_horizontal:NT
\str_map_inline:Nn
\int_zero:N
\cs_new:cx
\seq_get:NNT
\token_if_muskip_register_p:N
\intarray_rand_item:N
\tl_if_exist:cF
\fp_until_do:nn
\prop_put:Nno
\clist_gput_left:cn
\clist_if_in:noT
\prop_gput_if_new:cnn
\token_if_int_register:NT
\peek_charcode_ignore_spaces:NT
\vbox_unpack:N
\c_sys_year_int
\flag_if_raised_p:n
\muskip_gset_eq:Nc
\l_tmpa_dim
\tl_trim_spaces_apply:nN
\tl_remove_once:Nn
\seq_gpop_right:NNF
\clist_new:N
\seq_put_right:cx
\intarray_count:c
\text_titlecase:n
\exp_args:cc
\iow_close:c
\tl_if_head_eq_catcode:oNT
\bool_case_false:n
\msg_none:nnxx
\q_mark
\exp_last_unbraced:NNNV
\skip_sub:Nn
\tl_gset:NV
\if_cs_exist:N
\clist_gset_eq:cc
\tl_if_blank_p:n
\tl_gset_rescan:Nno
\tl_put_right:cV
\vbox_gset:Nn
\peek_catcode_remove:NF
\str_if_exist_p:c
\msg_show_item_unbraced:nn
\fp_to_scientific:c
\muskip_zero:c
\exp_args:NNoo
\exp:w
\box_set_trim:Nnnnn
\g_tmpa_fp
\int_sub:cn
\cs_gset_protected:cn
\c_atsign_str
\tl_set_rescan:cno
\flag_log:n
\prop_if_in:cVT
\tl_map_inline:nn
\coffin_log_structure:N
\str_count_spaces:n
\msg_show:nn
\char_set_catcode_space:N
\str_uppercase:f
\c_space_tl
\regex_match:NnF
\seq_push:cx
\seq_set_from_inline_x:Nnn
\tl_gput_left:Nn
\g_tmpa_dim
\seq_if_empty:cF
\intarray_count:N
\keys_set_known:no
\box_show:cnn
\tl_gclear:c
\clist_gset_from_seq:cc
\tl_set:cV
\dim_add:cn
\clist_gset_eq:NN
\keys_set_filter:nnonN
\tl_if_single_p:c
\str_put_right:cV
\tl_reverse:V
\bool_case_true:n
\peek_N_type:TF
\box_show:c
\hbox_gset:cn
\clist_map_variable:cNn
\keys_set_known:nvnN
\use:n
\quark_if_nil_p:n
\bool_if:nT
\seq_gput_right:cv
\prop_get:NoN
\file_get_timestamp:nNT
\str_if_in:NnF
\tl_gput_left:No
\skip_if_exist_p:c
\exp_last_unbraced:Ne
\prop_gput:NnV
\seq_gput_left:cV
\tl_gtrim_spaces:N
\use_i_ii:nnn
\clist_item:nn
\int_do_until:nn
\box_gautosize_to_wd_and_ht_plus_dp:Nnn
\msg_info:nnnn
\msg_critical:nnxxx
\skip_if_exist:cT
\int_zero:c
\box_autosize_to_wd_and_ht_plus_dp:cnn
\prg_break:n
\str_gput_left:cn
\seq_pop_left:NNT
\peek_catcode_ignore_spaces:NF
\peek_catcode_remove_ignore_spaces:NTF
\prop_if_in_p:Nn
\int_decr:c
\exp_args:NNNo
\str_tail:N
\sys_if_rand_exist:TF
\skip_zero:c
\box_set_ht:Nn
\str_if_eq:NcTF
\seq_pop_left:NNTF
\tl_if_eq:NNTF
\clist_if_in:cVF
\tl_show:n
\str_use:c
\keys_set_known:nnN
\str_show:N
\sort_return_same:
\box_gset_eq_drop:NN
\dim_sub:cn
\bool_gset_inverse:c
\clist_log:n
\c_catcode_letter_token
\box_gclear:N
\msg_expandable_error:nn
\seq_indexed_map_inline:Nn
\sys_get_shell:nnNF
\str_map_inline:cn
\bool_xor_p:nn
\exp_args:NNV
\prg_break_point:Nn
\str_gremove_all:cn
\tl_clear:N
\seq_gconcat:NNN
\char_set_catcode_ignore:n
\int_case:nn
\exp_args:Ncoo
\exp_not:e
\int_gadd:Nn
\if_meaning:w
\prg_set_conditional:Nnn
\tl_gset:No
\char_str_foldcase:N
\str_range:Nnn
\cs_if_eq:NNF
\char_str_uppercase:N
\flag_if_raised:nTF
\regex_extract_all:NnN
\file_input:n
\int_do_until:nNnn
\box_if_empty:cTF
\dim_set_eq:cN
\seq_use:Nnnn
\clist_if_in:nVTF
\mode_if_horizontal:TF
\muskip_gadd:cn
\vbox_gset_to_ht:Nnn
\ior_str_get:NN
\quark_if_nil:oF
\box_log:N
\tl_if_eq:NNT
\c_one_int
\sys_load_debug:
\tl_rescan:nn
\prop_if_empty_p:N
\cs_gset_nopar:cpx
\clist_show:N
\cs_set_protected:Nx
\clist_get:NNTF
\str_if_eq:eeTF
\exp_args:Nff
\box_if_empty_p:c
\hcoffin_set:cn
\seq_gset_from_clist:Nc
\exp_last_unbraced:No
\seq_gset_from_clist:NN
\l_peek_token
\dim_gadd:Nn
\box_gset_trim:cnnnn
\c_catcode_other_token
\l_tmpb_seq
\cs_gset_protected_nopar:Npx
\seq_item:cn
\str_if_empty_p:N
\tl_replace_all:cnn
\int_step_inline:nnnn
\c_backslash_str
\tl_if_single_p:N
\prop_pop:cnNF
\seq_gremove_all:cn
\box_move_right:nn
\tl_if_eq:cNTF
\seq_gconcat:ccc
\hbox_gset_end:
\seq_push:co
\clist_item:Nn
\exp_args:Ncnx
\iow_shipout_x:cx
\clist_gsort:Nn
\c_math_superscript_token
\seq_gput_left:Nv
\fp_to_decimal:c
\token_if_muskip_register:NF
\tl_if_head_eq_catcode_p:oN
\prop_gremove:Nn
\clist_count:N
\muskip_if_exist:cTF
\token_if_protected_macro_p:N
\muskip_gset:Nn
\clist_use:cnnn
\cs_gset_protected_nopar:Nx
\coffin_gattach:Nnncnnnn
\str_map_variable:NNn
\str_if_eq:onF
\bool_if:nF
\file_if_exist_input:nF
\clist_reverse:c
\tl_put_left:cV
\prop_get:NVNTF
\sys_rand_seed:
\char_str_titlecase:N
\clist_use:cn
\tl_if_eq:NNF
\str_gclear:N
\ior_open:cn
\prop_gremove:cV
\str_count_spaces:N
\box_scale:Nnn
\quark_if_recursion_tail_stop_do:Nn
\bool_if:NF
\int_compare:nF
\seq_pop_left:NNF
\token_if_toks_register:NF
\quark_if_recursion_tail_break:nN
\clist_if_exist:NT
\char_set_catcode_end_line:n
\clist_push:NV
\seq_set_eq:cN
\hcoffin_set:Nw
\seq_if_exist_p:N
\seq_if_empty_p:c
\str_if_eq:VVT
\l_tmpb_bool
\msg_none:nnxxxx
\tl_gset:Nx
\dim_set_eq:Nc
\vbox_set:cw
\tl_if_blank:oF
\tl_rand_item:N
\seq_get:NN
\clist_gpop:NN
\clist_push:Nx
\ior_str_map_inline:Nn
\fp_gset:cn
\dim_gzero:c
\c_catcode_other_space_tl
\tl_build_put_left:Nx
\tl_gput_right:cn
\cs_gset:cpx
\token_if_mathchardef:NF
\seq_gpop_left:NNF
\int_if_odd:nTF
\clist_if_empty_p:c
\tl_if_head_eq_charcode:fNTF
\seq_gclear_new:N
\seq_set_from_function:NnN
\skip_log:c
\prop_put:cnx
\clist_set_eq:NN
\clist_get:cNF
\tl_if_head_eq_charcode:nNTF
\clist_count:c
\c_sys_platform_str
\cs_gset_protected_nopar:cx
\file_get:nnN
\c_dollar_str
\tl_if_empty_p:V
\mode_if_math_p:
\quark_if_no_value:NT
\cs_if_exist_p:c
\iow_new:N
\text_titlecase_first:nn
\seq_gput_right:co
\debug_on:n
\tl_analysis_map_inline:Nn
\c_catcode_active_space_tl
\keys_if_exist:nnF
\str_if_eq:nnF
\bool_case_true:nTF
\tl_build_gput_left:Nn
\tl_tail:V
\clist_greverse:c
\token_to_str:c
\l_tmpb_clist
\tl_gset_eq:cc
\tl_put_right:NV
\seq_push:Nx
\skip_use:N
\quark_if_nil:NTF
\str_if_eq:nvT
\msg_log:nnxxx
\str_remove_once:Nn
\tl_put_right:Nn
\muskip_if_exist:cT
\str_if_eq:NNF
\use_none:nnnnnnnnn
\box_if_empty:cF
\str_if_in:cnF
\muskip_show:c
\int_gsub:Nn
\exp_args:NNox
\clist_put_left:Nx
\muskip_const:cn
\clist_gconcat:ccc
\skip_if_eq:nnF
\prop_if_in:cnT
\exp_args:Nno
\int_mod:nn
\vbox_unpack:c
\msg_log:nnn
\prop_set_from_keyval:Nn
\tl_to_str:N
\box_resize_to_wd_and_ht_plus_dp:Nnn
\muskip_gsub:cn
\prop_set_from_keyval:cn
\c_log_iow
\regex_replace_once:NnNF
\cs_new_nopar:Nn
\token_if_alignment:NF
\clist_if_in:nnT
\seq_gpop_right:cNT
\msg_error:nnnn
\bool_show:c
\str_gremove_all:Nn
\str_if_eq_p:on
\l_tmpb_skip
\dim_gset:cn
\clist_pop:NN
\box_use:c
\int_step_function:nnnN
\vcoffin_gset:cnw
\token_if_eq_meaning:NNTF
\exp_not:n
\clist_gput_left:cx
\muskip_new:c
\prop_put:Non
\tl_build_end:N
\seq_gset_eq:cc
\seq_if_in:NvF
\seq_map_break:
\skip_if_eq:nnT
\g_msg_module_type_prop
\clist_if_empty:cT
\str_if_eq:nvF
\fp_compare_p:nNn
\regex_count:nnN
\sys_if_shell_restricted_p:
\prop_if_in:NnF
\clist_rand_item:N
\fp_min:nn
\coffin_set_horizontal_pole:Nnn
\seq_rand_item:N
\skip_gset:Nn
\if_false:
\prop_put:coo
\g_tmpb_tl
\tl_map_inline:Nn
\bool_set_true:N
\seq_gremove_duplicates:c
\skip_gset_eq:NN
\muskip_eval:n
\regex_extract_once:NnNTF
\coffin_set_vertical_pole:cnn
\exp_args:Ncco
\prop_gclear:N
\char_value_mathcode:n
\file_get_size:nNT
\seq_pop:cNT
\if_mode_inner:
\msg_show_eval:Nn
\sys_if_output_dvi:F
\str_greplace_all:Nnn
\str_case:VnF
\fi:
\exp_last_unbraced:NNNNf
\prop_if_in:NnT
\tl_trim_spaces:o
\dim_compare:nNnT
\sys_if_output_dvi_p:
\tl_set_eq:Nc
\str_if_eq:cNT
\seq_get_left:cNTF
\cs_if_exist_use:NF
\token_if_group_end:NF
\hbox:n
\prop_gput:cnx
\bool_if_exist:cF
\coffin_attach:Nnncnnnn
\seq_gpop:NNT
\seq_set_map:NNn
\keys_set_filter:nno
\g_peek_token
\msg_log:nnx
\int_if_odd:nT
\text_lowercase:nn
\iow_term:n
\tl_gremove_all:cn
\char_to_utfviii_bytes:n
\flag_if_raised:nT
\prop_if_exist:cF
\muskip_gset:cn
\peek_catcode_remove_ignore_spaces:NT
\sys_if_shell_unrestricted:TF
\msg_fatal:nnxx
\msg_show:nnx
\muskip_gzero:N
\seq_if_in:NVT
\l_tmpb_dim
\text_uppercase:nn
\int_div_round:nn
\seq_get_right:cN
\coffin_resize:Nnn
\exp_args:NnV
\c_hash_str
\seq_gput_left:NV
\sys_if_shell_unrestricted_p:
\cs_generate_from_arg_count:cNnn
\prop_gpop:NnN
\tl_if_eq_p:cN
\cs_new_protected:Nx
\cs_if_exist_use:NT
\coffin_set_eq:cN
\g_tmpa_box
\str_if_exist:cF
\token_if_protected_long_macro:NT
\token_if_eq_charcode:NNT
\str_case_e:nnTF
\muskip_set_eq:Nc
\tl_if_head_is_group_p:n
\keys_set_filter:nnvnN
\muskip_show:n
\str_map_break:n
\use_none:nnnnnnnn
\token_if_toks_register:NTF
\tl_range_unbraced:nnn
\sys_if_output_pdf:T
\hbox_gset_to_wd:cnw
\clist_set:Nn
\tl_if_in:cnT
\tl_if_single:cT
\clist_show:c
\coffin_gclear:c
\int_add:Nn
\seq_if_empty:NT
\bool_lazy_all:nTF
\tl_build_gbegin:N
\c_max_dim
\tl_set_eq:cN
\bool_gset_eq:Nc
\c_empty_clist
\bool_gset_false:N
\tl_greplace_all:cnn
\token_if_parameter:NF
\clist_gclear_new:N
\clist_get:NNT
\token_if_active_p:N
\int_sign:n
\exp_end_continue_f:w
\clist_set:No
\prop_pop:cnNTF
\clist_reverse:N
\quark_if_no_value:cTF
\text_uppercase:n
\skip_if_finite:nF
\msg_expandable_error:nnfff
\char_foldcase:N
\cs_gset_protected:Nx
\cs_if_free:NTF
\vbox_gset_split_to_ht:ccn
\str_if_eq:VnF
\tl_clear_new:N
\cs_gset_nopar:Nn
\vcoffin_set:cnw
\str_tail:c
\text_declare_expand_equivalent:Nn
\sys_if_platform_unix:TF
\msg_error:nn
\sys_if_shell:TF
\cs_new:Npn
\file_get_hex_dump:nN
\bool_if_exist_p:N
\sys_shell_now:x
\cs_new_protected_nopar:cx
\clist_map_inline:cn
\token_if_dim_register:NT
\muskip_const:Nn
\seq_gput_right:Nn
\keys_set_known:nnnN
\l_keys_path_str
\c_math_subscript_token
\clist_set:cn
\prop_gremove:cn
\seq_if_in:cvT
\regex_match:nnF
\skip_if_exist:NF
\g_tmpa_coffin
\int_to_hex:n
\token_if_group_end_p:N
\prop_const_from_keyval:cn
\tl_greverse:c
\cs_set_eq:Nc
\msg_set:nnn
\seq_get_right:cNT
\file_hex_dump:n
\box_set_eq:Nc
\exp_args:Ncv
\char_set_catcode_escape:n
\seq_push:Nv
\fp_to_dim:c
\file_parse_full_name:VNNN
\peek_N_type:T
\char_show_value_lccode:n
\tl_const:cn
\group_insert_after:N
\int_const:cn
\box_gset_eq:NN
\vbox_to_zero:n
\str_case:nV
\use_i_delimit_by_q_nil:nw
\seq_get_left:cN
\fp_to_decimal:n
\keys_set_known:nV
\tl_clear:c
\cs_show:c
\prop_set_eq:cN
\tl_map_break:n
\dim_max:nn
\seq_gput_left:No
\peek_charcode:NTF
\box_if_horizontal_p:c
\bool_case_false:nTF
\token_if_other:NF
\str_const:cn
\peek_catcode_ignore_spaces:NTF
\str_concat:NNN
\cs_new_protected_nopar:Nn
\file_get_full_name:VNF
\str_foldcase:n
\hcoffin_set:cw
\seq_put_right:NV
\bool_set:cn
\cs_new_protected_nopar:cn
\cs_gset_protected_nopar:cpx
\token_if_skip_register:NF
\clist_if_in:NnT
\intarray_log:c
\msg_none:nnx
\box_if_empty_p:N
\ior_open:cnTF
\l_tmpa_muskip
\str_gset:cx
\prop_if_exist:NTF
\clist_gpush:Nn
\l_tmpb_regex
\token_to_str:N
\msg_critical:nnxx
\str_if_empty:cTF
\seq_map_variable:NNn
\box_if_exist:NF
\tl_gremove_once:cn
\g_tmpa_tl
\box_if_horizontal:NF
\cs_new_protected:Npn
\dim_if_exist:cT
\sys_shell_shipout:x
\seq_gpop_right:cNF
\ior_str_map_variable:NNn
\box_new:N
\str_if_exist:NTF
\c_parameter_token
\str_remove_all:cn
\prop_map_function:cN
\seq_show:c
\dim_gzero:N
\cs_if_free:NF
\cs_undefine:c
\box_set_viewport:cnnnn
\iow_shipout:Nx
\clist_gpop:NNF
\hbox_set:cn
\cs_new_nopar:Nx
\prop_if_in:NVTF
\quark_if_nil:oT
\quark_if_no_value:nTF
\seq_gput_left:cn
\char_generate:nn
\exp_not:v
\tl_if_blank:VF
\use_none:nnnnnnn
\iow_close:N
\muskip_zero_new:c
\tl_gsort:Nn
\dim_new:N
\msg_show:nnnnnn
\tl_sort:cn
\str_gset_convert:Nnnn
\tl_if_blank:oT
\g_tmpb_int
\seq_set_from_clist:cc
\lua_shipout_e:n
\l_tmpb_int
\int_incr:N
\int_log:c
\exp_last_unbraced:NNNNo
\text_titlecase_first:n
\dim_add:Nn
\sys_if_engine_ptex_p:
\intarray_const_from_clist:Nn
\clist_if_exist_p:c
\keys_if_exist_p:nn
\str_gconcat:ccc
\str_gput_left:NV
\char_set_catcode:nn
\token_if_macro:NF
\fp_zero:N
\skip_gzero:c
\vbox_set_split_to_ht:cNn
\clist_get:cNTF
\tl_put_left:Nn
\regex_replace_once:NnNTF
\char_show_value_mathcode:n
\tl_if_single:nT
\msg_none:nnnnnn
\box_gset_dp:Nn
\tl_if_in:VnF
\muskip_gset_eq:cc
\prg_set_conditional:Npnn
\tl_gput_right:NV
\seq_get_left:cNT
\l_tmpa_coffin
\box_if_vertical:cTF
\char_set_mathcode:nn
\prop_if_empty:NF
\use_none:nn
\fp_if_exist:NTF
\if_catcode:w
\c_zero_dim
\box_wd:c
\box_set_eq_drop:Nc
\int_log:n
\group_end:
\token_if_space:NT
\g_tmpa_clist
\tl_case:cnTF
\token_if_math_subscript:NF
\bool_if_p:n
\debug_suspend:
\skip_if_exist:NT
\hbox_set_to_wd:Nnn
\exp_args:Nnno
\tl_range_braced:nnn
\fp_gzero:c
\exp_args:Nnx
\muskip_set_eq:NN
\str_gset_eq:NN
\seq_set_eq:cc
\clist_new:c
\cs_if_exist_use:NTF
\intarray_gset_rand:cn
\file_if_exist:nT
\str_log:N
\token_if_eq_charcode_p:NN
\clist_gsort:cn
\fp_if_nan:nTF
\dim_case:nnTF
\hbox_to_zero:n
\tl_if_empty_p:N
\skip_if_exist_p:N
\c_sys_minute_int
\tl_if_empty:cTF
\tl_gput_right:cx
\seq_map_inline:cn
\quark_if_nil:oTF
\seq_gset_from_clist:Nn
\char_set_catcode_math_subscript:n
\sys_if_engine_xetex:F
\ior_get:NNT
\box_set_to_last:N
\token_if_eq_meaning:NNT
\seq_pop:NNF
\prop_gremove:NV
\bool_lazy_any:nT
\seq_pop:NNTF
\token_if_int_register:NTF
\vbox_gset:Nw
\prop_gput:Nno
\tl_put_right:cn
\tl_head:n
\prop_gput:cVn
\exp_args:NVV
\exp_args:Nnnc
\seq_remove_duplicates:N
\sys_if_shell_p:
\cs_set_protected:Npn
\prop_gpop:coN
\tl_if_empty:cT
\seq_gpop_left:cNTF
\clist_put_left:co
\use_iii:nnnn
\seq_log:N
\sys_if_rand_exist:T
\fp_compare:nT
\mode_if_inner:TF
\keys_define:nn
\tl_if_head_eq_catcode:oNTF
\c_zero_fp
\str_if_in:nnTF
\seq_if_in:NxF
\fp_compare_p:n
\prop_gput:Noo
\box_set_dp:cn
\exp_args:Noc
\seq_put_left:Nn
\token_if_macro:NT
\regex_extract_once:NnN
\clist_set_from_seq:cc
\char_titlecase:N
\cs_if_exist:NF
\msg_log:nn
\char_gset_active_eq:NN
\cs_if_exist_use:cT
\prop_if_empty:cTF
\seq_if_in:cxTF
\sys_if_shell_restricted:F
\hbox_set_end:
\sys_if_output_pdf_p:
\l_text_math_arg_tl
\tl_if_single_token_p:n
\tl_if_in:onTF
\token_if_eq_charcode:NNTF
\seq_pop_left:cNT
\fp_if_nan:nT
\msg_redirect_class:nn
\token_if_math_toggle_p:N
\tl_if_in:NnF
\iow_now:Nn
\sys_if_engine_ptex:TF
\regex_match:NnTF
\seq_gpush:cv
\box_if_exist:cT
\bool_if:cTF
\clist_gput_left:NV
\str_if_in:cnT
\sys_load_deprecation:
\seq_map_function:cN
\box_ht:c
\tl_if_in:nnTF
\msg_if_exist:nnF
\exp_last_unbraced:NNNf
\mode_if_math:TF
\mode_if_horizontal_p:
\box_gset_eq:cN
\c_empty_prop
\fp_max:nn
\str_gput_right:cn
\tl_if_head_eq_charcode:nNT
\int_rand:n
\prg_set_protected_conditional:Nnn
\tl_remove_all:Nn
\tl_if_head_eq_meaning_p:nN
\tl_if_single:NT
\int_compare:nT
\regex_set:Nn
\box_if_exist:NTF
\tl_show:N
\intarray_gset:cnn
\box_set_trim:cnnnn
\clist_rand_item:n
\exp_last_unbraced:Nx
\clist_get:NN
\tl_if_single_token:nTF
\msg_warning:nn
\regex_extract_all:nnNF
\clist_if_in:noTF
\mode_if_vertical:TF
\exp_last_unbraced:NcV
\tl_if_head_is_group:nT
\prop_gpop:cnN
\fp_to_decimal:N
\exp_args:NNNx
\flag_if_exist_p:n
\tl_greplace_once:cnn
\bool_if_exist:cTF
\cs_argument_spec:N
\l_text_math_delims_tl
\quark_if_recursion_tail_stop:o
\text_expand:n
\str_if_eq_p:Nc
\tl_gtrim_spaces:c
\exp_args:NV
\int_to_Alph:n
\clist_gput_right:cn
\token_if_primitive:NT
\bool_lazy_any:nTF
\file_compare_timestamp:nNnF
\hbox_set_to_wd:Nnw
\file_input_stop:
\dim_set:cn
\fp_zero:c
\char_set_catcode_comment:N
\vbox_set_top:Nn
\fp_if_exist_p:N
\cs_new_protected:cpn
\prop_if_exist_p:c
\seq_put_right:cn
\prop_set_eq:NN
\msg_expandable_error:nnnnnn
\sys_finalise:
\fp_to_tl:n
\str_use:N
\mode_if_horizontal:T
\seq_map_variable:Ncn
\peek_meaning_ignore_spaces:NT
\hcoffin_gset:Nn
\muskip_zero_new:N
\bool_set:Nn
\tl_if_in:onF
