export const themes : { [theme:string]: { foreground : string} } = 
{
    "Abyss" : { foreground : "#FFFFFF" },
    "Default Dark+" : { foreground : "#D4D4D4" },
    "Default Light+" : { foreground : "#000000" },
    "Default High Contrast" : { foreground : "#FFFFFF" },
    "Kimbie Dark" : { foreground : "#d3af86" },
    "Monokai" : { foreground : "#f8f8f2" },
    "Monokai Dimmed" : { foreground : "#c5c8c6" },
    "Quiet Light" : { foreground : "#333333" },
    "Red" : { foreground : "#F8F8F8" },
    "Solarized Dark" : { foreground : "#000000" },
    "Solarized Light" : { foreground : "#FFFFFF" },
    "Tomorrow Night Blue" : { foreground : "#ffffff" },
    "Visual Studio Dark" : { foreground : "#D4D4D4" },
    "Visual Studio Light" : { foreground : "#000000"},

    "Atom One Dark" : { foreground : "#ffffff" },
    "One Dark Pro" : { foreground : "#ffffff" },
    "One Dark Pro Vivid" : { foreground : "#ffffff" },
    "Dark+ Material" : { foreground : "#9E9E9E" },
    "Dracula" : { foreground : "#F8F8F2"},
    "Dracula Soft" : { foreground : "#F8F8F2"},
    "dark-plus-syntax" : { foreground : "#d4d4d4" },
    "Winter is Coming (Dark Blue)" : { foreground : "#a7dbf7" },
    "Winter is Coming (Dark)" : { foreground : "#a7dbf7" },
    "Winter is Coming (Light)" : { foreground : "#236ebf" },
    "Monokai Pro" : { foreground : "#FCFCFA" },
    "Monokai Pro (Filter Machine)" : { foreground : "#F2FFFC" },
    "Monokai Pro (Filter Octagon)" : { foreground : "#EAF2F1" },
    "Monokai Pro (Filter Ristretto)" : { foreground : "#FFF1F3" },
    "Monokai Pro (Filter Spectrum)" : { foreground : "#F7F1FF" },
}
