export const themeColorMap = {
    'Abyss': 'dark',
    'Default Dark+': 'dark',
    'Default Light+': 'light',
    'Visual Studio Dark': 'dark',
    'Visual Studio Light': 'light',
    'Default High Contrast': 'dark',
    'Kimbie Dark': 'dark',
    'Monokai Dimmed': 'dark',
    'Monokai': 'dark',
    'Quiet Light': 'light',
    'Red': 'dark',
    'vs-seti': 'dark',
    'Solarized Dark': 'dark',
    'Solarized Light': 'light',
    'Tomorrow Night Blue': 'dark',
    'One Dark Pro': 'dark',
    'One Dark Pro Vivid': 'dark',
    'One Dark Pro Bold': 'dark',
    'Material Theme': 'dark',
    'Material Theme High Contrast': 'dark',
    'Material Theme Darker': 'dark',
    'Material Theme Darker High Contrast': 'dark',
    'Material Theme Palenight': 'dark',
    'Material Theme Palenight High Contrast': 'dark',
    'Material Theme Ocean': 'dark',
    'Material Theme Ocean High Contrast': 'dark',
    'Material Theme Lighter': 'light',
    'Material Theme Lighter High Contrast': 'light',
    'Atom One Dark': 'dark',
    'Dracula': 'dark',
    'Dracula Soft': 'dark'
}
