name: LaTeX-Secure-Workspace Extension Package
env:
  cache-version: v12
on: [push]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
      with:
        node-version: '20'
    - name: Create extension package
      run: |
        npm ci
        npm run release
    - name: Archive extension package
      uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
      with:
        name: tex-workspace-secure
        path: tex-workspace-secure-*.vsix